//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.07 at 05:56:42 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}CAPPLUS_RXTG_LSTCTG"/&gt;
 *         &lt;element ref="{}CAPPLUS_RXTG_LEDSZ"/&gt;
 *         &lt;element ref="{}CAPPLUS_RXTG_LEQMAX"/&gt;
 *         &lt;element ref="{}CAPPLUS_RXTG_LLEQMAX"/&gt;
 *         &lt;element ref="{}CAPPLUS_RX_TG_LIST_DLH_TYPE_FTLLISHTYPE"/&gt;
 *         &lt;element ref="{}CAPPLUS_RX_TG_LIST_DLH_TYPE_FTLLISHID"/&gt;
 *         &lt;element ref="{}CAPPLUS_RXTG_RXTGLISTALIAS"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "capplusrxtglstctg",
    "capplusrxtgledsz",
    "capplusrxtgleqmax",
    "capplusrxtglleqmax",
    "capplusrxtglistdlhtypeftllishtype",
    "capplusrxtglistdlhtypeftllishid",
    "capplusrxtgrxtglistalias"
})
@XmlRootElement(name = "CAPPLUS_RX_TG_LIST_DLH_TYPE")
public class CAPPLUSRXTGLISTDLHTYPE {

    @XmlElement(name = "CAPPLUS_RXTG_LSTCTG", required = true)
    protected CAPPLUSRXTGLSTCTG capplusrxtglstctg;
    @XmlElement(name = "CAPPLUS_RXTG_LEDSZ", required = true)
    protected CAPPLUSRXTGLEDSZ capplusrxtgledsz;
    @XmlElement(name = "CAPPLUS_RXTG_LEQMAX", required = true)
    protected CAPPLUSRXTGLEQMAX capplusrxtgleqmax;
    @XmlElement(name = "CAPPLUS_RXTG_LLEQMAX", required = true)
    protected CAPPLUSRXTGLLEQMAX capplusrxtglleqmax;
    @XmlElement(name = "CAPPLUS_RX_TG_LIST_DLH_TYPE_FTLLISHTYPE", required = true)
    protected CAPPLUSRXTGLISTDLHTYPEFTLLISHTYPE capplusrxtglistdlhtypeftllishtype;
    @XmlElement(name = "CAPPLUS_RX_TG_LIST_DLH_TYPE_FTLLISHID", required = true)
    protected CAPPLUSRXTGLISTDLHTYPEFTLLISHID capplusrxtglistdlhtypeftllishid;
    @XmlElement(name = "CAPPLUS_RXTG_RXTGLISTALIAS", required = true)
    protected CAPPLUSRXTGRXTGLISTALIAS capplusrxtgrxtglistalias;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;

    /**
     * Gets the value of the capplusrxtglstctg property.
     * 
     * @return
     *     possible object is
     *     {@link CAPPLUSRXTGLSTCTG }
     *     
     */
    public CAPPLUSRXTGLSTCTG getCAPPLUSRXTGLSTCTG() {
        return capplusrxtglstctg;
    }

    /**
     * Sets the value of the capplusrxtglstctg property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAPPLUSRXTGLSTCTG }
     *     
     */
    public void setCAPPLUSRXTGLSTCTG(CAPPLUSRXTGLSTCTG value) {
        this.capplusrxtglstctg = value;
    }

    /**
     * Gets the value of the capplusrxtgledsz property.
     * 
     * @return
     *     possible object is
     *     {@link CAPPLUSRXTGLEDSZ }
     *     
     */
    public CAPPLUSRXTGLEDSZ getCAPPLUSRXTGLEDSZ() {
        return capplusrxtgledsz;
    }

    /**
     * Sets the value of the capplusrxtgledsz property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAPPLUSRXTGLEDSZ }
     *     
     */
    public void setCAPPLUSRXTGLEDSZ(CAPPLUSRXTGLEDSZ value) {
        this.capplusrxtgledsz = value;
    }

    /**
     * Gets the value of the capplusrxtgleqmax property.
     * 
     * @return
     *     possible object is
     *     {@link CAPPLUSRXTGLEQMAX }
     *     
     */
    public CAPPLUSRXTGLEQMAX getCAPPLUSRXTGLEQMAX() {
        return capplusrxtgleqmax;
    }

    /**
     * Sets the value of the capplusrxtgleqmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAPPLUSRXTGLEQMAX }
     *     
     */
    public void setCAPPLUSRXTGLEQMAX(CAPPLUSRXTGLEQMAX value) {
        this.capplusrxtgleqmax = value;
    }

    /**
     * Gets the value of the capplusrxtglleqmax property.
     * 
     * @return
     *     possible object is
     *     {@link CAPPLUSRXTGLLEQMAX }
     *     
     */
    public CAPPLUSRXTGLLEQMAX getCAPPLUSRXTGLLEQMAX() {
        return capplusrxtglleqmax;
    }

    /**
     * Sets the value of the capplusrxtglleqmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAPPLUSRXTGLLEQMAX }
     *     
     */
    public void setCAPPLUSRXTGLLEQMAX(CAPPLUSRXTGLLEQMAX value) {
        this.capplusrxtglleqmax = value;
    }

    /**
     * Gets the value of the capplusrxtglistdlhtypeftllishtype property.
     * 
     * @return
     *     possible object is
     *     {@link CAPPLUSRXTGLISTDLHTYPEFTLLISHTYPE }
     *     
     */
    public CAPPLUSRXTGLISTDLHTYPEFTLLISHTYPE getCAPPLUSRXTGLISTDLHTYPEFTLLISHTYPE() {
        return capplusrxtglistdlhtypeftllishtype;
    }

    /**
     * Sets the value of the capplusrxtglistdlhtypeftllishtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAPPLUSRXTGLISTDLHTYPEFTLLISHTYPE }
     *     
     */
    public void setCAPPLUSRXTGLISTDLHTYPEFTLLISHTYPE(CAPPLUSRXTGLISTDLHTYPEFTLLISHTYPE value) {
        this.capplusrxtglistdlhtypeftllishtype = value;
    }

    /**
     * Gets the value of the capplusrxtglistdlhtypeftllishid property.
     * 
     * @return
     *     possible object is
     *     {@link CAPPLUSRXTGLISTDLHTYPEFTLLISHID }
     *     
     */
    public CAPPLUSRXTGLISTDLHTYPEFTLLISHID getCAPPLUSRXTGLISTDLHTYPEFTLLISHID() {
        return capplusrxtglistdlhtypeftllishid;
    }

    /**
     * Sets the value of the capplusrxtglistdlhtypeftllishid property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAPPLUSRXTGLISTDLHTYPEFTLLISHID }
     *     
     */
    public void setCAPPLUSRXTGLISTDLHTYPEFTLLISHID(CAPPLUSRXTGLISTDLHTYPEFTLLISHID value) {
        this.capplusrxtglistdlhtypeftllishid = value;
    }

    /**
     * Gets the value of the capplusrxtgrxtglistalias property.
     * 
     * @return
     *     possible object is
     *     {@link CAPPLUSRXTGRXTGLISTALIAS }
     *     
     */
    public CAPPLUSRXTGRXTGLISTALIAS getCAPPLUSRXTGRXTGLISTALIAS() {
        return capplusrxtgrxtglistalias;
    }

    /**
     * Sets the value of the capplusrxtgrxtglistalias property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAPPLUSRXTGRXTGLISTALIAS }
     *     
     */
    public void setCAPPLUSRXTGRXTGLISTALIAS(CAPPLUSRXTGRXTGLISTALIAS value) {
        this.capplusrxtgrxtglistalias = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

}
