//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.05 at 02:22:03 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}VAC_TTSLANGPACK_TYPE_GRP"/&gt;
 *         &lt;element ref="{}VAC_TTSLANGPACK"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vacttslangpacktypegrp",
    "vacttslangpack"
})
@XmlRootElement(name = "CS_TTSLANGPACK_PARTITION")
public class CSTTSLANGPACKPARTITION {

    @XmlElement(name = "VAC_TTSLANGPACK_TYPE_GRP", required = true)
    protected VACTTSLANGPACKTYPEGRP vacttslangpacktypegrp;
    @XmlElement(name = "VAC_TTSLANGPACK", required = true)
    protected VACTTSLANGPACK vacttslangpack;

    /**
     * Gets the value of the vacttslangpacktypegrp property.
     * 
     * @return
     *     possible object is
     *     {@link VACTTSLANGPACKTYPEGRP }
     *     
     */
    public VACTTSLANGPACKTYPEGRP getVACTTSLANGPACKTYPEGRP() {
        return vacttslangpacktypegrp;
    }

    /**
     * Sets the value of the vacttslangpacktypegrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link VACTTSLANGPACKTYPEGRP }
     *     
     */
    public void setVACTTSLANGPACKTYPEGRP(VACTTSLANGPACKTYPEGRP value) {
        this.vacttslangpacktypegrp = value;
    }

    /**
     * Gets the value of the vacttslangpack property.
     * 
     * @return
     *     possible object is
     *     {@link VACTTSLANGPACK }
     *     
     */
    public VACTTSLANGPACK getVACTTSLANGPACK() {
        return vacttslangpack;
    }

    /**
     * Sets the value of the vacttslangpack property.
     * 
     * @param value
     *     allowed object is
     *     {@link VACTTSLANGPACK }
     *     
     */
    public void setVACTTSLANGPACK(VACTTSLANGPACK value) {
        this.vacttslangpack = value;
    }

}
