//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.07 at 05:56:42 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}FD_MAXZNCHQTY"/&gt;
 *         &lt;element ref="{}FD_CONVCAPBL"/&gt;
 *         &lt;element ref="{}FD_LTRCAPBL"/&gt;
 *         &lt;element ref="{}FD_MDCCONV"/&gt;
 *         &lt;element ref="{}FD_ENHPRVCPB"/&gt;
 *         &lt;element ref="{}FD_MDCLTR"/&gt;
 *         &lt;element ref="{}FD_DTMFCAPBL"/&gt;
 *         &lt;element ref="{}FD_MDCSTATUS"/&gt;
 *         &lt;element ref="{}FD_MDCMSG"/&gt;
 *         &lt;element ref="{}FD_MDCRTT"/&gt;
 *         &lt;element ref="{}FD_RATRSTEN"/&gt;
 *         &lt;element ref="{}FD_PRVCPB"/&gt;
 *         &lt;element ref="{}FD_F2CALLALERTENABLE"/&gt;
 *         &lt;element ref="{}FD_LANGSET"/&gt;
 *         &lt;element ref="{}FD_RADTYPE"/&gt;
 *         &lt;element ref="{}FD_SCANPRIOTYPE"/&gt;
 *         &lt;element ref="{}FD_CAOPERTYPE"/&gt;
 *         &lt;element ref="{}FD_CAWVOICEOPERTYPE"/&gt;
 *         &lt;element ref="{}FD_SCOPERTYPE"/&gt;
 *         &lt;element ref="{}FD_SELINHOPERTYPE"/&gt;
 *         &lt;element ref="{}FD_OTCAPBL"/&gt;
 *         &lt;element ref="{}FD_EMEROPERTYPE"/&gt;
 *         &lt;element ref="{}FD_PTTIDOPERTYPE"/&gt;
 *         &lt;element ref="{}FD_REMMONOPERTYPE"/&gt;
 *         &lt;element ref="{}FD_RADCHKOPERTYPE"/&gt;
 *         &lt;element ref="{}FD_RPTRACCOPERTYPE"/&gt;
 *         &lt;element ref="{}FD_EDITMODE"/&gt;
 *         &lt;element ref="{}FD_CHARSIZE"/&gt;
 *         &lt;element ref="{}FD_20KHZBWCPB"/&gt;
 *         &lt;element ref="{}FD_OBCPB"/&gt;
 *         &lt;element ref="{}FD_QCIICAPBL"/&gt;
 *         &lt;element ref="{}FD_MAXLTRPERQTY"/&gt;
 *         &lt;element ref="{}FD_MODELTYPE"/&gt;
 *         &lt;element ref="{}FD_FLSHCODECHAR"/&gt;
 *         &lt;element ref="{}FD_MAXCONVPERQTY"/&gt;
 *         &lt;element ref="{}FD_FLASHID01_00"/&gt;
 *         &lt;element ref="{}FD_FLASHID01_01"/&gt;
 *         &lt;element ref="{}FD_FLASHID01_02"/&gt;
 *         &lt;element ref="{}FD_FLASHID01_03"/&gt;
 *         &lt;element ref="{}FD_FLASHID02_00"/&gt;
 *         &lt;element ref="{}FD_FLASHID02_01"/&gt;
 *         &lt;element ref="{}FD_FLASHID02_02"/&gt;
 *         &lt;element ref="{}FD_FLASHID02_03"/&gt;
 *         &lt;element ref="{}FD_FLASHID03_00"/&gt;
 *         &lt;element ref="{}FD_FLASHID03_01"/&gt;
 *         &lt;element ref="{}FD_FLASHID03_02"/&gt;
 *         &lt;element ref="{}FD_FLASHID03_03"/&gt;
 *         &lt;element ref="{}FD_FLASHID04_00"/&gt;
 *         &lt;element ref="{}FD_FLASHID04_01"/&gt;
 *         &lt;element ref="{}FD_FLASHID04_02"/&gt;
 *         &lt;element ref="{}FD_FLASHID04_03"/&gt;
 *         &lt;element ref="{}FD_FLASHID"/&gt;
 *         &lt;element ref="{}FD_SMARTCPB"/&gt;
 *         &lt;element ref="{}FD_VSCAP"/&gt;
 *         &lt;element ref="{}FD_DIGEMERCALL"/&gt;
 *         &lt;element ref="{}FD_TELINTC"/&gt;
 *         &lt;element ref="{}FD_QCIIENC"/&gt;
 *         &lt;element ref="{}FD_CALLTNTAG"/&gt;
 *         &lt;element ref="{}FD_5TEMER"/&gt;
 *         &lt;element ref="{}FD_DIGRMIOPTYPE"/&gt;
 *         &lt;element ref="{}FD_DIGTRDIHBTOPT"/&gt;
 *         &lt;element ref="{}FD_DIGTELINTC"/&gt;
 *         &lt;element ref="{}FD_IMEKPTYPE"/&gt;
 *         &lt;element ref="{}FD_DEVTYPE"/&gt;
 *         &lt;element ref="{}FD_KEYPADAUTOLOCK"/&gt;
 *         &lt;element ref="{}FD_BATTERYINFORMATIONMENU"/&gt;
 *         &lt;element ref="{}FD_ANALOGSQUELCH"/&gt;
 *         &lt;element ref="{}FD_POWERLEVEL"/&gt;
 *         &lt;element ref="{}FD_BACKLIGHTTIMER"/&gt;
 *         &lt;element ref="{}FD_AUDIOACCESSORY"/&gt;
 *         &lt;element ref="{}FD_SAFETYINFORMATION"/&gt;
 *         &lt;element ref="{}FD_SCREENSAVER"/&gt;
 *         &lt;element ref="{}FD_JOBTICKET"/&gt;
 *         &lt;element ref="{}FD_WALLPAPER"/&gt;
 *         &lt;element ref="{}FD_VIBRATE"/&gt;
 *         &lt;element ref="{}FD_COVERTMODE"/&gt;
 *         &lt;element ref="{}FD_ACTIONLIST"/&gt;
 *         &lt;element ref="{}FD_BACKLIGHTAUTOON"/&gt;
 *         &lt;element ref="{}FD_DUALKNOBENABLE"/&gt;
 *         &lt;element ref="{}FD_PUBLICADDRESSENABLE"/&gt;
 *         &lt;element ref="{}FD_TELEMETRYENABLE"/&gt;
 *         &lt;element ref="{}FD_ANALOGSCRAMBLINGENABLE"/&gt;
 *         &lt;element ref="{}FD_DIGITALINTELLIGENCEAUDIOENABLE"/&gt;
 *         &lt;element ref="{}FD_USERSELECTIVEAUDIOPROFILE"/&gt;
 *         &lt;element ref="{}FD_RESERVED198_8"/&gt;
 *         &lt;element ref="{}FD_MENUALPHASEARCHENABLE"/&gt;
 *         &lt;element ref="{}FD_F2ALLCALLENCODEENABLE"/&gt;
 *         &lt;element ref="{}FD_PHOTOSENSORENABLE"/&gt;
 *         &lt;element ref="{}FD_F2RADIOCHECKENCODEENABLE"/&gt;
 *         &lt;element ref="{}FD_USBHIDDATAROUTINGENABLE"/&gt;
 *         &lt;element ref="{}FD_FLEXIBLERXLIST"/&gt;
 *         &lt;element ref="{}FD_MICROPHONEDYNAMICDISTORTIONCONTROL"/&gt;
 *         &lt;element ref="{}FD_HOWLINGSUPPRESSOR"/&gt;
 *         &lt;element ref="{}FD_COUNTERFEITBATTERYINDICATION"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fdmaxznchqty",
    "fdconvcapbl",
    "fdltrcapbl",
    "fdmdcconv",
    "fdenhprvcpb",
    "fdmdcltr",
    "fddtmfcapbl",
    "fdmdcstatus",
    "fdmdcmsg",
    "fdmdcrtt",
    "fdratrsten",
    "fdprvcpb",
    "fdf2CALLALERTENABLE",
    "fdlangset",
    "fdradtype",
    "fdscanpriotype",
    "fdcaopertype",
    "fdcawvoiceopertype",
    "fdscopertype",
    "fdselinhopertype",
    "fdotcapbl",
    "fdemeropertype",
    "fdpttidopertype",
    "fdremmonopertype",
    "fdradchkopertype",
    "fdrptraccopertype",
    "fdeditmode",
    "fdcharsize",
    "fd20KHZBWCPB",
    "fdobcpb",
    "fdqciicapbl",
    "fdmaxltrperqty",
    "fdmodeltype",
    "fdflshcodechar",
    "fdmaxconvperqty",
    "fdflashid0100",
    "fdflashid0101",
    "fdflashid0102",
    "fdflashid0103",
    "fdflashid0200",
    "fdflashid0201",
    "fdflashid0202",
    "fdflashid0203",
    "fdflashid0300",
    "fdflashid0301",
    "fdflashid0302",
    "fdflashid0303",
    "fdflashid0400",
    "fdflashid0401",
    "fdflashid0402",
    "fdflashid0403",
    "fdflashid",
    "fdsmartcpb",
    "fdvscap",
    "fddigemercall",
    "fdtelintc",
    "fdqciienc",
    "fdcalltntag",
    "fd5TEMER",
    "fddigrmioptype",
    "fddigtrdihbtopt",
    "fddigtelintc",
    "fdimekptype",
    "fddevtype",
    "fdkeypadautolock",
    "fdbatteryinformationmenu",
    "fdanalogsquelch",
    "fdpowerlevel",
    "fdbacklighttimer",
    "fdaudioaccessory",
    "fdsafetyinformation",
    "fdscreensaver",
    "fdjobticket",
    "fdwallpaper",
    "fdvibrate",
    "fdcovertmode",
    "fdactionlist",
    "fdbacklightautoon",
    "fddualknobenable",
    "fdpublicaddressenable",
    "fdtelemetryenable",
    "fdanalogscramblingenable",
    "fddigitalintelligenceaudioenable",
    "fduserselectiveaudioprofile",
    "fdreserved1988",
    "fdmenualphasearchenable",
    "fdf2ALLCALLENCODEENABLE",
    "fdphotosensorenable",
    "fdf2RADIOCHECKENCODEENABLE",
    "fdusbhiddataroutingenable",
    "fdflexiblerxlist",
    "fdmicrophonedynamicdistortioncontrol",
    "fdhowlingsuppressor",
    "fdcounterfeitbatteryindication"
})
@XmlRootElement(name = "FEAT_DESCR_CMP_TYPE")
public class FEATDESCRCMPTYPE {

    @XmlElement(name = "FD_MAXZNCHQTY", required = true)
    protected FDMAXZNCHQTY fdmaxznchqty;
    @XmlElement(name = "FD_CONVCAPBL", required = true)
    protected FDCONVCAPBL fdconvcapbl;
    @XmlElement(name = "FD_LTRCAPBL", required = true)
    protected FDLTRCAPBL fdltrcapbl;
    @XmlElement(name = "FD_MDCCONV", required = true)
    protected FDMDCCONV fdmdcconv;
    @XmlElement(name = "FD_ENHPRVCPB", required = true)
    protected FDENHPRVCPB fdenhprvcpb;
    @XmlElement(name = "FD_MDCLTR", required = true)
    protected FDMDCLTR fdmdcltr;
    @XmlElement(name = "FD_DTMFCAPBL", required = true)
    protected FDDTMFCAPBL fddtmfcapbl;
    @XmlElement(name = "FD_MDCSTATUS", required = true)
    protected FDMDCSTATUS fdmdcstatus;
    @XmlElement(name = "FD_MDCMSG", required = true)
    protected FDMDCMSG fdmdcmsg;
    @XmlElement(name = "FD_MDCRTT", required = true)
    protected FDMDCRTT fdmdcrtt;
    @XmlElement(name = "FD_RATRSTEN", required = true)
    protected FDRATRSTEN fdratrsten;
    @XmlElement(name = "FD_PRVCPB", required = true)
    protected FDPRVCPB fdprvcpb;
    @XmlElement(name = "FD_F2CALLALERTENABLE", required = true)
    protected FDF2CALLALERTENABLE fdf2CALLALERTENABLE;
    @XmlElement(name = "FD_LANGSET", required = true)
    protected FDLANGSET fdlangset;
    @XmlElement(name = "FD_RADTYPE", required = true)
    protected FDRADTYPE fdradtype;
    @XmlElement(name = "FD_SCANPRIOTYPE", required = true)
    protected FDSCANPRIOTYPE fdscanpriotype;
    @XmlElement(name = "FD_CAOPERTYPE", required = true)
    protected FDCAOPERTYPE fdcaopertype;
    @XmlElement(name = "FD_CAWVOICEOPERTYPE", required = true)
    protected FDCAWVOICEOPERTYPE fdcawvoiceopertype;
    @XmlElement(name = "FD_SCOPERTYPE", required = true)
    protected FDSCOPERTYPE fdscopertype;
    @XmlElement(name = "FD_SELINHOPERTYPE", required = true)
    protected FDSELINHOPERTYPE fdselinhopertype;
    @XmlElement(name = "FD_OTCAPBL", required = true)
    protected FDOTCAPBL fdotcapbl;
    @XmlElement(name = "FD_EMEROPERTYPE", required = true)
    protected FDEMEROPERTYPE fdemeropertype;
    @XmlElement(name = "FD_PTTIDOPERTYPE", required = true)
    protected FDPTTIDOPERTYPE fdpttidopertype;
    @XmlElement(name = "FD_REMMONOPERTYPE", required = true)
    protected FDREMMONOPERTYPE fdremmonopertype;
    @XmlElement(name = "FD_RADCHKOPERTYPE", required = true)
    protected FDRADCHKOPERTYPE fdradchkopertype;
    @XmlElement(name = "FD_RPTRACCOPERTYPE", required = true)
    protected FDRPTRACCOPERTYPE fdrptraccopertype;
    @XmlElement(name = "FD_EDITMODE", required = true)
    protected FDEDITMODE fdeditmode;
    @XmlElement(name = "FD_CHARSIZE", required = true)
    protected FDCHARSIZE fdcharsize;
    @XmlElement(name = "FD_20KHZBWCPB", required = true)
    protected FD20KHZBWCPB fd20KHZBWCPB;
    @XmlElement(name = "FD_OBCPB", required = true)
    protected FDOBCPB fdobcpb;
    @XmlElement(name = "FD_QCIICAPBL", required = true)
    protected FDQCIICAPBL fdqciicapbl;
    @XmlElement(name = "FD_MAXLTRPERQTY", required = true)
    protected FDMAXLTRPERQTY fdmaxltrperqty;
    @XmlElement(name = "FD_MODELTYPE", required = true)
    protected FDMODELTYPE fdmodeltype;
    @XmlElement(name = "FD_FLSHCODECHAR", required = true)
    protected FDFLSHCODECHAR fdflshcodechar;
    @XmlElement(name = "FD_MAXCONVPERQTY", required = true)
    protected FDMAXCONVPERQTY fdmaxconvperqty;
    @XmlElement(name = "FD_FLASHID01_00", required = true)
    protected FDFLASHID0100 fdflashid0100;
    @XmlElement(name = "FD_FLASHID01_01", required = true)
    protected FDFLASHID0101 fdflashid0101;
    @XmlElement(name = "FD_FLASHID01_02", required = true)
    protected FDFLASHID0102 fdflashid0102;
    @XmlElement(name = "FD_FLASHID01_03", required = true)
    protected FDFLASHID0103 fdflashid0103;
    @XmlElement(name = "FD_FLASHID02_00", required = true)
    protected FDFLASHID0200 fdflashid0200;
    @XmlElement(name = "FD_FLASHID02_01", required = true)
    protected FDFLASHID0201 fdflashid0201;
    @XmlElement(name = "FD_FLASHID02_02", required = true)
    protected FDFLASHID0202 fdflashid0202;
    @XmlElement(name = "FD_FLASHID02_03", required = true)
    protected FDFLASHID0203 fdflashid0203;
    @XmlElement(name = "FD_FLASHID03_00", required = true)
    protected FDFLASHID0300 fdflashid0300;
    @XmlElement(name = "FD_FLASHID03_01", required = true)
    protected FDFLASHID0301 fdflashid0301;
    @XmlElement(name = "FD_FLASHID03_02", required = true)
    protected FDFLASHID0302 fdflashid0302;
    @XmlElement(name = "FD_FLASHID03_03", required = true)
    protected FDFLASHID0303 fdflashid0303;
    @XmlElement(name = "FD_FLASHID04_00", required = true)
    protected FDFLASHID0400 fdflashid0400;
    @XmlElement(name = "FD_FLASHID04_01", required = true)
    protected FDFLASHID0401 fdflashid0401;
    @XmlElement(name = "FD_FLASHID04_02", required = true)
    protected FDFLASHID0402 fdflashid0402;
    @XmlElement(name = "FD_FLASHID04_03", required = true)
    protected FDFLASHID0403 fdflashid0403;
    @XmlElement(name = "FD_FLASHID", required = true)
    protected FDFLASHID fdflashid;
    @XmlElement(name = "FD_SMARTCPB", required = true)
    protected FDSMARTCPB fdsmartcpb;
    @XmlElement(name = "FD_VSCAP", required = true)
    protected FDVSCAP fdvscap;
    @XmlElement(name = "FD_DIGEMERCALL", required = true)
    protected FDDIGEMERCALL fddigemercall;
    @XmlElement(name = "FD_TELINTC", required = true)
    protected FDTELINTC fdtelintc;
    @XmlElement(name = "FD_QCIIENC", required = true)
    protected FDQCIIENC fdqciienc;
    @XmlElement(name = "FD_CALLTNTAG", required = true)
    protected FDCALLTNTAG fdcalltntag;
    @XmlElement(name = "FD_5TEMER", required = true)
    protected FD5TEMER fd5TEMER;
    @XmlElement(name = "FD_DIGRMIOPTYPE", required = true)
    protected FDDIGRMIOPTYPE fddigrmioptype;
    @XmlElement(name = "FD_DIGTRDIHBTOPT", required = true)
    protected FDDIGTRDIHBTOPT fddigtrdihbtopt;
    @XmlElement(name = "FD_DIGTELINTC", required = true)
    protected FDDIGTELINTC fddigtelintc;
    @XmlElement(name = "FD_IMEKPTYPE", required = true)
    protected FDIMEKPTYPE fdimekptype;
    @XmlElement(name = "FD_DEVTYPE", required = true)
    protected FDDEVTYPE fddevtype;
    @XmlElement(name = "FD_KEYPADAUTOLOCK", required = true)
    protected FDKEYPADAUTOLOCK fdkeypadautolock;
    @XmlElement(name = "FD_BATTERYINFORMATIONMENU", required = true)
    protected FDBATTERYINFORMATIONMENU fdbatteryinformationmenu;
    @XmlElement(name = "FD_ANALOGSQUELCH", required = true)
    protected FDANALOGSQUELCH fdanalogsquelch;
    @XmlElement(name = "FD_POWERLEVEL", required = true)
    protected FDPOWERLEVEL fdpowerlevel;
    @XmlElement(name = "FD_BACKLIGHTTIMER", required = true)
    protected FDBACKLIGHTTIMER fdbacklighttimer;
    @XmlElement(name = "FD_AUDIOACCESSORY", required = true)
    protected FDAUDIOACCESSORY fdaudioaccessory;
    @XmlElement(name = "FD_SAFETYINFORMATION", required = true)
    protected FDSAFETYINFORMATION fdsafetyinformation;
    @XmlElement(name = "FD_SCREENSAVER", required = true)
    protected FDSCREENSAVER fdscreensaver;
    @XmlElement(name = "FD_JOBTICKET", required = true)
    protected FDJOBTICKET fdjobticket;
    @XmlElement(name = "FD_WALLPAPER", required = true)
    protected FDWALLPAPER fdwallpaper;
    @XmlElement(name = "FD_VIBRATE", required = true)
    protected FDVIBRATE fdvibrate;
    @XmlElement(name = "FD_COVERTMODE", required = true)
    protected FDCOVERTMODE fdcovertmode;
    @XmlElement(name = "FD_ACTIONLIST", required = true)
    protected FDACTIONLIST fdactionlist;
    @XmlElement(name = "FD_BACKLIGHTAUTOON", required = true)
    protected FDBACKLIGHTAUTOON fdbacklightautoon;
    @XmlElement(name = "FD_DUALKNOBENABLE", required = true)
    protected FDDUALKNOBENABLE fddualknobenable;
    @XmlElement(name = "FD_PUBLICADDRESSENABLE", required = true)
    protected FDPUBLICADDRESSENABLE fdpublicaddressenable;
    @XmlElement(name = "FD_TELEMETRYENABLE", required = true)
    protected FDTELEMETRYENABLE fdtelemetryenable;
    @XmlElement(name = "FD_ANALOGSCRAMBLINGENABLE", required = true)
    protected FDANALOGSCRAMBLINGENABLE fdanalogscramblingenable;
    @XmlElement(name = "FD_DIGITALINTELLIGENCEAUDIOENABLE", required = true)
    protected FDDIGITALINTELLIGENCEAUDIOENABLE fddigitalintelligenceaudioenable;
    @XmlElement(name = "FD_USERSELECTIVEAUDIOPROFILE", required = true)
    protected FDUSERSELECTIVEAUDIOPROFILE fduserselectiveaudioprofile;
    @XmlElement(name = "FD_RESERVED198_8", required = true)
    protected FDRESERVED1988 fdreserved1988;
    @XmlElement(name = "FD_MENUALPHASEARCHENABLE", required = true)
    protected FDMENUALPHASEARCHENABLE fdmenualphasearchenable;
    @XmlElement(name = "FD_F2ALLCALLENCODEENABLE", required = true)
    protected FDF2ALLCALLENCODEENABLE fdf2ALLCALLENCODEENABLE;
    @XmlElement(name = "FD_PHOTOSENSORENABLE", required = true)
    protected FDPHOTOSENSORENABLE fdphotosensorenable;
    @XmlElement(name = "FD_F2RADIOCHECKENCODEENABLE", required = true)
    protected FDF2RADIOCHECKENCODEENABLE fdf2RADIOCHECKENCODEENABLE;
    @XmlElement(name = "FD_USBHIDDATAROUTINGENABLE", required = true)
    protected FDUSBHIDDATAROUTINGENABLE fdusbhiddataroutingenable;
    @XmlElement(name = "FD_FLEXIBLERXLIST", required = true)
    protected FDFLEXIBLERXLIST fdflexiblerxlist;
    @XmlElement(name = "FD_MICROPHONEDYNAMICDISTORTIONCONTROL", required = true)
    protected FDMICROPHONEDYNAMICDISTORTIONCONTROL fdmicrophonedynamicdistortioncontrol;
    @XmlElement(name = "FD_HOWLINGSUPPRESSOR", required = true)
    protected FDHOWLINGSUPPRESSOR fdhowlingsuppressor;
    @XmlElement(name = "FD_COUNTERFEITBATTERYINDICATION", required = true)
    protected FDCOUNTERFEITBATTERYINDICATION fdcounterfeitbatteryindication;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;

    /**
     * Gets the value of the fdmaxznchqty property.
     * 
     * @return
     *     possible object is
     *     {@link FDMAXZNCHQTY }
     *     
     */
    public FDMAXZNCHQTY getFDMAXZNCHQTY() {
        return fdmaxznchqty;
    }

    /**
     * Sets the value of the fdmaxznchqty property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDMAXZNCHQTY }
     *     
     */
    public void setFDMAXZNCHQTY(FDMAXZNCHQTY value) {
        this.fdmaxznchqty = value;
    }

    /**
     * Gets the value of the fdconvcapbl property.
     * 
     * @return
     *     possible object is
     *     {@link FDCONVCAPBL }
     *     
     */
    public FDCONVCAPBL getFDCONVCAPBL() {
        return fdconvcapbl;
    }

    /**
     * Sets the value of the fdconvcapbl property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDCONVCAPBL }
     *     
     */
    public void setFDCONVCAPBL(FDCONVCAPBL value) {
        this.fdconvcapbl = value;
    }

    /**
     * Gets the value of the fdltrcapbl property.
     * 
     * @return
     *     possible object is
     *     {@link FDLTRCAPBL }
     *     
     */
    public FDLTRCAPBL getFDLTRCAPBL() {
        return fdltrcapbl;
    }

    /**
     * Sets the value of the fdltrcapbl property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDLTRCAPBL }
     *     
     */
    public void setFDLTRCAPBL(FDLTRCAPBL value) {
        this.fdltrcapbl = value;
    }

    /**
     * Gets the value of the fdmdcconv property.
     * 
     * @return
     *     possible object is
     *     {@link FDMDCCONV }
     *     
     */
    public FDMDCCONV getFDMDCCONV() {
        return fdmdcconv;
    }

    /**
     * Sets the value of the fdmdcconv property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDMDCCONV }
     *     
     */
    public void setFDMDCCONV(FDMDCCONV value) {
        this.fdmdcconv = value;
    }

    /**
     * Gets the value of the fdenhprvcpb property.
     * 
     * @return
     *     possible object is
     *     {@link FDENHPRVCPB }
     *     
     */
    public FDENHPRVCPB getFDENHPRVCPB() {
        return fdenhprvcpb;
    }

    /**
     * Sets the value of the fdenhprvcpb property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDENHPRVCPB }
     *     
     */
    public void setFDENHPRVCPB(FDENHPRVCPB value) {
        this.fdenhprvcpb = value;
    }

    /**
     * Gets the value of the fdmdcltr property.
     * 
     * @return
     *     possible object is
     *     {@link FDMDCLTR }
     *     
     */
    public FDMDCLTR getFDMDCLTR() {
        return fdmdcltr;
    }

    /**
     * Sets the value of the fdmdcltr property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDMDCLTR }
     *     
     */
    public void setFDMDCLTR(FDMDCLTR value) {
        this.fdmdcltr = value;
    }

    /**
     * Gets the value of the fddtmfcapbl property.
     * 
     * @return
     *     possible object is
     *     {@link FDDTMFCAPBL }
     *     
     */
    public FDDTMFCAPBL getFDDTMFCAPBL() {
        return fddtmfcapbl;
    }

    /**
     * Sets the value of the fddtmfcapbl property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDDTMFCAPBL }
     *     
     */
    public void setFDDTMFCAPBL(FDDTMFCAPBL value) {
        this.fddtmfcapbl = value;
    }

    /**
     * Gets the value of the fdmdcstatus property.
     * 
     * @return
     *     possible object is
     *     {@link FDMDCSTATUS }
     *     
     */
    public FDMDCSTATUS getFDMDCSTATUS() {
        return fdmdcstatus;
    }

    /**
     * Sets the value of the fdmdcstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDMDCSTATUS }
     *     
     */
    public void setFDMDCSTATUS(FDMDCSTATUS value) {
        this.fdmdcstatus = value;
    }

    /**
     * Gets the value of the fdmdcmsg property.
     * 
     * @return
     *     possible object is
     *     {@link FDMDCMSG }
     *     
     */
    public FDMDCMSG getFDMDCMSG() {
        return fdmdcmsg;
    }

    /**
     * Sets the value of the fdmdcmsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDMDCMSG }
     *     
     */
    public void setFDMDCMSG(FDMDCMSG value) {
        this.fdmdcmsg = value;
    }

    /**
     * Gets the value of the fdmdcrtt property.
     * 
     * @return
     *     possible object is
     *     {@link FDMDCRTT }
     *     
     */
    public FDMDCRTT getFDMDCRTT() {
        return fdmdcrtt;
    }

    /**
     * Sets the value of the fdmdcrtt property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDMDCRTT }
     *     
     */
    public void setFDMDCRTT(FDMDCRTT value) {
        this.fdmdcrtt = value;
    }

    /**
     * Gets the value of the fdratrsten property.
     * 
     * @return
     *     possible object is
     *     {@link FDRATRSTEN }
     *     
     */
    public FDRATRSTEN getFDRATRSTEN() {
        return fdratrsten;
    }

    /**
     * Sets the value of the fdratrsten property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDRATRSTEN }
     *     
     */
    public void setFDRATRSTEN(FDRATRSTEN value) {
        this.fdratrsten = value;
    }

    /**
     * Gets the value of the fdprvcpb property.
     * 
     * @return
     *     possible object is
     *     {@link FDPRVCPB }
     *     
     */
    public FDPRVCPB getFDPRVCPB() {
        return fdprvcpb;
    }

    /**
     * Sets the value of the fdprvcpb property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDPRVCPB }
     *     
     */
    public void setFDPRVCPB(FDPRVCPB value) {
        this.fdprvcpb = value;
    }

    /**
     * Gets the value of the fdf2CALLALERTENABLE property.
     * 
     * @return
     *     possible object is
     *     {@link FDF2CALLALERTENABLE }
     *     
     */
    public FDF2CALLALERTENABLE getFDF2CALLALERTENABLE() {
        return fdf2CALLALERTENABLE;
    }

    /**
     * Sets the value of the fdf2CALLALERTENABLE property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDF2CALLALERTENABLE }
     *     
     */
    public void setFDF2CALLALERTENABLE(FDF2CALLALERTENABLE value) {
        this.fdf2CALLALERTENABLE = value;
    }

    /**
     * Gets the value of the fdlangset property.
     * 
     * @return
     *     possible object is
     *     {@link FDLANGSET }
     *     
     */
    public FDLANGSET getFDLANGSET() {
        return fdlangset;
    }

    /**
     * Sets the value of the fdlangset property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDLANGSET }
     *     
     */
    public void setFDLANGSET(FDLANGSET value) {
        this.fdlangset = value;
    }

    /**
     * Gets the value of the fdradtype property.
     * 
     * @return
     *     possible object is
     *     {@link FDRADTYPE }
     *     
     */
    public FDRADTYPE getFDRADTYPE() {
        return fdradtype;
    }

    /**
     * Sets the value of the fdradtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDRADTYPE }
     *     
     */
    public void setFDRADTYPE(FDRADTYPE value) {
        this.fdradtype = value;
    }

    /**
     * Gets the value of the fdscanpriotype property.
     * 
     * @return
     *     possible object is
     *     {@link FDSCANPRIOTYPE }
     *     
     */
    public FDSCANPRIOTYPE getFDSCANPRIOTYPE() {
        return fdscanpriotype;
    }

    /**
     * Sets the value of the fdscanpriotype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDSCANPRIOTYPE }
     *     
     */
    public void setFDSCANPRIOTYPE(FDSCANPRIOTYPE value) {
        this.fdscanpriotype = value;
    }

    /**
     * Gets the value of the fdcaopertype property.
     * 
     * @return
     *     possible object is
     *     {@link FDCAOPERTYPE }
     *     
     */
    public FDCAOPERTYPE getFDCAOPERTYPE() {
        return fdcaopertype;
    }

    /**
     * Sets the value of the fdcaopertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDCAOPERTYPE }
     *     
     */
    public void setFDCAOPERTYPE(FDCAOPERTYPE value) {
        this.fdcaopertype = value;
    }

    /**
     * Gets the value of the fdcawvoiceopertype property.
     * 
     * @return
     *     possible object is
     *     {@link FDCAWVOICEOPERTYPE }
     *     
     */
    public FDCAWVOICEOPERTYPE getFDCAWVOICEOPERTYPE() {
        return fdcawvoiceopertype;
    }

    /**
     * Sets the value of the fdcawvoiceopertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDCAWVOICEOPERTYPE }
     *     
     */
    public void setFDCAWVOICEOPERTYPE(FDCAWVOICEOPERTYPE value) {
        this.fdcawvoiceopertype = value;
    }

    /**
     * Gets the value of the fdscopertype property.
     * 
     * @return
     *     possible object is
     *     {@link FDSCOPERTYPE }
     *     
     */
    public FDSCOPERTYPE getFDSCOPERTYPE() {
        return fdscopertype;
    }

    /**
     * Sets the value of the fdscopertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDSCOPERTYPE }
     *     
     */
    public void setFDSCOPERTYPE(FDSCOPERTYPE value) {
        this.fdscopertype = value;
    }

    /**
     * Gets the value of the fdselinhopertype property.
     * 
     * @return
     *     possible object is
     *     {@link FDSELINHOPERTYPE }
     *     
     */
    public FDSELINHOPERTYPE getFDSELINHOPERTYPE() {
        return fdselinhopertype;
    }

    /**
     * Sets the value of the fdselinhopertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDSELINHOPERTYPE }
     *     
     */
    public void setFDSELINHOPERTYPE(FDSELINHOPERTYPE value) {
        this.fdselinhopertype = value;
    }

    /**
     * Gets the value of the fdotcapbl property.
     * 
     * @return
     *     possible object is
     *     {@link FDOTCAPBL }
     *     
     */
    public FDOTCAPBL getFDOTCAPBL() {
        return fdotcapbl;
    }

    /**
     * Sets the value of the fdotcapbl property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDOTCAPBL }
     *     
     */
    public void setFDOTCAPBL(FDOTCAPBL value) {
        this.fdotcapbl = value;
    }

    /**
     * Gets the value of the fdemeropertype property.
     * 
     * @return
     *     possible object is
     *     {@link FDEMEROPERTYPE }
     *     
     */
    public FDEMEROPERTYPE getFDEMEROPERTYPE() {
        return fdemeropertype;
    }

    /**
     * Sets the value of the fdemeropertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDEMEROPERTYPE }
     *     
     */
    public void setFDEMEROPERTYPE(FDEMEROPERTYPE value) {
        this.fdemeropertype = value;
    }

    /**
     * Gets the value of the fdpttidopertype property.
     * 
     * @return
     *     possible object is
     *     {@link FDPTTIDOPERTYPE }
     *     
     */
    public FDPTTIDOPERTYPE getFDPTTIDOPERTYPE() {
        return fdpttidopertype;
    }

    /**
     * Sets the value of the fdpttidopertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDPTTIDOPERTYPE }
     *     
     */
    public void setFDPTTIDOPERTYPE(FDPTTIDOPERTYPE value) {
        this.fdpttidopertype = value;
    }

    /**
     * Gets the value of the fdremmonopertype property.
     * 
     * @return
     *     possible object is
     *     {@link FDREMMONOPERTYPE }
     *     
     */
    public FDREMMONOPERTYPE getFDREMMONOPERTYPE() {
        return fdremmonopertype;
    }

    /**
     * Sets the value of the fdremmonopertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDREMMONOPERTYPE }
     *     
     */
    public void setFDREMMONOPERTYPE(FDREMMONOPERTYPE value) {
        this.fdremmonopertype = value;
    }

    /**
     * Gets the value of the fdradchkopertype property.
     * 
     * @return
     *     possible object is
     *     {@link FDRADCHKOPERTYPE }
     *     
     */
    public FDRADCHKOPERTYPE getFDRADCHKOPERTYPE() {
        return fdradchkopertype;
    }

    /**
     * Sets the value of the fdradchkopertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDRADCHKOPERTYPE }
     *     
     */
    public void setFDRADCHKOPERTYPE(FDRADCHKOPERTYPE value) {
        this.fdradchkopertype = value;
    }

    /**
     * Gets the value of the fdrptraccopertype property.
     * 
     * @return
     *     possible object is
     *     {@link FDRPTRACCOPERTYPE }
     *     
     */
    public FDRPTRACCOPERTYPE getFDRPTRACCOPERTYPE() {
        return fdrptraccopertype;
    }

    /**
     * Sets the value of the fdrptraccopertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDRPTRACCOPERTYPE }
     *     
     */
    public void setFDRPTRACCOPERTYPE(FDRPTRACCOPERTYPE value) {
        this.fdrptraccopertype = value;
    }

    /**
     * Gets the value of the fdeditmode property.
     * 
     * @return
     *     possible object is
     *     {@link FDEDITMODE }
     *     
     */
    public FDEDITMODE getFDEDITMODE() {
        return fdeditmode;
    }

    /**
     * Sets the value of the fdeditmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDEDITMODE }
     *     
     */
    public void setFDEDITMODE(FDEDITMODE value) {
        this.fdeditmode = value;
    }

    /**
     * Gets the value of the fdcharsize property.
     * 
     * @return
     *     possible object is
     *     {@link FDCHARSIZE }
     *     
     */
    public FDCHARSIZE getFDCHARSIZE() {
        return fdcharsize;
    }

    /**
     * Sets the value of the fdcharsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDCHARSIZE }
     *     
     */
    public void setFDCHARSIZE(FDCHARSIZE value) {
        this.fdcharsize = value;
    }

    /**
     * Gets the value of the fd20KHZBWCPB property.
     * 
     * @return
     *     possible object is
     *     {@link FD20KHZBWCPB }
     *     
     */
    public FD20KHZBWCPB getFD20KHZBWCPB() {
        return fd20KHZBWCPB;
    }

    /**
     * Sets the value of the fd20KHZBWCPB property.
     * 
     * @param value
     *     allowed object is
     *     {@link FD20KHZBWCPB }
     *     
     */
    public void setFD20KHZBWCPB(FD20KHZBWCPB value) {
        this.fd20KHZBWCPB = value;
    }

    /**
     * Gets the value of the fdobcpb property.
     * 
     * @return
     *     possible object is
     *     {@link FDOBCPB }
     *     
     */
    public FDOBCPB getFDOBCPB() {
        return fdobcpb;
    }

    /**
     * Sets the value of the fdobcpb property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDOBCPB }
     *     
     */
    public void setFDOBCPB(FDOBCPB value) {
        this.fdobcpb = value;
    }

    /**
     * Gets the value of the fdqciicapbl property.
     * 
     * @return
     *     possible object is
     *     {@link FDQCIICAPBL }
     *     
     */
    public FDQCIICAPBL getFDQCIICAPBL() {
        return fdqciicapbl;
    }

    /**
     * Sets the value of the fdqciicapbl property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDQCIICAPBL }
     *     
     */
    public void setFDQCIICAPBL(FDQCIICAPBL value) {
        this.fdqciicapbl = value;
    }

    /**
     * Gets the value of the fdmaxltrperqty property.
     * 
     * @return
     *     possible object is
     *     {@link FDMAXLTRPERQTY }
     *     
     */
    public FDMAXLTRPERQTY getFDMAXLTRPERQTY() {
        return fdmaxltrperqty;
    }

    /**
     * Sets the value of the fdmaxltrperqty property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDMAXLTRPERQTY }
     *     
     */
    public void setFDMAXLTRPERQTY(FDMAXLTRPERQTY value) {
        this.fdmaxltrperqty = value;
    }

    /**
     * Gets the value of the fdmodeltype property.
     * 
     * @return
     *     possible object is
     *     {@link FDMODELTYPE }
     *     
     */
    public FDMODELTYPE getFDMODELTYPE() {
        return fdmodeltype;
    }

    /**
     * Sets the value of the fdmodeltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDMODELTYPE }
     *     
     */
    public void setFDMODELTYPE(FDMODELTYPE value) {
        this.fdmodeltype = value;
    }

    /**
     * Gets the value of the fdflshcodechar property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLSHCODECHAR }
     *     
     */
    public FDFLSHCODECHAR getFDFLSHCODECHAR() {
        return fdflshcodechar;
    }

    /**
     * Sets the value of the fdflshcodechar property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLSHCODECHAR }
     *     
     */
    public void setFDFLSHCODECHAR(FDFLSHCODECHAR value) {
        this.fdflshcodechar = value;
    }

    /**
     * Gets the value of the fdmaxconvperqty property.
     * 
     * @return
     *     possible object is
     *     {@link FDMAXCONVPERQTY }
     *     
     */
    public FDMAXCONVPERQTY getFDMAXCONVPERQTY() {
        return fdmaxconvperqty;
    }

    /**
     * Sets the value of the fdmaxconvperqty property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDMAXCONVPERQTY }
     *     
     */
    public void setFDMAXCONVPERQTY(FDMAXCONVPERQTY value) {
        this.fdmaxconvperqty = value;
    }

    /**
     * Gets the value of the fdflashid0100 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0100 }
     *     
     */
    public FDFLASHID0100 getFDFLASHID0100() {
        return fdflashid0100;
    }

    /**
     * Sets the value of the fdflashid0100 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0100 }
     *     
     */
    public void setFDFLASHID0100(FDFLASHID0100 value) {
        this.fdflashid0100 = value;
    }

    /**
     * Gets the value of the fdflashid0101 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0101 }
     *     
     */
    public FDFLASHID0101 getFDFLASHID0101() {
        return fdflashid0101;
    }

    /**
     * Sets the value of the fdflashid0101 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0101 }
     *     
     */
    public void setFDFLASHID0101(FDFLASHID0101 value) {
        this.fdflashid0101 = value;
    }

    /**
     * Gets the value of the fdflashid0102 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0102 }
     *     
     */
    public FDFLASHID0102 getFDFLASHID0102() {
        return fdflashid0102;
    }

    /**
     * Sets the value of the fdflashid0102 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0102 }
     *     
     */
    public void setFDFLASHID0102(FDFLASHID0102 value) {
        this.fdflashid0102 = value;
    }

    /**
     * Gets the value of the fdflashid0103 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0103 }
     *     
     */
    public FDFLASHID0103 getFDFLASHID0103() {
        return fdflashid0103;
    }

    /**
     * Sets the value of the fdflashid0103 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0103 }
     *     
     */
    public void setFDFLASHID0103(FDFLASHID0103 value) {
        this.fdflashid0103 = value;
    }

    /**
     * Gets the value of the fdflashid0200 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0200 }
     *     
     */
    public FDFLASHID0200 getFDFLASHID0200() {
        return fdflashid0200;
    }

    /**
     * Sets the value of the fdflashid0200 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0200 }
     *     
     */
    public void setFDFLASHID0200(FDFLASHID0200 value) {
        this.fdflashid0200 = value;
    }

    /**
     * Gets the value of the fdflashid0201 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0201 }
     *     
     */
    public FDFLASHID0201 getFDFLASHID0201() {
        return fdflashid0201;
    }

    /**
     * Sets the value of the fdflashid0201 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0201 }
     *     
     */
    public void setFDFLASHID0201(FDFLASHID0201 value) {
        this.fdflashid0201 = value;
    }

    /**
     * Gets the value of the fdflashid0202 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0202 }
     *     
     */
    public FDFLASHID0202 getFDFLASHID0202() {
        return fdflashid0202;
    }

    /**
     * Sets the value of the fdflashid0202 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0202 }
     *     
     */
    public void setFDFLASHID0202(FDFLASHID0202 value) {
        this.fdflashid0202 = value;
    }

    /**
     * Gets the value of the fdflashid0203 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0203 }
     *     
     */
    public FDFLASHID0203 getFDFLASHID0203() {
        return fdflashid0203;
    }

    /**
     * Sets the value of the fdflashid0203 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0203 }
     *     
     */
    public void setFDFLASHID0203(FDFLASHID0203 value) {
        this.fdflashid0203 = value;
    }

    /**
     * Gets the value of the fdflashid0300 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0300 }
     *     
     */
    public FDFLASHID0300 getFDFLASHID0300() {
        return fdflashid0300;
    }

    /**
     * Sets the value of the fdflashid0300 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0300 }
     *     
     */
    public void setFDFLASHID0300(FDFLASHID0300 value) {
        this.fdflashid0300 = value;
    }

    /**
     * Gets the value of the fdflashid0301 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0301 }
     *     
     */
    public FDFLASHID0301 getFDFLASHID0301() {
        return fdflashid0301;
    }

    /**
     * Sets the value of the fdflashid0301 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0301 }
     *     
     */
    public void setFDFLASHID0301(FDFLASHID0301 value) {
        this.fdflashid0301 = value;
    }

    /**
     * Gets the value of the fdflashid0302 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0302 }
     *     
     */
    public FDFLASHID0302 getFDFLASHID0302() {
        return fdflashid0302;
    }

    /**
     * Sets the value of the fdflashid0302 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0302 }
     *     
     */
    public void setFDFLASHID0302(FDFLASHID0302 value) {
        this.fdflashid0302 = value;
    }

    /**
     * Gets the value of the fdflashid0303 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0303 }
     *     
     */
    public FDFLASHID0303 getFDFLASHID0303() {
        return fdflashid0303;
    }

    /**
     * Sets the value of the fdflashid0303 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0303 }
     *     
     */
    public void setFDFLASHID0303(FDFLASHID0303 value) {
        this.fdflashid0303 = value;
    }

    /**
     * Gets the value of the fdflashid0400 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0400 }
     *     
     */
    public FDFLASHID0400 getFDFLASHID0400() {
        return fdflashid0400;
    }

    /**
     * Sets the value of the fdflashid0400 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0400 }
     *     
     */
    public void setFDFLASHID0400(FDFLASHID0400 value) {
        this.fdflashid0400 = value;
    }

    /**
     * Gets the value of the fdflashid0401 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0401 }
     *     
     */
    public FDFLASHID0401 getFDFLASHID0401() {
        return fdflashid0401;
    }

    /**
     * Sets the value of the fdflashid0401 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0401 }
     *     
     */
    public void setFDFLASHID0401(FDFLASHID0401 value) {
        this.fdflashid0401 = value;
    }

    /**
     * Gets the value of the fdflashid0402 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0402 }
     *     
     */
    public FDFLASHID0402 getFDFLASHID0402() {
        return fdflashid0402;
    }

    /**
     * Sets the value of the fdflashid0402 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0402 }
     *     
     */
    public void setFDFLASHID0402(FDFLASHID0402 value) {
        this.fdflashid0402 = value;
    }

    /**
     * Gets the value of the fdflashid0403 property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID0403 }
     *     
     */
    public FDFLASHID0403 getFDFLASHID0403() {
        return fdflashid0403;
    }

    /**
     * Sets the value of the fdflashid0403 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID0403 }
     *     
     */
    public void setFDFLASHID0403(FDFLASHID0403 value) {
        this.fdflashid0403 = value;
    }

    /**
     * Gets the value of the fdflashid property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLASHID }
     *     
     */
    public FDFLASHID getFDFLASHID() {
        return fdflashid;
    }

    /**
     * Sets the value of the fdflashid property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLASHID }
     *     
     */
    public void setFDFLASHID(FDFLASHID value) {
        this.fdflashid = value;
    }

    /**
     * Gets the value of the fdsmartcpb property.
     * 
     * @return
     *     possible object is
     *     {@link FDSMARTCPB }
     *     
     */
    public FDSMARTCPB getFDSMARTCPB() {
        return fdsmartcpb;
    }

    /**
     * Sets the value of the fdsmartcpb property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDSMARTCPB }
     *     
     */
    public void setFDSMARTCPB(FDSMARTCPB value) {
        this.fdsmartcpb = value;
    }

    /**
     * Gets the value of the fdvscap property.
     * 
     * @return
     *     possible object is
     *     {@link FDVSCAP }
     *     
     */
    public FDVSCAP getFDVSCAP() {
        return fdvscap;
    }

    /**
     * Sets the value of the fdvscap property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDVSCAP }
     *     
     */
    public void setFDVSCAP(FDVSCAP value) {
        this.fdvscap = value;
    }

    /**
     * Gets the value of the fddigemercall property.
     * 
     * @return
     *     possible object is
     *     {@link FDDIGEMERCALL }
     *     
     */
    public FDDIGEMERCALL getFDDIGEMERCALL() {
        return fddigemercall;
    }

    /**
     * Sets the value of the fddigemercall property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDDIGEMERCALL }
     *     
     */
    public void setFDDIGEMERCALL(FDDIGEMERCALL value) {
        this.fddigemercall = value;
    }

    /**
     * Gets the value of the fdtelintc property.
     * 
     * @return
     *     possible object is
     *     {@link FDTELINTC }
     *     
     */
    public FDTELINTC getFDTELINTC() {
        return fdtelintc;
    }

    /**
     * Sets the value of the fdtelintc property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDTELINTC }
     *     
     */
    public void setFDTELINTC(FDTELINTC value) {
        this.fdtelintc = value;
    }

    /**
     * Gets the value of the fdqciienc property.
     * 
     * @return
     *     possible object is
     *     {@link FDQCIIENC }
     *     
     */
    public FDQCIIENC getFDQCIIENC() {
        return fdqciienc;
    }

    /**
     * Sets the value of the fdqciienc property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDQCIIENC }
     *     
     */
    public void setFDQCIIENC(FDQCIIENC value) {
        this.fdqciienc = value;
    }

    /**
     * Gets the value of the fdcalltntag property.
     * 
     * @return
     *     possible object is
     *     {@link FDCALLTNTAG }
     *     
     */
    public FDCALLTNTAG getFDCALLTNTAG() {
        return fdcalltntag;
    }

    /**
     * Sets the value of the fdcalltntag property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDCALLTNTAG }
     *     
     */
    public void setFDCALLTNTAG(FDCALLTNTAG value) {
        this.fdcalltntag = value;
    }

    /**
     * Gets the value of the fd5TEMER property.
     * 
     * @return
     *     possible object is
     *     {@link FD5TEMER }
     *     
     */
    public FD5TEMER getFD5TEMER() {
        return fd5TEMER;
    }

    /**
     * Sets the value of the fd5TEMER property.
     * 
     * @param value
     *     allowed object is
     *     {@link FD5TEMER }
     *     
     */
    public void setFD5TEMER(FD5TEMER value) {
        this.fd5TEMER = value;
    }

    /**
     * Gets the value of the fddigrmioptype property.
     * 
     * @return
     *     possible object is
     *     {@link FDDIGRMIOPTYPE }
     *     
     */
    public FDDIGRMIOPTYPE getFDDIGRMIOPTYPE() {
        return fddigrmioptype;
    }

    /**
     * Sets the value of the fddigrmioptype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDDIGRMIOPTYPE }
     *     
     */
    public void setFDDIGRMIOPTYPE(FDDIGRMIOPTYPE value) {
        this.fddigrmioptype = value;
    }

    /**
     * Gets the value of the fddigtrdihbtopt property.
     * 
     * @return
     *     possible object is
     *     {@link FDDIGTRDIHBTOPT }
     *     
     */
    public FDDIGTRDIHBTOPT getFDDIGTRDIHBTOPT() {
        return fddigtrdihbtopt;
    }

    /**
     * Sets the value of the fddigtrdihbtopt property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDDIGTRDIHBTOPT }
     *     
     */
    public void setFDDIGTRDIHBTOPT(FDDIGTRDIHBTOPT value) {
        this.fddigtrdihbtopt = value;
    }

    /**
     * Gets the value of the fddigtelintc property.
     * 
     * @return
     *     possible object is
     *     {@link FDDIGTELINTC }
     *     
     */
    public FDDIGTELINTC getFDDIGTELINTC() {
        return fddigtelintc;
    }

    /**
     * Sets the value of the fddigtelintc property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDDIGTELINTC }
     *     
     */
    public void setFDDIGTELINTC(FDDIGTELINTC value) {
        this.fddigtelintc = value;
    }

    /**
     * Gets the value of the fdimekptype property.
     * 
     * @return
     *     possible object is
     *     {@link FDIMEKPTYPE }
     *     
     */
    public FDIMEKPTYPE getFDIMEKPTYPE() {
        return fdimekptype;
    }

    /**
     * Sets the value of the fdimekptype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDIMEKPTYPE }
     *     
     */
    public void setFDIMEKPTYPE(FDIMEKPTYPE value) {
        this.fdimekptype = value;
    }

    /**
     * Gets the value of the fddevtype property.
     * 
     * @return
     *     possible object is
     *     {@link FDDEVTYPE }
     *     
     */
    public FDDEVTYPE getFDDEVTYPE() {
        return fddevtype;
    }

    /**
     * Sets the value of the fddevtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDDEVTYPE }
     *     
     */
    public void setFDDEVTYPE(FDDEVTYPE value) {
        this.fddevtype = value;
    }

    /**
     * Gets the value of the fdkeypadautolock property.
     * 
     * @return
     *     possible object is
     *     {@link FDKEYPADAUTOLOCK }
     *     
     */
    public FDKEYPADAUTOLOCK getFDKEYPADAUTOLOCK() {
        return fdkeypadautolock;
    }

    /**
     * Sets the value of the fdkeypadautolock property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDKEYPADAUTOLOCK }
     *     
     */
    public void setFDKEYPADAUTOLOCK(FDKEYPADAUTOLOCK value) {
        this.fdkeypadautolock = value;
    }

    /**
     * Gets the value of the fdbatteryinformationmenu property.
     * 
     * @return
     *     possible object is
     *     {@link FDBATTERYINFORMATIONMENU }
     *     
     */
    public FDBATTERYINFORMATIONMENU getFDBATTERYINFORMATIONMENU() {
        return fdbatteryinformationmenu;
    }

    /**
     * Sets the value of the fdbatteryinformationmenu property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDBATTERYINFORMATIONMENU }
     *     
     */
    public void setFDBATTERYINFORMATIONMENU(FDBATTERYINFORMATIONMENU value) {
        this.fdbatteryinformationmenu = value;
    }

    /**
     * Gets the value of the fdanalogsquelch property.
     * 
     * @return
     *     possible object is
     *     {@link FDANALOGSQUELCH }
     *     
     */
    public FDANALOGSQUELCH getFDANALOGSQUELCH() {
        return fdanalogsquelch;
    }

    /**
     * Sets the value of the fdanalogsquelch property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDANALOGSQUELCH }
     *     
     */
    public void setFDANALOGSQUELCH(FDANALOGSQUELCH value) {
        this.fdanalogsquelch = value;
    }

    /**
     * Gets the value of the fdpowerlevel property.
     * 
     * @return
     *     possible object is
     *     {@link FDPOWERLEVEL }
     *     
     */
    public FDPOWERLEVEL getFDPOWERLEVEL() {
        return fdpowerlevel;
    }

    /**
     * Sets the value of the fdpowerlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDPOWERLEVEL }
     *     
     */
    public void setFDPOWERLEVEL(FDPOWERLEVEL value) {
        this.fdpowerlevel = value;
    }

    /**
     * Gets the value of the fdbacklighttimer property.
     * 
     * @return
     *     possible object is
     *     {@link FDBACKLIGHTTIMER }
     *     
     */
    public FDBACKLIGHTTIMER getFDBACKLIGHTTIMER() {
        return fdbacklighttimer;
    }

    /**
     * Sets the value of the fdbacklighttimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDBACKLIGHTTIMER }
     *     
     */
    public void setFDBACKLIGHTTIMER(FDBACKLIGHTTIMER value) {
        this.fdbacklighttimer = value;
    }

    /**
     * Gets the value of the fdaudioaccessory property.
     * 
     * @return
     *     possible object is
     *     {@link FDAUDIOACCESSORY }
     *     
     */
    public FDAUDIOACCESSORY getFDAUDIOACCESSORY() {
        return fdaudioaccessory;
    }

    /**
     * Sets the value of the fdaudioaccessory property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDAUDIOACCESSORY }
     *     
     */
    public void setFDAUDIOACCESSORY(FDAUDIOACCESSORY value) {
        this.fdaudioaccessory = value;
    }

    /**
     * Gets the value of the fdsafetyinformation property.
     * 
     * @return
     *     possible object is
     *     {@link FDSAFETYINFORMATION }
     *     
     */
    public FDSAFETYINFORMATION getFDSAFETYINFORMATION() {
        return fdsafetyinformation;
    }

    /**
     * Sets the value of the fdsafetyinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDSAFETYINFORMATION }
     *     
     */
    public void setFDSAFETYINFORMATION(FDSAFETYINFORMATION value) {
        this.fdsafetyinformation = value;
    }

    /**
     * Gets the value of the fdscreensaver property.
     * 
     * @return
     *     possible object is
     *     {@link FDSCREENSAVER }
     *     
     */
    public FDSCREENSAVER getFDSCREENSAVER() {
        return fdscreensaver;
    }

    /**
     * Sets the value of the fdscreensaver property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDSCREENSAVER }
     *     
     */
    public void setFDSCREENSAVER(FDSCREENSAVER value) {
        this.fdscreensaver = value;
    }

    /**
     * Gets the value of the fdjobticket property.
     * 
     * @return
     *     possible object is
     *     {@link FDJOBTICKET }
     *     
     */
    public FDJOBTICKET getFDJOBTICKET() {
        return fdjobticket;
    }

    /**
     * Sets the value of the fdjobticket property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDJOBTICKET }
     *     
     */
    public void setFDJOBTICKET(FDJOBTICKET value) {
        this.fdjobticket = value;
    }

    /**
     * Gets the value of the fdwallpaper property.
     * 
     * @return
     *     possible object is
     *     {@link FDWALLPAPER }
     *     
     */
    public FDWALLPAPER getFDWALLPAPER() {
        return fdwallpaper;
    }

    /**
     * Sets the value of the fdwallpaper property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDWALLPAPER }
     *     
     */
    public void setFDWALLPAPER(FDWALLPAPER value) {
        this.fdwallpaper = value;
    }

    /**
     * Gets the value of the fdvibrate property.
     * 
     * @return
     *     possible object is
     *     {@link FDVIBRATE }
     *     
     */
    public FDVIBRATE getFDVIBRATE() {
        return fdvibrate;
    }

    /**
     * Sets the value of the fdvibrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDVIBRATE }
     *     
     */
    public void setFDVIBRATE(FDVIBRATE value) {
        this.fdvibrate = value;
    }

    /**
     * Gets the value of the fdcovertmode property.
     * 
     * @return
     *     possible object is
     *     {@link FDCOVERTMODE }
     *     
     */
    public FDCOVERTMODE getFDCOVERTMODE() {
        return fdcovertmode;
    }

    /**
     * Sets the value of the fdcovertmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDCOVERTMODE }
     *     
     */
    public void setFDCOVERTMODE(FDCOVERTMODE value) {
        this.fdcovertmode = value;
    }

    /**
     * Gets the value of the fdactionlist property.
     * 
     * @return
     *     possible object is
     *     {@link FDACTIONLIST }
     *     
     */
    public FDACTIONLIST getFDACTIONLIST() {
        return fdactionlist;
    }

    /**
     * Sets the value of the fdactionlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDACTIONLIST }
     *     
     */
    public void setFDACTIONLIST(FDACTIONLIST value) {
        this.fdactionlist = value;
    }

    /**
     * Gets the value of the fdbacklightautoon property.
     * 
     * @return
     *     possible object is
     *     {@link FDBACKLIGHTAUTOON }
     *     
     */
    public FDBACKLIGHTAUTOON getFDBACKLIGHTAUTOON() {
        return fdbacklightautoon;
    }

    /**
     * Sets the value of the fdbacklightautoon property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDBACKLIGHTAUTOON }
     *     
     */
    public void setFDBACKLIGHTAUTOON(FDBACKLIGHTAUTOON value) {
        this.fdbacklightautoon = value;
    }

    /**
     * Gets the value of the fddualknobenable property.
     * 
     * @return
     *     possible object is
     *     {@link FDDUALKNOBENABLE }
     *     
     */
    public FDDUALKNOBENABLE getFDDUALKNOBENABLE() {
        return fddualknobenable;
    }

    /**
     * Sets the value of the fddualknobenable property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDDUALKNOBENABLE }
     *     
     */
    public void setFDDUALKNOBENABLE(FDDUALKNOBENABLE value) {
        this.fddualknobenable = value;
    }

    /**
     * Gets the value of the fdpublicaddressenable property.
     * 
     * @return
     *     possible object is
     *     {@link FDPUBLICADDRESSENABLE }
     *     
     */
    public FDPUBLICADDRESSENABLE getFDPUBLICADDRESSENABLE() {
        return fdpublicaddressenable;
    }

    /**
     * Sets the value of the fdpublicaddressenable property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDPUBLICADDRESSENABLE }
     *     
     */
    public void setFDPUBLICADDRESSENABLE(FDPUBLICADDRESSENABLE value) {
        this.fdpublicaddressenable = value;
    }

    /**
     * Gets the value of the fdtelemetryenable property.
     * 
     * @return
     *     possible object is
     *     {@link FDTELEMETRYENABLE }
     *     
     */
    public FDTELEMETRYENABLE getFDTELEMETRYENABLE() {
        return fdtelemetryenable;
    }

    /**
     * Sets the value of the fdtelemetryenable property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDTELEMETRYENABLE }
     *     
     */
    public void setFDTELEMETRYENABLE(FDTELEMETRYENABLE value) {
        this.fdtelemetryenable = value;
    }

    /**
     * Gets the value of the fdanalogscramblingenable property.
     * 
     * @return
     *     possible object is
     *     {@link FDANALOGSCRAMBLINGENABLE }
     *     
     */
    public FDANALOGSCRAMBLINGENABLE getFDANALOGSCRAMBLINGENABLE() {
        return fdanalogscramblingenable;
    }

    /**
     * Sets the value of the fdanalogscramblingenable property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDANALOGSCRAMBLINGENABLE }
     *     
     */
    public void setFDANALOGSCRAMBLINGENABLE(FDANALOGSCRAMBLINGENABLE value) {
        this.fdanalogscramblingenable = value;
    }

    /**
     * Gets the value of the fddigitalintelligenceaudioenable property.
     * 
     * @return
     *     possible object is
     *     {@link FDDIGITALINTELLIGENCEAUDIOENABLE }
     *     
     */
    public FDDIGITALINTELLIGENCEAUDIOENABLE getFDDIGITALINTELLIGENCEAUDIOENABLE() {
        return fddigitalintelligenceaudioenable;
    }

    /**
     * Sets the value of the fddigitalintelligenceaudioenable property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDDIGITALINTELLIGENCEAUDIOENABLE }
     *     
     */
    public void setFDDIGITALINTELLIGENCEAUDIOENABLE(FDDIGITALINTELLIGENCEAUDIOENABLE value) {
        this.fddigitalintelligenceaudioenable = value;
    }

    /**
     * Gets the value of the fduserselectiveaudioprofile property.
     * 
     * @return
     *     possible object is
     *     {@link FDUSERSELECTIVEAUDIOPROFILE }
     *     
     */
    public FDUSERSELECTIVEAUDIOPROFILE getFDUSERSELECTIVEAUDIOPROFILE() {
        return fduserselectiveaudioprofile;
    }

    /**
     * Sets the value of the fduserselectiveaudioprofile property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDUSERSELECTIVEAUDIOPROFILE }
     *     
     */
    public void setFDUSERSELECTIVEAUDIOPROFILE(FDUSERSELECTIVEAUDIOPROFILE value) {
        this.fduserselectiveaudioprofile = value;
    }

    /**
     * Gets the value of the fdreserved1988 property.
     * 
     * @return
     *     possible object is
     *     {@link FDRESERVED1988 }
     *     
     */
    public FDRESERVED1988 getFDRESERVED1988() {
        return fdreserved1988;
    }

    /**
     * Sets the value of the fdreserved1988 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDRESERVED1988 }
     *     
     */
    public void setFDRESERVED1988(FDRESERVED1988 value) {
        this.fdreserved1988 = value;
    }

    /**
     * Gets the value of the fdmenualphasearchenable property.
     * 
     * @return
     *     possible object is
     *     {@link FDMENUALPHASEARCHENABLE }
     *     
     */
    public FDMENUALPHASEARCHENABLE getFDMENUALPHASEARCHENABLE() {
        return fdmenualphasearchenable;
    }

    /**
     * Sets the value of the fdmenualphasearchenable property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDMENUALPHASEARCHENABLE }
     *     
     */
    public void setFDMENUALPHASEARCHENABLE(FDMENUALPHASEARCHENABLE value) {
        this.fdmenualphasearchenable = value;
    }

    /**
     * Gets the value of the fdf2ALLCALLENCODEENABLE property.
     * 
     * @return
     *     possible object is
     *     {@link FDF2ALLCALLENCODEENABLE }
     *     
     */
    public FDF2ALLCALLENCODEENABLE getFDF2ALLCALLENCODEENABLE() {
        return fdf2ALLCALLENCODEENABLE;
    }

    /**
     * Sets the value of the fdf2ALLCALLENCODEENABLE property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDF2ALLCALLENCODEENABLE }
     *     
     */
    public void setFDF2ALLCALLENCODEENABLE(FDF2ALLCALLENCODEENABLE value) {
        this.fdf2ALLCALLENCODEENABLE = value;
    }

    /**
     * Gets the value of the fdphotosensorenable property.
     * 
     * @return
     *     possible object is
     *     {@link FDPHOTOSENSORENABLE }
     *     
     */
    public FDPHOTOSENSORENABLE getFDPHOTOSENSORENABLE() {
        return fdphotosensorenable;
    }

    /**
     * Sets the value of the fdphotosensorenable property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDPHOTOSENSORENABLE }
     *     
     */
    public void setFDPHOTOSENSORENABLE(FDPHOTOSENSORENABLE value) {
        this.fdphotosensorenable = value;
    }

    /**
     * Gets the value of the fdf2RADIOCHECKENCODEENABLE property.
     * 
     * @return
     *     possible object is
     *     {@link FDF2RADIOCHECKENCODEENABLE }
     *     
     */
    public FDF2RADIOCHECKENCODEENABLE getFDF2RADIOCHECKENCODEENABLE() {
        return fdf2RADIOCHECKENCODEENABLE;
    }

    /**
     * Sets the value of the fdf2RADIOCHECKENCODEENABLE property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDF2RADIOCHECKENCODEENABLE }
     *     
     */
    public void setFDF2RADIOCHECKENCODEENABLE(FDF2RADIOCHECKENCODEENABLE value) {
        this.fdf2RADIOCHECKENCODEENABLE = value;
    }

    /**
     * Gets the value of the fdusbhiddataroutingenable property.
     * 
     * @return
     *     possible object is
     *     {@link FDUSBHIDDATAROUTINGENABLE }
     *     
     */
    public FDUSBHIDDATAROUTINGENABLE getFDUSBHIDDATAROUTINGENABLE() {
        return fdusbhiddataroutingenable;
    }

    /**
     * Sets the value of the fdusbhiddataroutingenable property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDUSBHIDDATAROUTINGENABLE }
     *     
     */
    public void setFDUSBHIDDATAROUTINGENABLE(FDUSBHIDDATAROUTINGENABLE value) {
        this.fdusbhiddataroutingenable = value;
    }

    /**
     * Gets the value of the fdflexiblerxlist property.
     * 
     * @return
     *     possible object is
     *     {@link FDFLEXIBLERXLIST }
     *     
     */
    public FDFLEXIBLERXLIST getFDFLEXIBLERXLIST() {
        return fdflexiblerxlist;
    }

    /**
     * Sets the value of the fdflexiblerxlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDFLEXIBLERXLIST }
     *     
     */
    public void setFDFLEXIBLERXLIST(FDFLEXIBLERXLIST value) {
        this.fdflexiblerxlist = value;
    }

    /**
     * Gets the value of the fdmicrophonedynamicdistortioncontrol property.
     * 
     * @return
     *     possible object is
     *     {@link FDMICROPHONEDYNAMICDISTORTIONCONTROL }
     *     
     */
    public FDMICROPHONEDYNAMICDISTORTIONCONTROL getFDMICROPHONEDYNAMICDISTORTIONCONTROL() {
        return fdmicrophonedynamicdistortioncontrol;
    }

    /**
     * Sets the value of the fdmicrophonedynamicdistortioncontrol property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDMICROPHONEDYNAMICDISTORTIONCONTROL }
     *     
     */
    public void setFDMICROPHONEDYNAMICDISTORTIONCONTROL(FDMICROPHONEDYNAMICDISTORTIONCONTROL value) {
        this.fdmicrophonedynamicdistortioncontrol = value;
    }

    /**
     * Gets the value of the fdhowlingsuppressor property.
     * 
     * @return
     *     possible object is
     *     {@link FDHOWLINGSUPPRESSOR }
     *     
     */
    public FDHOWLINGSUPPRESSOR getFDHOWLINGSUPPRESSOR() {
        return fdhowlingsuppressor;
    }

    /**
     * Sets the value of the fdhowlingsuppressor property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDHOWLINGSUPPRESSOR }
     *     
     */
    public void setFDHOWLINGSUPPRESSOR(FDHOWLINGSUPPRESSOR value) {
        this.fdhowlingsuppressor = value;
    }

    /**
     * Gets the value of the fdcounterfeitbatteryindication property.
     * 
     * @return
     *     possible object is
     *     {@link FDCOUNTERFEITBATTERYINDICATION }
     *     
     */
    public FDCOUNTERFEITBATTERYINDICATION getFDCOUNTERFEITBATTERYINDICATION() {
        return fdcounterfeitbatteryindication;
    }

    /**
     * Sets the value of the fdcounterfeitbatteryindication property.
     * 
     * @param value
     *     allowed object is
     *     {@link FDCOUNTERFEITBATTERYINDICATION }
     *     
     */
    public void setFDCOUNTERFEITBATTERYINDICATION(FDCOUNTERFEITBATTERYINDICATION value) {
        this.fdcounterfeitbatteryindication = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

}
