//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.05 at 02:22:03 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}FLEXIBLE_CAPPLUS_RX_TG_DLL_TYPE_NTLLISHTYPE"/&gt;
 *         &lt;element ref="{}FLEXIBLE_CAPPLUS_RX_TG_DLL_TYPE_NTLLISHID"/&gt;
 *         &lt;element ref="{}FLEXIBLECAPPLUSRXTGDLL_LLEQ"/&gt;
 *         &lt;element ref="{}FLEXIBLECAPPLUSRXTGDLL_LEDITEM"/&gt;
 *         &lt;element ref="{}FLEXIBLECAPPLUSRXTGDLL_LEDITEMTYPE"/&gt;
 *         &lt;element ref="{}FLEXIBLECAPPLUSRXTGDLL_LEDITEMID"/&gt;
 *         &lt;element ref="{}FLEXIBLECAPPLUSRXTGDLL_RESERVED"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="ListLetID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flexiblecapplusrxtgdlltypentllishtype",
    "flexiblecapplusrxtgdlltypentllishid",
    "flexiblecapplusrxtgdlllleq",
    "flexiblecapplusrxtgdllleditem",
    "flexiblecapplusrxtgdllleditemtype",
    "flexiblecapplusrxtgdllleditemid",
    "flexiblecapplusrxtgdllreserved"
})
@XmlRootElement(name = "FLEXIBLE_CAPPLUS_RX_TG_DLL_TYPE")
public class FLEXIBLECAPPLUSRXTGDLLTYPE {

    @XmlElement(name = "FLEXIBLE_CAPPLUS_RX_TG_DLL_TYPE_NTLLISHTYPE", required = true)
    protected FLEXIBLECAPPLUSRXTGDLLTYPENTLLISHTYPE flexiblecapplusrxtgdlltypentllishtype;
    @XmlElement(name = "FLEXIBLE_CAPPLUS_RX_TG_DLL_TYPE_NTLLISHID", required = true)
    protected FLEXIBLECAPPLUSRXTGDLLTYPENTLLISHID flexiblecapplusrxtgdlltypentllishid;
    @XmlElement(name = "FLEXIBLECAPPLUSRXTGDLL_LLEQ", required = true)
    protected FLEXIBLECAPPLUSRXTGDLLLLEQ flexiblecapplusrxtgdlllleq;
    @XmlElement(name = "FLEXIBLECAPPLUSRXTGDLL_LEDITEM", required = true)
    protected FLEXIBLECAPPLUSRXTGDLLLEDITEM flexiblecapplusrxtgdllleditem;
    @XmlElement(name = "FLEXIBLECAPPLUSRXTGDLL_LEDITEMTYPE", required = true)
    protected FLEXIBLECAPPLUSRXTGDLLLEDITEMTYPE flexiblecapplusrxtgdllleditemtype;
    @XmlElement(name = "FLEXIBLECAPPLUSRXTGDLL_LEDITEMID", required = true)
    protected FLEXIBLECAPPLUSRXTGDLLLEDITEMID flexiblecapplusrxtgdllleditemid;
    @XmlElement(name = "FLEXIBLECAPPLUSRXTGDLL_RESERVED", required = true)
    protected FLEXIBLECAPPLUSRXTGDLLRESERVED flexiblecapplusrxtgdllreserved;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;
    @XmlAttribute(name = "ListLetID", required = true)
    protected BigInteger listLetID;

    /**
     * Gets the value of the flexiblecapplusrxtgdlltypentllishtype property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLTYPENTLLISHTYPE }
     *     
     */
    public FLEXIBLECAPPLUSRXTGDLLTYPENTLLISHTYPE getFLEXIBLECAPPLUSRXTGDLLTYPENTLLISHTYPE() {
        return flexiblecapplusrxtgdlltypentllishtype;
    }

    /**
     * Sets the value of the flexiblecapplusrxtgdlltypentllishtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLTYPENTLLISHTYPE }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGDLLTYPENTLLISHTYPE(FLEXIBLECAPPLUSRXTGDLLTYPENTLLISHTYPE value) {
        this.flexiblecapplusrxtgdlltypentllishtype = value;
    }

    /**
     * Gets the value of the flexiblecapplusrxtgdlltypentllishid property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLTYPENTLLISHID }
     *     
     */
    public FLEXIBLECAPPLUSRXTGDLLTYPENTLLISHID getFLEXIBLECAPPLUSRXTGDLLTYPENTLLISHID() {
        return flexiblecapplusrxtgdlltypentllishid;
    }

    /**
     * Sets the value of the flexiblecapplusrxtgdlltypentllishid property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLTYPENTLLISHID }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGDLLTYPENTLLISHID(FLEXIBLECAPPLUSRXTGDLLTYPENTLLISHID value) {
        this.flexiblecapplusrxtgdlltypentllishid = value;
    }

    /**
     * Gets the value of the flexiblecapplusrxtgdlllleq property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLLLEQ }
     *     
     */
    public FLEXIBLECAPPLUSRXTGDLLLLEQ getFLEXIBLECAPPLUSRXTGDLLLLEQ() {
        return flexiblecapplusrxtgdlllleq;
    }

    /**
     * Sets the value of the flexiblecapplusrxtgdlllleq property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLLLEQ }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGDLLLLEQ(FLEXIBLECAPPLUSRXTGDLLLLEQ value) {
        this.flexiblecapplusrxtgdlllleq = value;
    }

    /**
     * Gets the value of the flexiblecapplusrxtgdllleditem property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLLEDITEM }
     *     
     */
    public FLEXIBLECAPPLUSRXTGDLLLEDITEM getFLEXIBLECAPPLUSRXTGDLLLEDITEM() {
        return flexiblecapplusrxtgdllleditem;
    }

    /**
     * Sets the value of the flexiblecapplusrxtgdllleditem property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLLEDITEM }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGDLLLEDITEM(FLEXIBLECAPPLUSRXTGDLLLEDITEM value) {
        this.flexiblecapplusrxtgdllleditem = value;
    }

    /**
     * Gets the value of the flexiblecapplusrxtgdllleditemtype property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLLEDITEMTYPE }
     *     
     */
    public FLEXIBLECAPPLUSRXTGDLLLEDITEMTYPE getFLEXIBLECAPPLUSRXTGDLLLEDITEMTYPE() {
        return flexiblecapplusrxtgdllleditemtype;
    }

    /**
     * Sets the value of the flexiblecapplusrxtgdllleditemtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLLEDITEMTYPE }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGDLLLEDITEMTYPE(FLEXIBLECAPPLUSRXTGDLLLEDITEMTYPE value) {
        this.flexiblecapplusrxtgdllleditemtype = value;
    }

    /**
     * Gets the value of the flexiblecapplusrxtgdllleditemid property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLLEDITEMID }
     *     
     */
    public FLEXIBLECAPPLUSRXTGDLLLEDITEMID getFLEXIBLECAPPLUSRXTGDLLLEDITEMID() {
        return flexiblecapplusrxtgdllleditemid;
    }

    /**
     * Sets the value of the flexiblecapplusrxtgdllleditemid property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLLEDITEMID }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGDLLLEDITEMID(FLEXIBLECAPPLUSRXTGDLLLEDITEMID value) {
        this.flexiblecapplusrxtgdllleditemid = value;
    }

    /**
     * Gets the value of the flexiblecapplusrxtgdllreserved property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLRESERVED }
     *     
     */
    public FLEXIBLECAPPLUSRXTGDLLRESERVED getFLEXIBLECAPPLUSRXTGDLLRESERVED() {
        return flexiblecapplusrxtgdllreserved;
    }

    /**
     * Sets the value of the flexiblecapplusrxtgdllreserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGDLLRESERVED }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGDLLRESERVED(FLEXIBLECAPPLUSRXTGDLLRESERVED value) {
        this.flexiblecapplusrxtgdllreserved = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

    /**
     * Gets the value of the listLetID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListLetID() {
        return listLetID;
    }

    /**
     * Sets the value of the listLetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListLetID(BigInteger value) {
        this.listLetID = value;
    }

}
