//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.05 at 02:22:03 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}FLEXIBLECAPPLUSRXTG_LISTCATEGORY"/&gt;
 *         &lt;element ref="{}FLEXIBLECAPPLUSRXTG_LEDSIZE"/&gt;
 *         &lt;element ref="{}FLEXIBLECAPPLUSRXTG_LEQMAX"/&gt;
 *         &lt;element ref="{}FLEXIBLECAPPLUSRXTG_LLEQMAX"/&gt;
 *         &lt;element ref="{}FLEXIBLE_CAPPLUS_RX_TG_DLH_TYPE_FTLLISHTYPE"/&gt;
 *         &lt;element ref="{}FLEXIBLE_CAPPLUS_RX_TG_DLH_TYPE_FTLLISHID"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flexiblecapplusrxtglistcategory",
    "flexiblecapplusrxtgledsize",
    "flexiblecapplusrxtgleqmax",
    "flexiblecapplusrxtglleqmax",
    "flexiblecapplusrxtgdlhtypeftllishtype",
    "flexiblecapplusrxtgdlhtypeftllishid"
})
@XmlRootElement(name = "FLEXIBLE_CAPPLUS_RX_TG_DLH_TYPE")
public class FLEXIBLECAPPLUSRXTGDLHTYPE {

    @XmlElement(name = "FLEXIBLECAPPLUSRXTG_LISTCATEGORY", required = true)
    protected FLEXIBLECAPPLUSRXTGLISTCATEGORY flexiblecapplusrxtglistcategory;
    @XmlElement(name = "FLEXIBLECAPPLUSRXTG_LEDSIZE", required = true)
    protected FLEXIBLECAPPLUSRXTGLEDSIZE flexiblecapplusrxtgledsize;
    @XmlElement(name = "FLEXIBLECAPPLUSRXTG_LEQMAX", required = true)
    protected FLEXIBLECAPPLUSRXTGLEQMAX flexiblecapplusrxtgleqmax;
    @XmlElement(name = "FLEXIBLECAPPLUSRXTG_LLEQMAX", required = true)
    protected FLEXIBLECAPPLUSRXTGLLEQMAX flexiblecapplusrxtglleqmax;
    @XmlElement(name = "FLEXIBLE_CAPPLUS_RX_TG_DLH_TYPE_FTLLISHTYPE", required = true)
    protected FLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHTYPE flexiblecapplusrxtgdlhtypeftllishtype;
    @XmlElement(name = "FLEXIBLE_CAPPLUS_RX_TG_DLH_TYPE_FTLLISHID", required = true)
    protected FLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHID flexiblecapplusrxtgdlhtypeftllishid;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;

    /**
     * Gets the value of the flexiblecapplusrxtglistcategory property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGLISTCATEGORY }
     *     
     */
    public FLEXIBLECAPPLUSRXTGLISTCATEGORY getFLEXIBLECAPPLUSRXTGLISTCATEGORY() {
        return flexiblecapplusrxtglistcategory;
    }

    /**
     * Sets the value of the flexiblecapplusrxtglistcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGLISTCATEGORY }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGLISTCATEGORY(FLEXIBLECAPPLUSRXTGLISTCATEGORY value) {
        this.flexiblecapplusrxtglistcategory = value;
    }

    /**
     * Gets the value of the flexiblecapplusrxtgledsize property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGLEDSIZE }
     *     
     */
    public FLEXIBLECAPPLUSRXTGLEDSIZE getFLEXIBLECAPPLUSRXTGLEDSIZE() {
        return flexiblecapplusrxtgledsize;
    }

    /**
     * Sets the value of the flexiblecapplusrxtgledsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGLEDSIZE }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGLEDSIZE(FLEXIBLECAPPLUSRXTGLEDSIZE value) {
        this.flexiblecapplusrxtgledsize = value;
    }

    /**
     * Gets the value of the flexiblecapplusrxtgleqmax property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGLEQMAX }
     *     
     */
    public FLEXIBLECAPPLUSRXTGLEQMAX getFLEXIBLECAPPLUSRXTGLEQMAX() {
        return flexiblecapplusrxtgleqmax;
    }

    /**
     * Sets the value of the flexiblecapplusrxtgleqmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGLEQMAX }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGLEQMAX(FLEXIBLECAPPLUSRXTGLEQMAX value) {
        this.flexiblecapplusrxtgleqmax = value;
    }

    /**
     * Gets the value of the flexiblecapplusrxtglleqmax property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGLLEQMAX }
     *     
     */
    public FLEXIBLECAPPLUSRXTGLLEQMAX getFLEXIBLECAPPLUSRXTGLLEQMAX() {
        return flexiblecapplusrxtglleqmax;
    }

    /**
     * Sets the value of the flexiblecapplusrxtglleqmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGLLEQMAX }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGLLEQMAX(FLEXIBLECAPPLUSRXTGLLEQMAX value) {
        this.flexiblecapplusrxtglleqmax = value;
    }

    /**
     * Gets the value of the flexiblecapplusrxtgdlhtypeftllishtype property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHTYPE }
     *     
     */
    public FLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHTYPE getFLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHTYPE() {
        return flexiblecapplusrxtgdlhtypeftllishtype;
    }

    /**
     * Sets the value of the flexiblecapplusrxtgdlhtypeftllishtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHTYPE }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHTYPE(FLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHTYPE value) {
        this.flexiblecapplusrxtgdlhtypeftllishtype = value;
    }

    /**
     * Gets the value of the flexiblecapplusrxtgdlhtypeftllishid property.
     * 
     * @return
     *     possible object is
     *     {@link FLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHID }
     *     
     */
    public FLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHID getFLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHID() {
        return flexiblecapplusrxtgdlhtypeftllishid;
    }

    /**
     * Sets the value of the flexiblecapplusrxtgdlhtypeftllishid property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHID }
     *     
     */
    public void setFLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHID(FLEXIBLECAPPLUSRXTGDLHTYPEFTLLISHID value) {
        this.flexiblecapplusrxtgdlhtypeftllishid = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

}
