//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.07 at 05:56:42 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}LCPSTLST_LSTCTG"/&gt;
 *         &lt;element ref="{}LCPSTLST_LEDSZ"/&gt;
 *         &lt;element ref="{}LCPSTLST_LEQMAX"/&gt;
 *         &lt;element ref="{}LCPSTLST_LLEQMAX"/&gt;
 *         &lt;element ref="{}LCP_STLST_DLH_TYPE_FTLLISHTYPE"/&gt;
 *         &lt;element ref="{}LCP_STLST_DLH_TYPE_FTLLISHID"/&gt;
 *         &lt;element ref="{}LCPSTLST_ALIAS"/&gt;
 *         &lt;element ref="{}LCPSTLST_LSTHMST"/&gt;
 *         &lt;element ref="{}LCPSTLST_GDSRRITHSHD"/&gt;
 *         &lt;element ref="{}LCPSTLST_RESERVED"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lcpstlstlstctg",
    "lcpstlstledsz",
    "lcpstlstleqmax",
    "lcpstlstlleqmax",
    "lcpstlstdlhtypeftllishtype",
    "lcpstlstdlhtypeftllishid",
    "lcpstlstalias",
    "lcpstlstlsthmst",
    "lcpstlstgdsrrithshd",
    "lcpstlstreserved"
})
@XmlRootElement(name = "LCP_STLST_DLH_TYPE")
public class LCPSTLSTDLHTYPE {

    @XmlElement(name = "LCPSTLST_LSTCTG", required = true)
    protected LCPSTLSTLSTCTG lcpstlstlstctg;
    @XmlElement(name = "LCPSTLST_LEDSZ", required = true)
    protected LCPSTLSTLEDSZ lcpstlstledsz;
    @XmlElement(name = "LCPSTLST_LEQMAX", required = true)
    protected LCPSTLSTLEQMAX lcpstlstleqmax;
    @XmlElement(name = "LCPSTLST_LLEQMAX", required = true)
    protected LCPSTLSTLLEQMAX lcpstlstlleqmax;
    @XmlElement(name = "LCP_STLST_DLH_TYPE_FTLLISHTYPE", required = true)
    protected LCPSTLSTDLHTYPEFTLLISHTYPE lcpstlstdlhtypeftllishtype;
    @XmlElement(name = "LCP_STLST_DLH_TYPE_FTLLISHID", required = true)
    protected LCPSTLSTDLHTYPEFTLLISHID lcpstlstdlhtypeftllishid;
    @XmlElement(name = "LCPSTLST_ALIAS", required = true)
    protected LCPSTLSTALIAS lcpstlstalias;
    @XmlElement(name = "LCPSTLST_LSTHMST", required = true)
    protected LCPSTLSTLSTHMST lcpstlstlsthmst;
    @XmlElement(name = "LCPSTLST_GDSRRITHSHD", required = true)
    protected LCPSTLSTGDSRRITHSHD lcpstlstgdsrrithshd;
    @XmlElement(name = "LCPSTLST_RESERVED", required = true)
    protected LCPSTLSTRESERVED lcpstlstreserved;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;

    /**
     * Gets the value of the lcpstlstlstctg property.
     * 
     * @return
     *     possible object is
     *     {@link LCPSTLSTLSTCTG }
     *     
     */
    public LCPSTLSTLSTCTG getLCPSTLSTLSTCTG() {
        return lcpstlstlstctg;
    }

    /**
     * Sets the value of the lcpstlstlstctg property.
     * 
     * @param value
     *     allowed object is
     *     {@link LCPSTLSTLSTCTG }
     *     
     */
    public void setLCPSTLSTLSTCTG(LCPSTLSTLSTCTG value) {
        this.lcpstlstlstctg = value;
    }

    /**
     * Gets the value of the lcpstlstledsz property.
     * 
     * @return
     *     possible object is
     *     {@link LCPSTLSTLEDSZ }
     *     
     */
    public LCPSTLSTLEDSZ getLCPSTLSTLEDSZ() {
        return lcpstlstledsz;
    }

    /**
     * Sets the value of the lcpstlstledsz property.
     * 
     * @param value
     *     allowed object is
     *     {@link LCPSTLSTLEDSZ }
     *     
     */
    public void setLCPSTLSTLEDSZ(LCPSTLSTLEDSZ value) {
        this.lcpstlstledsz = value;
    }

    /**
     * Gets the value of the lcpstlstleqmax property.
     * 
     * @return
     *     possible object is
     *     {@link LCPSTLSTLEQMAX }
     *     
     */
    public LCPSTLSTLEQMAX getLCPSTLSTLEQMAX() {
        return lcpstlstleqmax;
    }

    /**
     * Sets the value of the lcpstlstleqmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link LCPSTLSTLEQMAX }
     *     
     */
    public void setLCPSTLSTLEQMAX(LCPSTLSTLEQMAX value) {
        this.lcpstlstleqmax = value;
    }

    /**
     * Gets the value of the lcpstlstlleqmax property.
     * 
     * @return
     *     possible object is
     *     {@link LCPSTLSTLLEQMAX }
     *     
     */
    public LCPSTLSTLLEQMAX getLCPSTLSTLLEQMAX() {
        return lcpstlstlleqmax;
    }

    /**
     * Sets the value of the lcpstlstlleqmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link LCPSTLSTLLEQMAX }
     *     
     */
    public void setLCPSTLSTLLEQMAX(LCPSTLSTLLEQMAX value) {
        this.lcpstlstlleqmax = value;
    }

    /**
     * Gets the value of the lcpstlstdlhtypeftllishtype property.
     * 
     * @return
     *     possible object is
     *     {@link LCPSTLSTDLHTYPEFTLLISHTYPE }
     *     
     */
    public LCPSTLSTDLHTYPEFTLLISHTYPE getLCPSTLSTDLHTYPEFTLLISHTYPE() {
        return lcpstlstdlhtypeftllishtype;
    }

    /**
     * Sets the value of the lcpstlstdlhtypeftllishtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link LCPSTLSTDLHTYPEFTLLISHTYPE }
     *     
     */
    public void setLCPSTLSTDLHTYPEFTLLISHTYPE(LCPSTLSTDLHTYPEFTLLISHTYPE value) {
        this.lcpstlstdlhtypeftllishtype = value;
    }

    /**
     * Gets the value of the lcpstlstdlhtypeftllishid property.
     * 
     * @return
     *     possible object is
     *     {@link LCPSTLSTDLHTYPEFTLLISHID }
     *     
     */
    public LCPSTLSTDLHTYPEFTLLISHID getLCPSTLSTDLHTYPEFTLLISHID() {
        return lcpstlstdlhtypeftllishid;
    }

    /**
     * Sets the value of the lcpstlstdlhtypeftllishid property.
     * 
     * @param value
     *     allowed object is
     *     {@link LCPSTLSTDLHTYPEFTLLISHID }
     *     
     */
    public void setLCPSTLSTDLHTYPEFTLLISHID(LCPSTLSTDLHTYPEFTLLISHID value) {
        this.lcpstlstdlhtypeftllishid = value;
    }

    /**
     * Gets the value of the lcpstlstalias property.
     * 
     * @return
     *     possible object is
     *     {@link LCPSTLSTALIAS }
     *     
     */
    public LCPSTLSTALIAS getLCPSTLSTALIAS() {
        return lcpstlstalias;
    }

    /**
     * Sets the value of the lcpstlstalias property.
     * 
     * @param value
     *     allowed object is
     *     {@link LCPSTLSTALIAS }
     *     
     */
    public void setLCPSTLSTALIAS(LCPSTLSTALIAS value) {
        this.lcpstlstalias = value;
    }

    /**
     * Gets the value of the lcpstlstlsthmst property.
     * 
     * @return
     *     possible object is
     *     {@link LCPSTLSTLSTHMST }
     *     
     */
    public LCPSTLSTLSTHMST getLCPSTLSTLSTHMST() {
        return lcpstlstlsthmst;
    }

    /**
     * Sets the value of the lcpstlstlsthmst property.
     * 
     * @param value
     *     allowed object is
     *     {@link LCPSTLSTLSTHMST }
     *     
     */
    public void setLCPSTLSTLSTHMST(LCPSTLSTLSTHMST value) {
        this.lcpstlstlsthmst = value;
    }

    /**
     * Gets the value of the lcpstlstgdsrrithshd property.
     * 
     * @return
     *     possible object is
     *     {@link LCPSTLSTGDSRRITHSHD }
     *     
     */
    public LCPSTLSTGDSRRITHSHD getLCPSTLSTGDSRRITHSHD() {
        return lcpstlstgdsrrithshd;
    }

    /**
     * Sets the value of the lcpstlstgdsrrithshd property.
     * 
     * @param value
     *     allowed object is
     *     {@link LCPSTLSTGDSRRITHSHD }
     *     
     */
    public void setLCPSTLSTGDSRRITHSHD(LCPSTLSTGDSRRITHSHD value) {
        this.lcpstlstgdsrrithshd = value;
    }

    /**
     * Gets the value of the lcpstlstreserved property.
     * 
     * @return
     *     possible object is
     *     {@link LCPSTLSTRESERVED }
     *     
     */
    public LCPSTLSTRESERVED getLCPSTLSTRESERVED() {
        return lcpstlstreserved;
    }

    /**
     * Sets the value of the lcpstlstreserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link LCPSTLSTRESERVED }
     *     
     */
    public void setLCPSTLSTRESERVED(LCPSTLSTRESERVED value) {
        this.lcpstlstreserved = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

}
