//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.05 at 02:22:03 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM1"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM1TYPE"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM1ID"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM2"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM2TYPE"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM2ID"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM3"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM3TYPE"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM3ID"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM4"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM4TYPE"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM4ID"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM5"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM5TYPE"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM5ID"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM6"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM6TYPE"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM6ID"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM7"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM7TYPE"/&gt;
 *         &lt;element ref="{}MBPTTCHANSELECTION_ITEM7ID"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mbpttchanselectionitem1",
    "mbpttchanselectionitem1TYPE",
    "mbpttchanselectionitem1ID",
    "mbpttchanselectionitem2",
    "mbpttchanselectionitem2TYPE",
    "mbpttchanselectionitem2ID",
    "mbpttchanselectionitem3",
    "mbpttchanselectionitem3TYPE",
    "mbpttchanselectionitem3ID",
    "mbpttchanselectionitem4",
    "mbpttchanselectionitem4TYPE",
    "mbpttchanselectionitem4ID",
    "mbpttchanselectionitem5",
    "mbpttchanselectionitem5TYPE",
    "mbpttchanselectionitem5ID",
    "mbpttchanselectionitem6",
    "mbpttchanselectionitem6TYPE",
    "mbpttchanselectionitem6ID",
    "mbpttchanselectionitem7",
    "mbpttchanselectionitem7TYPE",
    "mbpttchanselectionitem7ID"
})
@XmlRootElement(name = "MBPTTCHANSELECTION_CMP_TYPE")
public class MBPTTCHANSELECTIONCMPTYPE {

    @XmlElement(name = "MBPTTCHANSELECTION_ITEM1", required = true)
    protected MBPTTCHANSELECTIONITEM1 mbpttchanselectionitem1;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM1TYPE", required = true)
    protected MBPTTCHANSELECTIONITEM1TYPE mbpttchanselectionitem1TYPE;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM1ID", required = true)
    protected MBPTTCHANSELECTIONITEM1ID mbpttchanselectionitem1ID;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM2", required = true)
    protected MBPTTCHANSELECTIONITEM2 mbpttchanselectionitem2;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM2TYPE", required = true)
    protected MBPTTCHANSELECTIONITEM2TYPE mbpttchanselectionitem2TYPE;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM2ID", required = true)
    protected MBPTTCHANSELECTIONITEM2ID mbpttchanselectionitem2ID;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM3", required = true)
    protected MBPTTCHANSELECTIONITEM3 mbpttchanselectionitem3;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM3TYPE", required = true)
    protected MBPTTCHANSELECTIONITEM3TYPE mbpttchanselectionitem3TYPE;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM3ID", required = true)
    protected MBPTTCHANSELECTIONITEM3ID mbpttchanselectionitem3ID;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM4", required = true)
    protected MBPTTCHANSELECTIONITEM4 mbpttchanselectionitem4;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM4TYPE", required = true)
    protected MBPTTCHANSELECTIONITEM4TYPE mbpttchanselectionitem4TYPE;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM4ID", required = true)
    protected MBPTTCHANSELECTIONITEM4ID mbpttchanselectionitem4ID;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM5", required = true)
    protected MBPTTCHANSELECTIONITEM5 mbpttchanselectionitem5;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM5TYPE", required = true)
    protected MBPTTCHANSELECTIONITEM5TYPE mbpttchanselectionitem5TYPE;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM5ID", required = true)
    protected MBPTTCHANSELECTIONITEM5ID mbpttchanselectionitem5ID;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM6", required = true)
    protected MBPTTCHANSELECTIONITEM6 mbpttchanselectionitem6;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM6TYPE", required = true)
    protected MBPTTCHANSELECTIONITEM6TYPE mbpttchanselectionitem6TYPE;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM6ID", required = true)
    protected MBPTTCHANSELECTIONITEM6ID mbpttchanselectionitem6ID;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM7", required = true)
    protected MBPTTCHANSELECTIONITEM7 mbpttchanselectionitem7;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM7TYPE", required = true)
    protected MBPTTCHANSELECTIONITEM7TYPE mbpttchanselectionitem7TYPE;
    @XmlElement(name = "MBPTTCHANSELECTION_ITEM7ID", required = true)
    protected MBPTTCHANSELECTIONITEM7ID mbpttchanselectionitem7ID;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;

    /**
     * Gets the value of the mbpttchanselectionitem1 property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM1 }
     *     
     */
    public MBPTTCHANSELECTIONITEM1 getMBPTTCHANSELECTIONITEM1() {
        return mbpttchanselectionitem1;
    }

    /**
     * Sets the value of the mbpttchanselectionitem1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM1 }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM1(MBPTTCHANSELECTIONITEM1 value) {
        this.mbpttchanselectionitem1 = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem1TYPE property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM1TYPE }
     *     
     */
    public MBPTTCHANSELECTIONITEM1TYPE getMBPTTCHANSELECTIONITEM1TYPE() {
        return mbpttchanselectionitem1TYPE;
    }

    /**
     * Sets the value of the mbpttchanselectionitem1TYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM1TYPE }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM1TYPE(MBPTTCHANSELECTIONITEM1TYPE value) {
        this.mbpttchanselectionitem1TYPE = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem1ID property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM1ID }
     *     
     */
    public MBPTTCHANSELECTIONITEM1ID getMBPTTCHANSELECTIONITEM1ID() {
        return mbpttchanselectionitem1ID;
    }

    /**
     * Sets the value of the mbpttchanselectionitem1ID property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM1ID }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM1ID(MBPTTCHANSELECTIONITEM1ID value) {
        this.mbpttchanselectionitem1ID = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem2 property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM2 }
     *     
     */
    public MBPTTCHANSELECTIONITEM2 getMBPTTCHANSELECTIONITEM2() {
        return mbpttchanselectionitem2;
    }

    /**
     * Sets the value of the mbpttchanselectionitem2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM2 }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM2(MBPTTCHANSELECTIONITEM2 value) {
        this.mbpttchanselectionitem2 = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem2TYPE property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM2TYPE }
     *     
     */
    public MBPTTCHANSELECTIONITEM2TYPE getMBPTTCHANSELECTIONITEM2TYPE() {
        return mbpttchanselectionitem2TYPE;
    }

    /**
     * Sets the value of the mbpttchanselectionitem2TYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM2TYPE }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM2TYPE(MBPTTCHANSELECTIONITEM2TYPE value) {
        this.mbpttchanselectionitem2TYPE = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem2ID property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM2ID }
     *     
     */
    public MBPTTCHANSELECTIONITEM2ID getMBPTTCHANSELECTIONITEM2ID() {
        return mbpttchanselectionitem2ID;
    }

    /**
     * Sets the value of the mbpttchanselectionitem2ID property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM2ID }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM2ID(MBPTTCHANSELECTIONITEM2ID value) {
        this.mbpttchanselectionitem2ID = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem3 property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM3 }
     *     
     */
    public MBPTTCHANSELECTIONITEM3 getMBPTTCHANSELECTIONITEM3() {
        return mbpttchanselectionitem3;
    }

    /**
     * Sets the value of the mbpttchanselectionitem3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM3 }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM3(MBPTTCHANSELECTIONITEM3 value) {
        this.mbpttchanselectionitem3 = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem3TYPE property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM3TYPE }
     *     
     */
    public MBPTTCHANSELECTIONITEM3TYPE getMBPTTCHANSELECTIONITEM3TYPE() {
        return mbpttchanselectionitem3TYPE;
    }

    /**
     * Sets the value of the mbpttchanselectionitem3TYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM3TYPE }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM3TYPE(MBPTTCHANSELECTIONITEM3TYPE value) {
        this.mbpttchanselectionitem3TYPE = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem3ID property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM3ID }
     *     
     */
    public MBPTTCHANSELECTIONITEM3ID getMBPTTCHANSELECTIONITEM3ID() {
        return mbpttchanselectionitem3ID;
    }

    /**
     * Sets the value of the mbpttchanselectionitem3ID property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM3ID }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM3ID(MBPTTCHANSELECTIONITEM3ID value) {
        this.mbpttchanselectionitem3ID = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem4 property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM4 }
     *     
     */
    public MBPTTCHANSELECTIONITEM4 getMBPTTCHANSELECTIONITEM4() {
        return mbpttchanselectionitem4;
    }

    /**
     * Sets the value of the mbpttchanselectionitem4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM4 }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM4(MBPTTCHANSELECTIONITEM4 value) {
        this.mbpttchanselectionitem4 = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem4TYPE property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM4TYPE }
     *     
     */
    public MBPTTCHANSELECTIONITEM4TYPE getMBPTTCHANSELECTIONITEM4TYPE() {
        return mbpttchanselectionitem4TYPE;
    }

    /**
     * Sets the value of the mbpttchanselectionitem4TYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM4TYPE }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM4TYPE(MBPTTCHANSELECTIONITEM4TYPE value) {
        this.mbpttchanselectionitem4TYPE = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem4ID property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM4ID }
     *     
     */
    public MBPTTCHANSELECTIONITEM4ID getMBPTTCHANSELECTIONITEM4ID() {
        return mbpttchanselectionitem4ID;
    }

    /**
     * Sets the value of the mbpttchanselectionitem4ID property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM4ID }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM4ID(MBPTTCHANSELECTIONITEM4ID value) {
        this.mbpttchanselectionitem4ID = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem5 property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM5 }
     *     
     */
    public MBPTTCHANSELECTIONITEM5 getMBPTTCHANSELECTIONITEM5() {
        return mbpttchanselectionitem5;
    }

    /**
     * Sets the value of the mbpttchanselectionitem5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM5 }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM5(MBPTTCHANSELECTIONITEM5 value) {
        this.mbpttchanselectionitem5 = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem5TYPE property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM5TYPE }
     *     
     */
    public MBPTTCHANSELECTIONITEM5TYPE getMBPTTCHANSELECTIONITEM5TYPE() {
        return mbpttchanselectionitem5TYPE;
    }

    /**
     * Sets the value of the mbpttchanselectionitem5TYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM5TYPE }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM5TYPE(MBPTTCHANSELECTIONITEM5TYPE value) {
        this.mbpttchanselectionitem5TYPE = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem5ID property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM5ID }
     *     
     */
    public MBPTTCHANSELECTIONITEM5ID getMBPTTCHANSELECTIONITEM5ID() {
        return mbpttchanselectionitem5ID;
    }

    /**
     * Sets the value of the mbpttchanselectionitem5ID property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM5ID }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM5ID(MBPTTCHANSELECTIONITEM5ID value) {
        this.mbpttchanselectionitem5ID = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem6 property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM6 }
     *     
     */
    public MBPTTCHANSELECTIONITEM6 getMBPTTCHANSELECTIONITEM6() {
        return mbpttchanselectionitem6;
    }

    /**
     * Sets the value of the mbpttchanselectionitem6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM6 }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM6(MBPTTCHANSELECTIONITEM6 value) {
        this.mbpttchanselectionitem6 = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem6TYPE property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM6TYPE }
     *     
     */
    public MBPTTCHANSELECTIONITEM6TYPE getMBPTTCHANSELECTIONITEM6TYPE() {
        return mbpttchanselectionitem6TYPE;
    }

    /**
     * Sets the value of the mbpttchanselectionitem6TYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM6TYPE }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM6TYPE(MBPTTCHANSELECTIONITEM6TYPE value) {
        this.mbpttchanselectionitem6TYPE = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem6ID property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM6ID }
     *     
     */
    public MBPTTCHANSELECTIONITEM6ID getMBPTTCHANSELECTIONITEM6ID() {
        return mbpttchanselectionitem6ID;
    }

    /**
     * Sets the value of the mbpttchanselectionitem6ID property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM6ID }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM6ID(MBPTTCHANSELECTIONITEM6ID value) {
        this.mbpttchanselectionitem6ID = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem7 property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM7 }
     *     
     */
    public MBPTTCHANSELECTIONITEM7 getMBPTTCHANSELECTIONITEM7() {
        return mbpttchanselectionitem7;
    }

    /**
     * Sets the value of the mbpttchanselectionitem7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM7 }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM7(MBPTTCHANSELECTIONITEM7 value) {
        this.mbpttchanselectionitem7 = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem7TYPE property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM7TYPE }
     *     
     */
    public MBPTTCHANSELECTIONITEM7TYPE getMBPTTCHANSELECTIONITEM7TYPE() {
        return mbpttchanselectionitem7TYPE;
    }

    /**
     * Sets the value of the mbpttchanselectionitem7TYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM7TYPE }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM7TYPE(MBPTTCHANSELECTIONITEM7TYPE value) {
        this.mbpttchanselectionitem7TYPE = value;
    }

    /**
     * Gets the value of the mbpttchanselectionitem7ID property.
     * 
     * @return
     *     possible object is
     *     {@link MBPTTCHANSELECTIONITEM7ID }
     *     
     */
    public MBPTTCHANSELECTIONITEM7ID getMBPTTCHANSELECTIONITEM7ID() {
        return mbpttchanselectionitem7ID;
    }

    /**
     * Sets the value of the mbpttchanselectionitem7ID property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBPTTCHANSELECTIONITEM7ID }
     *     
     */
    public void setMBPTTCHANSELECTIONITEM7ID(MBPTTCHANSELECTIONITEM7ID value) {
        this.mbpttchanselectionitem7ID = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

}
