//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.07 at 05:56:42 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}MDCSYS_DOSCRTTYPE"/&gt;
 *         &lt;element ref="{}MDCSYS_DOSEN"/&gt;
 *         &lt;element ref="{}MDCSYS_PTTSTTYPE"/&gt;
 *         &lt;element ref="{}MDCSYS_PTTIDTYPE"/&gt;
 *         &lt;element ref="{}MDCSYS_MDCCAENC"/&gt;
 *         &lt;element ref="{}MDCSYS_DOSAUTOMUTEDUR"/&gt;
 *         &lt;element ref="{}MDCSYS_PRMID"/&gt;
 *         &lt;element ref="{}MDCSYS_GRPID"/&gt;
 *         &lt;element ref="{}MDCSYS_DOSCOASTDRT"/&gt;
 *         &lt;element ref="{}MDCSYS_LTDPTCTIME"/&gt;
 *         &lt;element ref="{}MDCSYS_PRETIME"/&gt;
 *         &lt;element ref="{}MDCSYS_EMGCYTYPE"/&gt;
 *         &lt;element ref="{}MDCSYS_EMGCYATYPE"/&gt;
 *         &lt;element ref="{}MDCSYS_MDCEMGCYADECEN"/&gt;
 *         &lt;element ref="{}MDCSYS_SDPREAMBLE"/&gt;
 *         &lt;element ref="{}MDCSYS_EMPTTIDEN"/&gt;
 *         &lt;element ref="{}MDCSYS_EMGCYLMTPTIME"/&gt;
 *         &lt;element ref="{}MDCSYS_DOSFIXRETRYTIME"/&gt;
 *         &lt;element ref="{}MDCSYS_MDCEMGCYPERS"/&gt;
 *         &lt;element ref="{}MDCSYS_MDCEMGCYPERSTYPE"/&gt;
 *         &lt;element ref="{}MDCSYS_MDCEMGCYPERSID"/&gt;
 *         &lt;element ref="{}MDCSYS_PLTRET"/&gt;
 *         &lt;element ref="{}MDCSYS_IMPLTRET"/&gt;
 *         &lt;element ref="{}MDCSYS_PREAMBLETYPE"/&gt;
 *         &lt;element ref="{}MDCSYS_MDCSYSALIAS"/&gt;
 *         &lt;element ref="{}MDCSYS_EMGCYPTTSTEN"/&gt;
 *         &lt;element ref="{}MDCSYS_CALTTYPE"/&gt;
 *         &lt;element ref="{}MDCSYS_RDCKDECEN"/&gt;
 *         &lt;element ref="{}MDCSYS_SELCDECEN"/&gt;
 *         &lt;element ref="{}MDCSYS_ATRSTTMTYPE"/&gt;
 *         &lt;element ref="{}MDCSYS_RACTYPE"/&gt;
 *         &lt;element ref="{}MDCSYS_RMDECEN"/&gt;
 *         &lt;element ref="{}MDCSYS_EMGRM"/&gt;
 *         &lt;element ref="{}MDCSYS_MDCEMRSKYRVT"/&gt;
 *         &lt;element ref="{}MDCSYS_RMM"/&gt;
 *         &lt;element ref="{}MDCSYS_MDCEMRSTKRVTALT"/&gt;
 *         &lt;element ref="{}MDCSYS_RMDUR"/&gt;
 *         &lt;element ref="{}MDCSYS_EMGRMDUR"/&gt;
 *         &lt;element ref="{}MDCSYS_REPACPRETM"/&gt;
 *         &lt;element ref="{}MDCSYS_EMHOTMICTXDUR"/&gt;
 *         &lt;element ref="{}MDCSYS_EMHOTMICRXDUR"/&gt;
 *         &lt;element ref="{}MDCSYS_EMHOTMICCLCNT"/&gt;
 *         &lt;element ref="{}MDCSYS_RESERVED"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mdcsysdoscrttype",
    "mdcsysdosen",
    "mdcsyspttsttype",
    "mdcsyspttidtype",
    "mdcsysmdccaenc",
    "mdcsysdosautomutedur",
    "mdcsysprmid",
    "mdcsysgrpid",
    "mdcsysdoscoastdrt",
    "mdcsysltdptctime",
    "mdcsyspretime",
    "mdcsysemgcytype",
    "mdcsysemgcyatype",
    "mdcsysmdcemgcyadecen",
    "mdcsyssdpreamble",
    "mdcsysempttiden",
    "mdcsysemgcylmtptime",
    "mdcsysdosfixretrytime",
    "mdcsysmdcemgcypers",
    "mdcsysmdcemgcyperstype",
    "mdcsysmdcemgcypersid",
    "mdcsyspltret",
    "mdcsysimpltret",
    "mdcsyspreambletype",
    "mdcsysmdcsysalias",
    "mdcsysemgcypttsten",
    "mdcsyscalttype",
    "mdcsysrdckdecen",
    "mdcsysselcdecen",
    "mdcsysatrsttmtype",
    "mdcsysractype",
    "mdcsysrmdecen",
    "mdcsysemgrm",
    "mdcsysmdcemrskyrvt",
    "mdcsysrmm",
    "mdcsysmdcemrstkrvtalt",
    "mdcsysrmdur",
    "mdcsysemgrmdur",
    "mdcsysrepacpretm",
    "mdcsysemhotmictxdur",
    "mdcsysemhotmicrxdur",
    "mdcsysemhotmicclcnt",
    "mdcsysreserved"
})
@XmlRootElement(name = "MDC_SYS_CMP_TYPE")
public class MDCSYSCMPTYPE {

    @XmlElement(name = "MDCSYS_DOSCRTTYPE", required = true)
    protected MDCSYSDOSCRTTYPE mdcsysdoscrttype;
    @XmlElement(name = "MDCSYS_DOSEN", required = true)
    protected MDCSYSDOSEN mdcsysdosen;
    @XmlElement(name = "MDCSYS_PTTSTTYPE", required = true)
    protected MDCSYSPTTSTTYPE mdcsyspttsttype;
    @XmlElement(name = "MDCSYS_PTTIDTYPE", required = true)
    protected MDCSYSPTTIDTYPE mdcsyspttidtype;
    @XmlElement(name = "MDCSYS_MDCCAENC", required = true)
    protected MDCSYSMDCCAENC mdcsysmdccaenc;
    @XmlElement(name = "MDCSYS_DOSAUTOMUTEDUR", required = true)
    protected MDCSYSDOSAUTOMUTEDUR mdcsysdosautomutedur;
    @XmlElement(name = "MDCSYS_PRMID", required = true)
    protected MDCSYSPRMID mdcsysprmid;
    @XmlElement(name = "MDCSYS_GRPID", required = true)
    protected MDCSYSGRPID mdcsysgrpid;
    @XmlElement(name = "MDCSYS_DOSCOASTDRT", required = true)
    protected MDCSYSDOSCOASTDRT mdcsysdoscoastdrt;
    @XmlElement(name = "MDCSYS_LTDPTCTIME", required = true)
    protected MDCSYSLTDPTCTIME mdcsysltdptctime;
    @XmlElement(name = "MDCSYS_PRETIME", required = true)
    protected MDCSYSPRETIME mdcsyspretime;
    @XmlElement(name = "MDCSYS_EMGCYTYPE", required = true)
    protected MDCSYSEMGCYTYPE mdcsysemgcytype;
    @XmlElement(name = "MDCSYS_EMGCYATYPE", required = true)
    protected MDCSYSEMGCYATYPE mdcsysemgcyatype;
    @XmlElement(name = "MDCSYS_MDCEMGCYADECEN", required = true)
    protected MDCSYSMDCEMGCYADECEN mdcsysmdcemgcyadecen;
    @XmlElement(name = "MDCSYS_SDPREAMBLE", required = true)
    protected MDCSYSSDPREAMBLE mdcsyssdpreamble;
    @XmlElement(name = "MDCSYS_EMPTTIDEN", required = true)
    protected MDCSYSEMPTTIDEN mdcsysempttiden;
    @XmlElement(name = "MDCSYS_EMGCYLMTPTIME", required = true)
    protected MDCSYSEMGCYLMTPTIME mdcsysemgcylmtptime;
    @XmlElement(name = "MDCSYS_DOSFIXRETRYTIME", required = true)
    protected MDCSYSDOSFIXRETRYTIME mdcsysdosfixretrytime;
    @XmlElement(name = "MDCSYS_MDCEMGCYPERS", required = true)
    protected MDCSYSMDCEMGCYPERS mdcsysmdcemgcypers;
    @XmlElement(name = "MDCSYS_MDCEMGCYPERSTYPE", required = true)
    protected MDCSYSMDCEMGCYPERSTYPE mdcsysmdcemgcyperstype;
    @XmlElement(name = "MDCSYS_MDCEMGCYPERSID", required = true)
    protected MDCSYSMDCEMGCYPERSID mdcsysmdcemgcypersid;
    @XmlElement(name = "MDCSYS_PLTRET", required = true)
    protected MDCSYSPLTRET mdcsyspltret;
    @XmlElement(name = "MDCSYS_IMPLTRET", required = true)
    protected MDCSYSIMPLTRET mdcsysimpltret;
    @XmlElement(name = "MDCSYS_PREAMBLETYPE", required = true)
    protected MDCSYSPREAMBLETYPE mdcsyspreambletype;
    @XmlElement(name = "MDCSYS_MDCSYSALIAS", required = true)
    protected MDCSYSMDCSYSALIAS mdcsysmdcsysalias;
    @XmlElement(name = "MDCSYS_EMGCYPTTSTEN", required = true)
    protected MDCSYSEMGCYPTTSTEN mdcsysemgcypttsten;
    @XmlElement(name = "MDCSYS_CALTTYPE", required = true)
    protected MDCSYSCALTTYPE mdcsyscalttype;
    @XmlElement(name = "MDCSYS_RDCKDECEN", required = true)
    protected MDCSYSRDCKDECEN mdcsysrdckdecen;
    @XmlElement(name = "MDCSYS_SELCDECEN", required = true)
    protected MDCSYSSELCDECEN mdcsysselcdecen;
    @XmlElement(name = "MDCSYS_ATRSTTMTYPE", required = true)
    protected MDCSYSATRSTTMTYPE mdcsysatrsttmtype;
    @XmlElement(name = "MDCSYS_RACTYPE", required = true)
    protected MDCSYSRACTYPE mdcsysractype;
    @XmlElement(name = "MDCSYS_RMDECEN", required = true)
    protected MDCSYSRMDECEN mdcsysrmdecen;
    @XmlElement(name = "MDCSYS_EMGRM", required = true)
    protected MDCSYSEMGRM mdcsysemgrm;
    @XmlElement(name = "MDCSYS_MDCEMRSKYRVT", required = true)
    protected MDCSYSMDCEMRSKYRVT mdcsysmdcemrskyrvt;
    @XmlElement(name = "MDCSYS_RMM", required = true)
    protected MDCSYSRMM mdcsysrmm;
    @XmlElement(name = "MDCSYS_MDCEMRSTKRVTALT", required = true)
    protected MDCSYSMDCEMRSTKRVTALT mdcsysmdcemrstkrvtalt;
    @XmlElement(name = "MDCSYS_RMDUR", required = true)
    protected MDCSYSRMDUR mdcsysrmdur;
    @XmlElement(name = "MDCSYS_EMGRMDUR", required = true)
    protected MDCSYSEMGRMDUR mdcsysemgrmdur;
    @XmlElement(name = "MDCSYS_REPACPRETM", required = true)
    protected MDCSYSREPACPRETM mdcsysrepacpretm;
    @XmlElement(name = "MDCSYS_EMHOTMICTXDUR", required = true)
    protected MDCSYSEMHOTMICTXDUR mdcsysemhotmictxdur;
    @XmlElement(name = "MDCSYS_EMHOTMICRXDUR", required = true)
    protected MDCSYSEMHOTMICRXDUR mdcsysemhotmicrxdur;
    @XmlElement(name = "MDCSYS_EMHOTMICCLCNT", required = true)
    protected MDCSYSEMHOTMICCLCNT mdcsysemhotmicclcnt;
    @XmlElement(name = "MDCSYS_RESERVED", required = true)
    protected MDCSYSRESERVED mdcsysreserved;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;

    /**
     * Gets the value of the mdcsysdoscrttype property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSDOSCRTTYPE }
     *     
     */
    public MDCSYSDOSCRTTYPE getMDCSYSDOSCRTTYPE() {
        return mdcsysdoscrttype;
    }

    /**
     * Sets the value of the mdcsysdoscrttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSDOSCRTTYPE }
     *     
     */
    public void setMDCSYSDOSCRTTYPE(MDCSYSDOSCRTTYPE value) {
        this.mdcsysdoscrttype = value;
    }

    /**
     * Gets the value of the mdcsysdosen property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSDOSEN }
     *     
     */
    public MDCSYSDOSEN getMDCSYSDOSEN() {
        return mdcsysdosen;
    }

    /**
     * Sets the value of the mdcsysdosen property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSDOSEN }
     *     
     */
    public void setMDCSYSDOSEN(MDCSYSDOSEN value) {
        this.mdcsysdosen = value;
    }

    /**
     * Gets the value of the mdcsyspttsttype property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSPTTSTTYPE }
     *     
     */
    public MDCSYSPTTSTTYPE getMDCSYSPTTSTTYPE() {
        return mdcsyspttsttype;
    }

    /**
     * Sets the value of the mdcsyspttsttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSPTTSTTYPE }
     *     
     */
    public void setMDCSYSPTTSTTYPE(MDCSYSPTTSTTYPE value) {
        this.mdcsyspttsttype = value;
    }

    /**
     * Gets the value of the mdcsyspttidtype property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSPTTIDTYPE }
     *     
     */
    public MDCSYSPTTIDTYPE getMDCSYSPTTIDTYPE() {
        return mdcsyspttidtype;
    }

    /**
     * Sets the value of the mdcsyspttidtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSPTTIDTYPE }
     *     
     */
    public void setMDCSYSPTTIDTYPE(MDCSYSPTTIDTYPE value) {
        this.mdcsyspttidtype = value;
    }

    /**
     * Gets the value of the mdcsysmdccaenc property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSMDCCAENC }
     *     
     */
    public MDCSYSMDCCAENC getMDCSYSMDCCAENC() {
        return mdcsysmdccaenc;
    }

    /**
     * Sets the value of the mdcsysmdccaenc property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSMDCCAENC }
     *     
     */
    public void setMDCSYSMDCCAENC(MDCSYSMDCCAENC value) {
        this.mdcsysmdccaenc = value;
    }

    /**
     * Gets the value of the mdcsysdosautomutedur property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSDOSAUTOMUTEDUR }
     *     
     */
    public MDCSYSDOSAUTOMUTEDUR getMDCSYSDOSAUTOMUTEDUR() {
        return mdcsysdosautomutedur;
    }

    /**
     * Sets the value of the mdcsysdosautomutedur property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSDOSAUTOMUTEDUR }
     *     
     */
    public void setMDCSYSDOSAUTOMUTEDUR(MDCSYSDOSAUTOMUTEDUR value) {
        this.mdcsysdosautomutedur = value;
    }

    /**
     * Gets the value of the mdcsysprmid property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSPRMID }
     *     
     */
    public MDCSYSPRMID getMDCSYSPRMID() {
        return mdcsysprmid;
    }

    /**
     * Sets the value of the mdcsysprmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSPRMID }
     *     
     */
    public void setMDCSYSPRMID(MDCSYSPRMID value) {
        this.mdcsysprmid = value;
    }

    /**
     * Gets the value of the mdcsysgrpid property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSGRPID }
     *     
     */
    public MDCSYSGRPID getMDCSYSGRPID() {
        return mdcsysgrpid;
    }

    /**
     * Sets the value of the mdcsysgrpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSGRPID }
     *     
     */
    public void setMDCSYSGRPID(MDCSYSGRPID value) {
        this.mdcsysgrpid = value;
    }

    /**
     * Gets the value of the mdcsysdoscoastdrt property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSDOSCOASTDRT }
     *     
     */
    public MDCSYSDOSCOASTDRT getMDCSYSDOSCOASTDRT() {
        return mdcsysdoscoastdrt;
    }

    /**
     * Sets the value of the mdcsysdoscoastdrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSDOSCOASTDRT }
     *     
     */
    public void setMDCSYSDOSCOASTDRT(MDCSYSDOSCOASTDRT value) {
        this.mdcsysdoscoastdrt = value;
    }

    /**
     * Gets the value of the mdcsysltdptctime property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSLTDPTCTIME }
     *     
     */
    public MDCSYSLTDPTCTIME getMDCSYSLTDPTCTIME() {
        return mdcsysltdptctime;
    }

    /**
     * Sets the value of the mdcsysltdptctime property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSLTDPTCTIME }
     *     
     */
    public void setMDCSYSLTDPTCTIME(MDCSYSLTDPTCTIME value) {
        this.mdcsysltdptctime = value;
    }

    /**
     * Gets the value of the mdcsyspretime property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSPRETIME }
     *     
     */
    public MDCSYSPRETIME getMDCSYSPRETIME() {
        return mdcsyspretime;
    }

    /**
     * Sets the value of the mdcsyspretime property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSPRETIME }
     *     
     */
    public void setMDCSYSPRETIME(MDCSYSPRETIME value) {
        this.mdcsyspretime = value;
    }

    /**
     * Gets the value of the mdcsysemgcytype property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSEMGCYTYPE }
     *     
     */
    public MDCSYSEMGCYTYPE getMDCSYSEMGCYTYPE() {
        return mdcsysemgcytype;
    }

    /**
     * Sets the value of the mdcsysemgcytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSEMGCYTYPE }
     *     
     */
    public void setMDCSYSEMGCYTYPE(MDCSYSEMGCYTYPE value) {
        this.mdcsysemgcytype = value;
    }

    /**
     * Gets the value of the mdcsysemgcyatype property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSEMGCYATYPE }
     *     
     */
    public MDCSYSEMGCYATYPE getMDCSYSEMGCYATYPE() {
        return mdcsysemgcyatype;
    }

    /**
     * Sets the value of the mdcsysemgcyatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSEMGCYATYPE }
     *     
     */
    public void setMDCSYSEMGCYATYPE(MDCSYSEMGCYATYPE value) {
        this.mdcsysemgcyatype = value;
    }

    /**
     * Gets the value of the mdcsysmdcemgcyadecen property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSMDCEMGCYADECEN }
     *     
     */
    public MDCSYSMDCEMGCYADECEN getMDCSYSMDCEMGCYADECEN() {
        return mdcsysmdcemgcyadecen;
    }

    /**
     * Sets the value of the mdcsysmdcemgcyadecen property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSMDCEMGCYADECEN }
     *     
     */
    public void setMDCSYSMDCEMGCYADECEN(MDCSYSMDCEMGCYADECEN value) {
        this.mdcsysmdcemgcyadecen = value;
    }

    /**
     * Gets the value of the mdcsyssdpreamble property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSSDPREAMBLE }
     *     
     */
    public MDCSYSSDPREAMBLE getMDCSYSSDPREAMBLE() {
        return mdcsyssdpreamble;
    }

    /**
     * Sets the value of the mdcsyssdpreamble property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSSDPREAMBLE }
     *     
     */
    public void setMDCSYSSDPREAMBLE(MDCSYSSDPREAMBLE value) {
        this.mdcsyssdpreamble = value;
    }

    /**
     * Gets the value of the mdcsysempttiden property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSEMPTTIDEN }
     *     
     */
    public MDCSYSEMPTTIDEN getMDCSYSEMPTTIDEN() {
        return mdcsysempttiden;
    }

    /**
     * Sets the value of the mdcsysempttiden property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSEMPTTIDEN }
     *     
     */
    public void setMDCSYSEMPTTIDEN(MDCSYSEMPTTIDEN value) {
        this.mdcsysempttiden = value;
    }

    /**
     * Gets the value of the mdcsysemgcylmtptime property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSEMGCYLMTPTIME }
     *     
     */
    public MDCSYSEMGCYLMTPTIME getMDCSYSEMGCYLMTPTIME() {
        return mdcsysemgcylmtptime;
    }

    /**
     * Sets the value of the mdcsysemgcylmtptime property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSEMGCYLMTPTIME }
     *     
     */
    public void setMDCSYSEMGCYLMTPTIME(MDCSYSEMGCYLMTPTIME value) {
        this.mdcsysemgcylmtptime = value;
    }

    /**
     * Gets the value of the mdcsysdosfixretrytime property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSDOSFIXRETRYTIME }
     *     
     */
    public MDCSYSDOSFIXRETRYTIME getMDCSYSDOSFIXRETRYTIME() {
        return mdcsysdosfixretrytime;
    }

    /**
     * Sets the value of the mdcsysdosfixretrytime property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSDOSFIXRETRYTIME }
     *     
     */
    public void setMDCSYSDOSFIXRETRYTIME(MDCSYSDOSFIXRETRYTIME value) {
        this.mdcsysdosfixretrytime = value;
    }

    /**
     * Gets the value of the mdcsysmdcemgcypers property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSMDCEMGCYPERS }
     *     
     */
    public MDCSYSMDCEMGCYPERS getMDCSYSMDCEMGCYPERS() {
        return mdcsysmdcemgcypers;
    }

    /**
     * Sets the value of the mdcsysmdcemgcypers property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSMDCEMGCYPERS }
     *     
     */
    public void setMDCSYSMDCEMGCYPERS(MDCSYSMDCEMGCYPERS value) {
        this.mdcsysmdcemgcypers = value;
    }

    /**
     * Gets the value of the mdcsysmdcemgcyperstype property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSMDCEMGCYPERSTYPE }
     *     
     */
    public MDCSYSMDCEMGCYPERSTYPE getMDCSYSMDCEMGCYPERSTYPE() {
        return mdcsysmdcemgcyperstype;
    }

    /**
     * Sets the value of the mdcsysmdcemgcyperstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSMDCEMGCYPERSTYPE }
     *     
     */
    public void setMDCSYSMDCEMGCYPERSTYPE(MDCSYSMDCEMGCYPERSTYPE value) {
        this.mdcsysmdcemgcyperstype = value;
    }

    /**
     * Gets the value of the mdcsysmdcemgcypersid property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSMDCEMGCYPERSID }
     *     
     */
    public MDCSYSMDCEMGCYPERSID getMDCSYSMDCEMGCYPERSID() {
        return mdcsysmdcemgcypersid;
    }

    /**
     * Sets the value of the mdcsysmdcemgcypersid property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSMDCEMGCYPERSID }
     *     
     */
    public void setMDCSYSMDCEMGCYPERSID(MDCSYSMDCEMGCYPERSID value) {
        this.mdcsysmdcemgcypersid = value;
    }

    /**
     * Gets the value of the mdcsyspltret property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSPLTRET }
     *     
     */
    public MDCSYSPLTRET getMDCSYSPLTRET() {
        return mdcsyspltret;
    }

    /**
     * Sets the value of the mdcsyspltret property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSPLTRET }
     *     
     */
    public void setMDCSYSPLTRET(MDCSYSPLTRET value) {
        this.mdcsyspltret = value;
    }

    /**
     * Gets the value of the mdcsysimpltret property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSIMPLTRET }
     *     
     */
    public MDCSYSIMPLTRET getMDCSYSIMPLTRET() {
        return mdcsysimpltret;
    }

    /**
     * Sets the value of the mdcsysimpltret property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSIMPLTRET }
     *     
     */
    public void setMDCSYSIMPLTRET(MDCSYSIMPLTRET value) {
        this.mdcsysimpltret = value;
    }

    /**
     * Gets the value of the mdcsyspreambletype property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSPREAMBLETYPE }
     *     
     */
    public MDCSYSPREAMBLETYPE getMDCSYSPREAMBLETYPE() {
        return mdcsyspreambletype;
    }

    /**
     * Sets the value of the mdcsyspreambletype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSPREAMBLETYPE }
     *     
     */
    public void setMDCSYSPREAMBLETYPE(MDCSYSPREAMBLETYPE value) {
        this.mdcsyspreambletype = value;
    }

    /**
     * Gets the value of the mdcsysmdcsysalias property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSMDCSYSALIAS }
     *     
     */
    public MDCSYSMDCSYSALIAS getMDCSYSMDCSYSALIAS() {
        return mdcsysmdcsysalias;
    }

    /**
     * Sets the value of the mdcsysmdcsysalias property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSMDCSYSALIAS }
     *     
     */
    public void setMDCSYSMDCSYSALIAS(MDCSYSMDCSYSALIAS value) {
        this.mdcsysmdcsysalias = value;
    }

    /**
     * Gets the value of the mdcsysemgcypttsten property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSEMGCYPTTSTEN }
     *     
     */
    public MDCSYSEMGCYPTTSTEN getMDCSYSEMGCYPTTSTEN() {
        return mdcsysemgcypttsten;
    }

    /**
     * Sets the value of the mdcsysemgcypttsten property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSEMGCYPTTSTEN }
     *     
     */
    public void setMDCSYSEMGCYPTTSTEN(MDCSYSEMGCYPTTSTEN value) {
        this.mdcsysemgcypttsten = value;
    }

    /**
     * Gets the value of the mdcsyscalttype property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSCALTTYPE }
     *     
     */
    public MDCSYSCALTTYPE getMDCSYSCALTTYPE() {
        return mdcsyscalttype;
    }

    /**
     * Sets the value of the mdcsyscalttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSCALTTYPE }
     *     
     */
    public void setMDCSYSCALTTYPE(MDCSYSCALTTYPE value) {
        this.mdcsyscalttype = value;
    }

    /**
     * Gets the value of the mdcsysrdckdecen property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSRDCKDECEN }
     *     
     */
    public MDCSYSRDCKDECEN getMDCSYSRDCKDECEN() {
        return mdcsysrdckdecen;
    }

    /**
     * Sets the value of the mdcsysrdckdecen property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSRDCKDECEN }
     *     
     */
    public void setMDCSYSRDCKDECEN(MDCSYSRDCKDECEN value) {
        this.mdcsysrdckdecen = value;
    }

    /**
     * Gets the value of the mdcsysselcdecen property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSSELCDECEN }
     *     
     */
    public MDCSYSSELCDECEN getMDCSYSSELCDECEN() {
        return mdcsysselcdecen;
    }

    /**
     * Sets the value of the mdcsysselcdecen property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSSELCDECEN }
     *     
     */
    public void setMDCSYSSELCDECEN(MDCSYSSELCDECEN value) {
        this.mdcsysselcdecen = value;
    }

    /**
     * Gets the value of the mdcsysatrsttmtype property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSATRSTTMTYPE }
     *     
     */
    public MDCSYSATRSTTMTYPE getMDCSYSATRSTTMTYPE() {
        return mdcsysatrsttmtype;
    }

    /**
     * Sets the value of the mdcsysatrsttmtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSATRSTTMTYPE }
     *     
     */
    public void setMDCSYSATRSTTMTYPE(MDCSYSATRSTTMTYPE value) {
        this.mdcsysatrsttmtype = value;
    }

    /**
     * Gets the value of the mdcsysractype property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSRACTYPE }
     *     
     */
    public MDCSYSRACTYPE getMDCSYSRACTYPE() {
        return mdcsysractype;
    }

    /**
     * Sets the value of the mdcsysractype property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSRACTYPE }
     *     
     */
    public void setMDCSYSRACTYPE(MDCSYSRACTYPE value) {
        this.mdcsysractype = value;
    }

    /**
     * Gets the value of the mdcsysrmdecen property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSRMDECEN }
     *     
     */
    public MDCSYSRMDECEN getMDCSYSRMDECEN() {
        return mdcsysrmdecen;
    }

    /**
     * Sets the value of the mdcsysrmdecen property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSRMDECEN }
     *     
     */
    public void setMDCSYSRMDECEN(MDCSYSRMDECEN value) {
        this.mdcsysrmdecen = value;
    }

    /**
     * Gets the value of the mdcsysemgrm property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSEMGRM }
     *     
     */
    public MDCSYSEMGRM getMDCSYSEMGRM() {
        return mdcsysemgrm;
    }

    /**
     * Sets the value of the mdcsysemgrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSEMGRM }
     *     
     */
    public void setMDCSYSEMGRM(MDCSYSEMGRM value) {
        this.mdcsysemgrm = value;
    }

    /**
     * Gets the value of the mdcsysmdcemrskyrvt property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSMDCEMRSKYRVT }
     *     
     */
    public MDCSYSMDCEMRSKYRVT getMDCSYSMDCEMRSKYRVT() {
        return mdcsysmdcemrskyrvt;
    }

    /**
     * Sets the value of the mdcsysmdcemrskyrvt property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSMDCEMRSKYRVT }
     *     
     */
    public void setMDCSYSMDCEMRSKYRVT(MDCSYSMDCEMRSKYRVT value) {
        this.mdcsysmdcemrskyrvt = value;
    }

    /**
     * Gets the value of the mdcsysrmm property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSRMM }
     *     
     */
    public MDCSYSRMM getMDCSYSRMM() {
        return mdcsysrmm;
    }

    /**
     * Sets the value of the mdcsysrmm property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSRMM }
     *     
     */
    public void setMDCSYSRMM(MDCSYSRMM value) {
        this.mdcsysrmm = value;
    }

    /**
     * Gets the value of the mdcsysmdcemrstkrvtalt property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSMDCEMRSTKRVTALT }
     *     
     */
    public MDCSYSMDCEMRSTKRVTALT getMDCSYSMDCEMRSTKRVTALT() {
        return mdcsysmdcemrstkrvtalt;
    }

    /**
     * Sets the value of the mdcsysmdcemrstkrvtalt property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSMDCEMRSTKRVTALT }
     *     
     */
    public void setMDCSYSMDCEMRSTKRVTALT(MDCSYSMDCEMRSTKRVTALT value) {
        this.mdcsysmdcemrstkrvtalt = value;
    }

    /**
     * Gets the value of the mdcsysrmdur property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSRMDUR }
     *     
     */
    public MDCSYSRMDUR getMDCSYSRMDUR() {
        return mdcsysrmdur;
    }

    /**
     * Sets the value of the mdcsysrmdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSRMDUR }
     *     
     */
    public void setMDCSYSRMDUR(MDCSYSRMDUR value) {
        this.mdcsysrmdur = value;
    }

    /**
     * Gets the value of the mdcsysemgrmdur property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSEMGRMDUR }
     *     
     */
    public MDCSYSEMGRMDUR getMDCSYSEMGRMDUR() {
        return mdcsysemgrmdur;
    }

    /**
     * Sets the value of the mdcsysemgrmdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSEMGRMDUR }
     *     
     */
    public void setMDCSYSEMGRMDUR(MDCSYSEMGRMDUR value) {
        this.mdcsysemgrmdur = value;
    }

    /**
     * Gets the value of the mdcsysrepacpretm property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSREPACPRETM }
     *     
     */
    public MDCSYSREPACPRETM getMDCSYSREPACPRETM() {
        return mdcsysrepacpretm;
    }

    /**
     * Sets the value of the mdcsysrepacpretm property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSREPACPRETM }
     *     
     */
    public void setMDCSYSREPACPRETM(MDCSYSREPACPRETM value) {
        this.mdcsysrepacpretm = value;
    }

    /**
     * Gets the value of the mdcsysemhotmictxdur property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSEMHOTMICTXDUR }
     *     
     */
    public MDCSYSEMHOTMICTXDUR getMDCSYSEMHOTMICTXDUR() {
        return mdcsysemhotmictxdur;
    }

    /**
     * Sets the value of the mdcsysemhotmictxdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSEMHOTMICTXDUR }
     *     
     */
    public void setMDCSYSEMHOTMICTXDUR(MDCSYSEMHOTMICTXDUR value) {
        this.mdcsysemhotmictxdur = value;
    }

    /**
     * Gets the value of the mdcsysemhotmicrxdur property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSEMHOTMICRXDUR }
     *     
     */
    public MDCSYSEMHOTMICRXDUR getMDCSYSEMHOTMICRXDUR() {
        return mdcsysemhotmicrxdur;
    }

    /**
     * Sets the value of the mdcsysemhotmicrxdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSEMHOTMICRXDUR }
     *     
     */
    public void setMDCSYSEMHOTMICRXDUR(MDCSYSEMHOTMICRXDUR value) {
        this.mdcsysemhotmicrxdur = value;
    }

    /**
     * Gets the value of the mdcsysemhotmicclcnt property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSEMHOTMICCLCNT }
     *     
     */
    public MDCSYSEMHOTMICCLCNT getMDCSYSEMHOTMICCLCNT() {
        return mdcsysemhotmicclcnt;
    }

    /**
     * Sets the value of the mdcsysemhotmicclcnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSEMHOTMICCLCNT }
     *     
     */
    public void setMDCSYSEMHOTMICCLCNT(MDCSYSEMHOTMICCLCNT value) {
        this.mdcsysemhotmicclcnt = value;
    }

    /**
     * Gets the value of the mdcsysreserved property.
     * 
     * @return
     *     possible object is
     *     {@link MDCSYSRESERVED }
     *     
     */
    public MDCSYSRESERVED getMDCSYSRESERVED() {
        return mdcsysreserved;
    }

    /**
     * Sets the value of the mdcsysreserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDCSYSRESERVED }
     *     
     */
    public void setMDCSYSRESERVED(MDCSYSRESERVED value) {
        this.mdcsysreserved = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

}
