//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.07 at 05:56:42 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}QU_LSTCTG"/&gt;
 *         &lt;element ref="{}QU_LEDSZ"/&gt;
 *         &lt;element ref="{}QU_LEQMAX"/&gt;
 *         &lt;element ref="{}QU_LLEQMAX"/&gt;
 *         &lt;element ref="{}QCII_UCL_DLH_TYPE_FTLLISHTYPE"/&gt;
 *         &lt;element ref="{}QCII_UCL_DLH_TYPE_FTLLISHID"/&gt;
 *         &lt;element ref="{}QU_ALPHNUMSRCHEN"/&gt;
 *         &lt;element ref="{}QU_RESERVED"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qulstctg",
    "quledsz",
    "quleqmax",
    "qulleqmax",
    "qciiucldlhtypeftllishtype",
    "qciiucldlhtypeftllishid",
    "qualphnumsrchen",
    "qureserved"
})
@XmlRootElement(name = "QCII_UCL_DLH_TYPE")
public class QCIIUCLDLHTYPE {

    @XmlElement(name = "QU_LSTCTG", required = true)
    protected QULSTCTG qulstctg;
    @XmlElement(name = "QU_LEDSZ", required = true)
    protected QULEDSZ quledsz;
    @XmlElement(name = "QU_LEQMAX", required = true)
    protected QULEQMAX quleqmax;
    @XmlElement(name = "QU_LLEQMAX", required = true)
    protected QULLEQMAX qulleqmax;
    @XmlElement(name = "QCII_UCL_DLH_TYPE_FTLLISHTYPE", required = true)
    protected QCIIUCLDLHTYPEFTLLISHTYPE qciiucldlhtypeftllishtype;
    @XmlElement(name = "QCII_UCL_DLH_TYPE_FTLLISHID", required = true)
    protected QCIIUCLDLHTYPEFTLLISHID qciiucldlhtypeftllishid;
    @XmlElement(name = "QU_ALPHNUMSRCHEN", required = true)
    protected QUALPHNUMSRCHEN qualphnumsrchen;
    @XmlElement(name = "QU_RESERVED", required = true)
    protected QURESERVED qureserved;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;

    /**
     * Gets the value of the qulstctg property.
     * 
     * @return
     *     possible object is
     *     {@link QULSTCTG }
     *     
     */
    public QULSTCTG getQULSTCTG() {
        return qulstctg;
    }

    /**
     * Sets the value of the qulstctg property.
     * 
     * @param value
     *     allowed object is
     *     {@link QULSTCTG }
     *     
     */
    public void setQULSTCTG(QULSTCTG value) {
        this.qulstctg = value;
    }

    /**
     * Gets the value of the quledsz property.
     * 
     * @return
     *     possible object is
     *     {@link QULEDSZ }
     *     
     */
    public QULEDSZ getQULEDSZ() {
        return quledsz;
    }

    /**
     * Sets the value of the quledsz property.
     * 
     * @param value
     *     allowed object is
     *     {@link QULEDSZ }
     *     
     */
    public void setQULEDSZ(QULEDSZ value) {
        this.quledsz = value;
    }

    /**
     * Gets the value of the quleqmax property.
     * 
     * @return
     *     possible object is
     *     {@link QULEQMAX }
     *     
     */
    public QULEQMAX getQULEQMAX() {
        return quleqmax;
    }

    /**
     * Sets the value of the quleqmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link QULEQMAX }
     *     
     */
    public void setQULEQMAX(QULEQMAX value) {
        this.quleqmax = value;
    }

    /**
     * Gets the value of the qulleqmax property.
     * 
     * @return
     *     possible object is
     *     {@link QULLEQMAX }
     *     
     */
    public QULLEQMAX getQULLEQMAX() {
        return qulleqmax;
    }

    /**
     * Sets the value of the qulleqmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link QULLEQMAX }
     *     
     */
    public void setQULLEQMAX(QULLEQMAX value) {
        this.qulleqmax = value;
    }

    /**
     * Gets the value of the qciiucldlhtypeftllishtype property.
     * 
     * @return
     *     possible object is
     *     {@link QCIIUCLDLHTYPEFTLLISHTYPE }
     *     
     */
    public QCIIUCLDLHTYPEFTLLISHTYPE getQCIIUCLDLHTYPEFTLLISHTYPE() {
        return qciiucldlhtypeftllishtype;
    }

    /**
     * Sets the value of the qciiucldlhtypeftllishtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link QCIIUCLDLHTYPEFTLLISHTYPE }
     *     
     */
    public void setQCIIUCLDLHTYPEFTLLISHTYPE(QCIIUCLDLHTYPEFTLLISHTYPE value) {
        this.qciiucldlhtypeftllishtype = value;
    }

    /**
     * Gets the value of the qciiucldlhtypeftllishid property.
     * 
     * @return
     *     possible object is
     *     {@link QCIIUCLDLHTYPEFTLLISHID }
     *     
     */
    public QCIIUCLDLHTYPEFTLLISHID getQCIIUCLDLHTYPEFTLLISHID() {
        return qciiucldlhtypeftllishid;
    }

    /**
     * Sets the value of the qciiucldlhtypeftllishid property.
     * 
     * @param value
     *     allowed object is
     *     {@link QCIIUCLDLHTYPEFTLLISHID }
     *     
     */
    public void setQCIIUCLDLHTYPEFTLLISHID(QCIIUCLDLHTYPEFTLLISHID value) {
        this.qciiucldlhtypeftllishid = value;
    }

    /**
     * Gets the value of the qualphnumsrchen property.
     * 
     * @return
     *     possible object is
     *     {@link QUALPHNUMSRCHEN }
     *     
     */
    public QUALPHNUMSRCHEN getQUALPHNUMSRCHEN() {
        return qualphnumsrchen;
    }

    /**
     * Sets the value of the qualphnumsrchen property.
     * 
     * @param value
     *     allowed object is
     *     {@link QUALPHNUMSRCHEN }
     *     
     */
    public void setQUALPHNUMSRCHEN(QUALPHNUMSRCHEN value) {
        this.qualphnumsrchen = value;
    }

    /**
     * Gets the value of the qureserved property.
     * 
     * @return
     *     possible object is
     *     {@link QURESERVED }
     *     
     */
    public QURESERVED getQURESERVED() {
        return qureserved;
    }

    /**
     * Sets the value of the qureserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link QURESERVED }
     *     
     */
    public void setQURESERVED(QURESERVED value) {
        this.qureserved = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

}
