//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.07 at 05:56:42 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}RX_TG_LIST_DLL_TYPE_NTLLISHTYPE"/&gt;
 *         &lt;element ref="{}RX_TG_LIST_DLL_TYPE_NTLLISHID"/&gt;
 *         &lt;element ref="{}RXTG_LLEQ"/&gt;
 *         &lt;element ref="{}RXTG_DGUCLCOMP"/&gt;
 *         &lt;element ref="{}RXTG_DGUCLCOMPTYPE"/&gt;
 *         &lt;element ref="{}RXTG_DGUCLCOMPID"/&gt;
 *         &lt;element ref="{}RXTGL_RESERVED"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="ListLetID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rxtglistdlltypentllishtype",
    "rxtglistdlltypentllishid",
    "rxtglleq",
    "rxtgdguclcomp",
    "rxtgdguclcomptype",
    "rxtgdguclcompid",
    "rxtglreserved"
})
@XmlRootElement(name = "RX_TG_LIST_DLL_TYPE")
public class RXTGLISTDLLTYPE {

    @XmlElement(name = "RX_TG_LIST_DLL_TYPE_NTLLISHTYPE", required = true)
    protected RXTGLISTDLLTYPENTLLISHTYPE rxtglistdlltypentllishtype;
    @XmlElement(name = "RX_TG_LIST_DLL_TYPE_NTLLISHID", required = true)
    protected RXTGLISTDLLTYPENTLLISHID rxtglistdlltypentllishid;
    @XmlElement(name = "RXTG_LLEQ", required = true)
    protected RXTGLLEQ rxtglleq;
    @XmlElement(name = "RXTG_DGUCLCOMP", required = true)
    protected RXTGDGUCLCOMP rxtgdguclcomp;
    @XmlElement(name = "RXTG_DGUCLCOMPTYPE", required = true)
    protected RXTGDGUCLCOMPTYPE rxtgdguclcomptype;
    @XmlElement(name = "RXTG_DGUCLCOMPID", required = true)
    protected RXTGDGUCLCOMPID rxtgdguclcompid;
    @XmlElement(name = "RXTGL_RESERVED", required = true)
    protected RXTGLRESERVED rxtglreserved;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;
    @XmlAttribute(name = "ListLetID", required = true)
    protected BigInteger listLetID;

    /**
     * Gets the value of the rxtglistdlltypentllishtype property.
     * 
     * @return
     *     possible object is
     *     {@link RXTGLISTDLLTYPENTLLISHTYPE }
     *     
     */
    public RXTGLISTDLLTYPENTLLISHTYPE getRXTGLISTDLLTYPENTLLISHTYPE() {
        return rxtglistdlltypentllishtype;
    }

    /**
     * Sets the value of the rxtglistdlltypentllishtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link RXTGLISTDLLTYPENTLLISHTYPE }
     *     
     */
    public void setRXTGLISTDLLTYPENTLLISHTYPE(RXTGLISTDLLTYPENTLLISHTYPE value) {
        this.rxtglistdlltypentllishtype = value;
    }

    /**
     * Gets the value of the rxtglistdlltypentllishid property.
     * 
     * @return
     *     possible object is
     *     {@link RXTGLISTDLLTYPENTLLISHID }
     *     
     */
    public RXTGLISTDLLTYPENTLLISHID getRXTGLISTDLLTYPENTLLISHID() {
        return rxtglistdlltypentllishid;
    }

    /**
     * Sets the value of the rxtglistdlltypentllishid property.
     * 
     * @param value
     *     allowed object is
     *     {@link RXTGLISTDLLTYPENTLLISHID }
     *     
     */
    public void setRXTGLISTDLLTYPENTLLISHID(RXTGLISTDLLTYPENTLLISHID value) {
        this.rxtglistdlltypentllishid = value;
    }

    /**
     * Gets the value of the rxtglleq property.
     * 
     * @return
     *     possible object is
     *     {@link RXTGLLEQ }
     *     
     */
    public RXTGLLEQ getRXTGLLEQ() {
        return rxtglleq;
    }

    /**
     * Sets the value of the rxtglleq property.
     * 
     * @param value
     *     allowed object is
     *     {@link RXTGLLEQ }
     *     
     */
    public void setRXTGLLEQ(RXTGLLEQ value) {
        this.rxtglleq = value;
    }

    /**
     * Gets the value of the rxtgdguclcomp property.
     * 
     * @return
     *     possible object is
     *     {@link RXTGDGUCLCOMP }
     *     
     */
    public RXTGDGUCLCOMP getRXTGDGUCLCOMP() {
        return rxtgdguclcomp;
    }

    /**
     * Sets the value of the rxtgdguclcomp property.
     * 
     * @param value
     *     allowed object is
     *     {@link RXTGDGUCLCOMP }
     *     
     */
    public void setRXTGDGUCLCOMP(RXTGDGUCLCOMP value) {
        this.rxtgdguclcomp = value;
    }

    /**
     * Gets the value of the rxtgdguclcomptype property.
     * 
     * @return
     *     possible object is
     *     {@link RXTGDGUCLCOMPTYPE }
     *     
     */
    public RXTGDGUCLCOMPTYPE getRXTGDGUCLCOMPTYPE() {
        return rxtgdguclcomptype;
    }

    /**
     * Sets the value of the rxtgdguclcomptype property.
     * 
     * @param value
     *     allowed object is
     *     {@link RXTGDGUCLCOMPTYPE }
     *     
     */
    public void setRXTGDGUCLCOMPTYPE(RXTGDGUCLCOMPTYPE value) {
        this.rxtgdguclcomptype = value;
    }

    /**
     * Gets the value of the rxtgdguclcompid property.
     * 
     * @return
     *     possible object is
     *     {@link RXTGDGUCLCOMPID }
     *     
     */
    public RXTGDGUCLCOMPID getRXTGDGUCLCOMPID() {
        return rxtgdguclcompid;
    }

    /**
     * Sets the value of the rxtgdguclcompid property.
     * 
     * @param value
     *     allowed object is
     *     {@link RXTGDGUCLCOMPID }
     *     
     */
    public void setRXTGDGUCLCOMPID(RXTGDGUCLCOMPID value) {
        this.rxtgdguclcompid = value;
    }

    /**
     * Gets the value of the rxtglreserved property.
     * 
     * @return
     *     possible object is
     *     {@link RXTGLRESERVED }
     *     
     */
    public RXTGLRESERVED getRXTGLRESERVED() {
        return rxtglreserved;
    }

    /**
     * Sets the value of the rxtglreserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link RXTGLRESERVED }
     *     
     */
    public void setRXTGLRESERVED(RXTGLRESERVED value) {
        this.rxtglreserved = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

    /**
     * Gets the value of the listLetID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListLetID() {
        return listLetID;
    }

    /**
     * Sets the value of the listLetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListLetID(BigInteger value) {
        this.listLetID = value;
    }

}
