//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.07 at 05:56:42 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_ENCTONEDUR"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_DECMINDUR"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_DECMAXDUR"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE1"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE2"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE3"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE4"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE5"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE6"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE7"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE8"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE9"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE10"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE11"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE12"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE13"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE14"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE15"/&gt;
 *         &lt;element ref="{}S5USRDEFSIGSTD_TONE16"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s5USRDEFSIGSTDENCTONEDUR",
    "s5USRDEFSIGSTDDECMINDUR",
    "s5USRDEFSIGSTDDECMAXDUR",
    "s5USRDEFSIGSTDTONE1",
    "s5USRDEFSIGSTDTONE2",
    "s5USRDEFSIGSTDTONE3",
    "s5USRDEFSIGSTDTONE4",
    "s5USRDEFSIGSTDTONE5",
    "s5USRDEFSIGSTDTONE6",
    "s5USRDEFSIGSTDTONE7",
    "s5USRDEFSIGSTDTONE8",
    "s5USRDEFSIGSTDTONE9",
    "s5USRDEFSIGSTDTONE10",
    "s5USRDEFSIGSTDTONE11",
    "s5USRDEFSIGSTDTONE12",
    "s5USRDEFSIGSTDTONE13",
    "s5USRDEFSIGSTDTONE14",
    "s5USRDEFSIGSTDTONE15",
    "s5USRDEFSIGSTDTONE16"
})
@XmlRootElement(name = "SLT_5_USER_DEFINED_SIGNAL_STD_CMP_TYPE")
public class SLT5USERDEFINEDSIGNALSTDCMPTYPE {

    @XmlElement(name = "S5USRDEFSIGSTD_ENCTONEDUR", required = true)
    protected S5USRDEFSIGSTDENCTONEDUR s5USRDEFSIGSTDENCTONEDUR;
    @XmlElement(name = "S5USRDEFSIGSTD_DECMINDUR", required = true)
    protected S5USRDEFSIGSTDDECMINDUR s5USRDEFSIGSTDDECMINDUR;
    @XmlElement(name = "S5USRDEFSIGSTD_DECMAXDUR", required = true)
    protected S5USRDEFSIGSTDDECMAXDUR s5USRDEFSIGSTDDECMAXDUR;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE1", required = true)
    protected S5USRDEFSIGSTDTONE1 s5USRDEFSIGSTDTONE1;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE2", required = true)
    protected S5USRDEFSIGSTDTONE2 s5USRDEFSIGSTDTONE2;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE3", required = true)
    protected S5USRDEFSIGSTDTONE3 s5USRDEFSIGSTDTONE3;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE4", required = true)
    protected S5USRDEFSIGSTDTONE4 s5USRDEFSIGSTDTONE4;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE5", required = true)
    protected S5USRDEFSIGSTDTONE5 s5USRDEFSIGSTDTONE5;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE6", required = true)
    protected S5USRDEFSIGSTDTONE6 s5USRDEFSIGSTDTONE6;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE7", required = true)
    protected S5USRDEFSIGSTDTONE7 s5USRDEFSIGSTDTONE7;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE8", required = true)
    protected S5USRDEFSIGSTDTONE8 s5USRDEFSIGSTDTONE8;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE9", required = true)
    protected S5USRDEFSIGSTDTONE9 s5USRDEFSIGSTDTONE9;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE10", required = true)
    protected S5USRDEFSIGSTDTONE10 s5USRDEFSIGSTDTONE10;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE11", required = true)
    protected S5USRDEFSIGSTDTONE11 s5USRDEFSIGSTDTONE11;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE12", required = true)
    protected S5USRDEFSIGSTDTONE12 s5USRDEFSIGSTDTONE12;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE13", required = true)
    protected S5USRDEFSIGSTDTONE13 s5USRDEFSIGSTDTONE13;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE14", required = true)
    protected S5USRDEFSIGSTDTONE14 s5USRDEFSIGSTDTONE14;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE15", required = true)
    protected S5USRDEFSIGSTDTONE15 s5USRDEFSIGSTDTONE15;
    @XmlElement(name = "S5USRDEFSIGSTD_TONE16", required = true)
    protected S5USRDEFSIGSTDTONE16 s5USRDEFSIGSTDTONE16;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;

    /**
     * Gets the value of the s5USRDEFSIGSTDENCTONEDUR property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDENCTONEDUR }
     *     
     */
    public S5USRDEFSIGSTDENCTONEDUR getS5USRDEFSIGSTDENCTONEDUR() {
        return s5USRDEFSIGSTDENCTONEDUR;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDENCTONEDUR property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDENCTONEDUR }
     *     
     */
    public void setS5USRDEFSIGSTDENCTONEDUR(S5USRDEFSIGSTDENCTONEDUR value) {
        this.s5USRDEFSIGSTDENCTONEDUR = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDDECMINDUR property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDDECMINDUR }
     *     
     */
    public S5USRDEFSIGSTDDECMINDUR getS5USRDEFSIGSTDDECMINDUR() {
        return s5USRDEFSIGSTDDECMINDUR;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDDECMINDUR property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDDECMINDUR }
     *     
     */
    public void setS5USRDEFSIGSTDDECMINDUR(S5USRDEFSIGSTDDECMINDUR value) {
        this.s5USRDEFSIGSTDDECMINDUR = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDDECMAXDUR property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDDECMAXDUR }
     *     
     */
    public S5USRDEFSIGSTDDECMAXDUR getS5USRDEFSIGSTDDECMAXDUR() {
        return s5USRDEFSIGSTDDECMAXDUR;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDDECMAXDUR property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDDECMAXDUR }
     *     
     */
    public void setS5USRDEFSIGSTDDECMAXDUR(S5USRDEFSIGSTDDECMAXDUR value) {
        this.s5USRDEFSIGSTDDECMAXDUR = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE1 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE1 }
     *     
     */
    public S5USRDEFSIGSTDTONE1 getS5USRDEFSIGSTDTONE1() {
        return s5USRDEFSIGSTDTONE1;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE1 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE1(S5USRDEFSIGSTDTONE1 value) {
        this.s5USRDEFSIGSTDTONE1 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE2 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE2 }
     *     
     */
    public S5USRDEFSIGSTDTONE2 getS5USRDEFSIGSTDTONE2() {
        return s5USRDEFSIGSTDTONE2;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE2 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE2(S5USRDEFSIGSTDTONE2 value) {
        this.s5USRDEFSIGSTDTONE2 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE3 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE3 }
     *     
     */
    public S5USRDEFSIGSTDTONE3 getS5USRDEFSIGSTDTONE3() {
        return s5USRDEFSIGSTDTONE3;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE3 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE3(S5USRDEFSIGSTDTONE3 value) {
        this.s5USRDEFSIGSTDTONE3 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE4 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE4 }
     *     
     */
    public S5USRDEFSIGSTDTONE4 getS5USRDEFSIGSTDTONE4() {
        return s5USRDEFSIGSTDTONE4;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE4 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE4(S5USRDEFSIGSTDTONE4 value) {
        this.s5USRDEFSIGSTDTONE4 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE5 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE5 }
     *     
     */
    public S5USRDEFSIGSTDTONE5 getS5USRDEFSIGSTDTONE5() {
        return s5USRDEFSIGSTDTONE5;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE5 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE5(S5USRDEFSIGSTDTONE5 value) {
        this.s5USRDEFSIGSTDTONE5 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE6 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE6 }
     *     
     */
    public S5USRDEFSIGSTDTONE6 getS5USRDEFSIGSTDTONE6() {
        return s5USRDEFSIGSTDTONE6;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE6 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE6(S5USRDEFSIGSTDTONE6 value) {
        this.s5USRDEFSIGSTDTONE6 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE7 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE7 }
     *     
     */
    public S5USRDEFSIGSTDTONE7 getS5USRDEFSIGSTDTONE7() {
        return s5USRDEFSIGSTDTONE7;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE7 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE7(S5USRDEFSIGSTDTONE7 value) {
        this.s5USRDEFSIGSTDTONE7 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE8 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE8 }
     *     
     */
    public S5USRDEFSIGSTDTONE8 getS5USRDEFSIGSTDTONE8() {
        return s5USRDEFSIGSTDTONE8;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE8 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE8(S5USRDEFSIGSTDTONE8 value) {
        this.s5USRDEFSIGSTDTONE8 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE9 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE9 }
     *     
     */
    public S5USRDEFSIGSTDTONE9 getS5USRDEFSIGSTDTONE9() {
        return s5USRDEFSIGSTDTONE9;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE9 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE9(S5USRDEFSIGSTDTONE9 value) {
        this.s5USRDEFSIGSTDTONE9 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE10 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE10 }
     *     
     */
    public S5USRDEFSIGSTDTONE10 getS5USRDEFSIGSTDTONE10() {
        return s5USRDEFSIGSTDTONE10;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE10 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE10(S5USRDEFSIGSTDTONE10 value) {
        this.s5USRDEFSIGSTDTONE10 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE11 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE11 }
     *     
     */
    public S5USRDEFSIGSTDTONE11 getS5USRDEFSIGSTDTONE11() {
        return s5USRDEFSIGSTDTONE11;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE11 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE11(S5USRDEFSIGSTDTONE11 value) {
        this.s5USRDEFSIGSTDTONE11 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE12 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE12 }
     *     
     */
    public S5USRDEFSIGSTDTONE12 getS5USRDEFSIGSTDTONE12() {
        return s5USRDEFSIGSTDTONE12;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE12 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE12(S5USRDEFSIGSTDTONE12 value) {
        this.s5USRDEFSIGSTDTONE12 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE13 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE13 }
     *     
     */
    public S5USRDEFSIGSTDTONE13 getS5USRDEFSIGSTDTONE13() {
        return s5USRDEFSIGSTDTONE13;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE13 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE13(S5USRDEFSIGSTDTONE13 value) {
        this.s5USRDEFSIGSTDTONE13 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE14 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE14 }
     *     
     */
    public S5USRDEFSIGSTDTONE14 getS5USRDEFSIGSTDTONE14() {
        return s5USRDEFSIGSTDTONE14;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE14 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE14(S5USRDEFSIGSTDTONE14 value) {
        this.s5USRDEFSIGSTDTONE14 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE15 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE15 }
     *     
     */
    public S5USRDEFSIGSTDTONE15 getS5USRDEFSIGSTDTONE15() {
        return s5USRDEFSIGSTDTONE15;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE15 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE15(S5USRDEFSIGSTDTONE15 value) {
        this.s5USRDEFSIGSTDTONE15 = value;
    }

    /**
     * Gets the value of the s5USRDEFSIGSTDTONE16 property.
     * 
     * @return
     *     possible object is
     *     {@link S5USRDEFSIGSTDTONE16 }
     *     
     */
    public S5USRDEFSIGSTDTONE16 getS5USRDEFSIGSTDTONE16() {
        return s5USRDEFSIGSTDTONE16;
    }

    /**
     * Sets the value of the s5USRDEFSIGSTDTONE16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5USRDEFSIGSTDTONE16 }
     *     
     */
    public void setS5USRDEFSIGSTDTONE16(S5USRDEFSIGSTDTONE16 value) {
        this.s5USRDEFSIGSTDTONE16 = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

}
