//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.07 at 05:56:42 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}SSP_LSTCTG"/&gt;
 *         &lt;element ref="{}SSP_LEDSZ"/&gt;
 *         &lt;element ref="{}SSP_LEQMAX"/&gt;
 *         &lt;element ref="{}SSP_LLEQMAX"/&gt;
 *         &lt;element ref="{}ST_SRCH_DLH_TYPE_FTLLISHTYPE"/&gt;
 *         &lt;element ref="{}ST_SRCH_DLH_TYPE_FTLLISHID"/&gt;
 *         &lt;element ref="{}SSP_PR1MEMTYPE"/&gt;
 *         &lt;element ref="{}SSP_PR1MEMID"/&gt;
 *         &lt;element ref="{}SSP_PR2MEMTYPE"/&gt;
 *         &lt;element ref="{}SSP_PR2MEMID"/&gt;
 *         &lt;element ref="{}SSP_DSGTXMEMTYPE"/&gt;
 *         &lt;element ref="{}SSP_DSGTXMEMID"/&gt;
 *         &lt;element ref="{}SSP_SCANLISTALIAS"/&gt;
 *         &lt;element ref="{}SSP_TLKSCNEN"/&gt;
 *         &lt;element ref="{}SSP_PLLOCKCHMARKEN"/&gt;
 *         &lt;element ref="{}SSP_LSTDYNMCDTMNHMCH"/&gt;
 *         &lt;element ref="{}SSP_RSSITHRFORROAM"/&gt;
 *         &lt;element ref="{}SSP_RESERVED"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ssplstctg",
    "sspledsz",
    "sspleqmax",
    "ssplleqmax",
    "stsrchdlhtypeftllishtype",
    "stsrchdlhtypeftllishid",
    "ssppr1MEMTYPE",
    "ssppr1MEMID",
    "ssppr2MEMTYPE",
    "ssppr2MEMID",
    "sspdsgtxmemtype",
    "sspdsgtxmemid",
    "sspscanlistalias",
    "ssptlkscnen",
    "ssppllockchmarken",
    "ssplstdynmcdtmnhmch",
    "ssprssithrforroam",
    "sspreserved"
})
@XmlRootElement(name = "ST_SRCH_DLH_TYPE")
public class STSRCHDLHTYPE {

    @XmlElement(name = "SSP_LSTCTG", required = true)
    protected SSPLSTCTG ssplstctg;
    @XmlElement(name = "SSP_LEDSZ", required = true)
    protected SSPLEDSZ sspledsz;
    @XmlElement(name = "SSP_LEQMAX", required = true)
    protected SSPLEQMAX sspleqmax;
    @XmlElement(name = "SSP_LLEQMAX", required = true)
    protected SSPLLEQMAX ssplleqmax;
    @XmlElement(name = "ST_SRCH_DLH_TYPE_FTLLISHTYPE", required = true)
    protected STSRCHDLHTYPEFTLLISHTYPE stsrchdlhtypeftllishtype;
    @XmlElement(name = "ST_SRCH_DLH_TYPE_FTLLISHID", required = true)
    protected STSRCHDLHTYPEFTLLISHID stsrchdlhtypeftllishid;
    @XmlElement(name = "SSP_PR1MEMTYPE", required = true)
    protected SSPPR1MEMTYPE ssppr1MEMTYPE;
    @XmlElement(name = "SSP_PR1MEMID", required = true)
    protected SSPPR1MEMID ssppr1MEMID;
    @XmlElement(name = "SSP_PR2MEMTYPE", required = true)
    protected SSPPR2MEMTYPE ssppr2MEMTYPE;
    @XmlElement(name = "SSP_PR2MEMID", required = true)
    protected SSPPR2MEMID ssppr2MEMID;
    @XmlElement(name = "SSP_DSGTXMEMTYPE", required = true)
    protected SSPDSGTXMEMTYPE sspdsgtxmemtype;
    @XmlElement(name = "SSP_DSGTXMEMID", required = true)
    protected SSPDSGTXMEMID sspdsgtxmemid;
    @XmlElement(name = "SSP_SCANLISTALIAS", required = true)
    protected SSPSCANLISTALIAS sspscanlistalias;
    @XmlElement(name = "SSP_TLKSCNEN", required = true)
    protected SSPTLKSCNEN ssptlkscnen;
    @XmlElement(name = "SSP_PLLOCKCHMARKEN", required = true)
    protected SSPPLLOCKCHMARKEN ssppllockchmarken;
    @XmlElement(name = "SSP_LSTDYNMCDTMNHMCH", required = true)
    protected SSPLSTDYNMCDTMNHMCH ssplstdynmcdtmnhmch;
    @XmlElement(name = "SSP_RSSITHRFORROAM", required = true)
    protected SSPRSSITHRFORROAM ssprssithrforroam;
    @XmlElement(name = "SSP_RESERVED", required = true)
    protected SSPRESERVED sspreserved;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;

    /**
     * Gets the value of the ssplstctg property.
     * 
     * @return
     *     possible object is
     *     {@link SSPLSTCTG }
     *     
     */
    public SSPLSTCTG getSSPLSTCTG() {
        return ssplstctg;
    }

    /**
     * Sets the value of the ssplstctg property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPLSTCTG }
     *     
     */
    public void setSSPLSTCTG(SSPLSTCTG value) {
        this.ssplstctg = value;
    }

    /**
     * Gets the value of the sspledsz property.
     * 
     * @return
     *     possible object is
     *     {@link SSPLEDSZ }
     *     
     */
    public SSPLEDSZ getSSPLEDSZ() {
        return sspledsz;
    }

    /**
     * Sets the value of the sspledsz property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPLEDSZ }
     *     
     */
    public void setSSPLEDSZ(SSPLEDSZ value) {
        this.sspledsz = value;
    }

    /**
     * Gets the value of the sspleqmax property.
     * 
     * @return
     *     possible object is
     *     {@link SSPLEQMAX }
     *     
     */
    public SSPLEQMAX getSSPLEQMAX() {
        return sspleqmax;
    }

    /**
     * Sets the value of the sspleqmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPLEQMAX }
     *     
     */
    public void setSSPLEQMAX(SSPLEQMAX value) {
        this.sspleqmax = value;
    }

    /**
     * Gets the value of the ssplleqmax property.
     * 
     * @return
     *     possible object is
     *     {@link SSPLLEQMAX }
     *     
     */
    public SSPLLEQMAX getSSPLLEQMAX() {
        return ssplleqmax;
    }

    /**
     * Sets the value of the ssplleqmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPLLEQMAX }
     *     
     */
    public void setSSPLLEQMAX(SSPLLEQMAX value) {
        this.ssplleqmax = value;
    }

    /**
     * Gets the value of the stsrchdlhtypeftllishtype property.
     * 
     * @return
     *     possible object is
     *     {@link STSRCHDLHTYPEFTLLISHTYPE }
     *     
     */
    public STSRCHDLHTYPEFTLLISHTYPE getSTSRCHDLHTYPEFTLLISHTYPE() {
        return stsrchdlhtypeftllishtype;
    }

    /**
     * Sets the value of the stsrchdlhtypeftllishtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link STSRCHDLHTYPEFTLLISHTYPE }
     *     
     */
    public void setSTSRCHDLHTYPEFTLLISHTYPE(STSRCHDLHTYPEFTLLISHTYPE value) {
        this.stsrchdlhtypeftllishtype = value;
    }

    /**
     * Gets the value of the stsrchdlhtypeftllishid property.
     * 
     * @return
     *     possible object is
     *     {@link STSRCHDLHTYPEFTLLISHID }
     *     
     */
    public STSRCHDLHTYPEFTLLISHID getSTSRCHDLHTYPEFTLLISHID() {
        return stsrchdlhtypeftllishid;
    }

    /**
     * Sets the value of the stsrchdlhtypeftllishid property.
     * 
     * @param value
     *     allowed object is
     *     {@link STSRCHDLHTYPEFTLLISHID }
     *     
     */
    public void setSTSRCHDLHTYPEFTLLISHID(STSRCHDLHTYPEFTLLISHID value) {
        this.stsrchdlhtypeftllishid = value;
    }

    /**
     * Gets the value of the ssppr1MEMTYPE property.
     * 
     * @return
     *     possible object is
     *     {@link SSPPR1MEMTYPE }
     *     
     */
    public SSPPR1MEMTYPE getSSPPR1MEMTYPE() {
        return ssppr1MEMTYPE;
    }

    /**
     * Sets the value of the ssppr1MEMTYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPPR1MEMTYPE }
     *     
     */
    public void setSSPPR1MEMTYPE(SSPPR1MEMTYPE value) {
        this.ssppr1MEMTYPE = value;
    }

    /**
     * Gets the value of the ssppr1MEMID property.
     * 
     * @return
     *     possible object is
     *     {@link SSPPR1MEMID }
     *     
     */
    public SSPPR1MEMID getSSPPR1MEMID() {
        return ssppr1MEMID;
    }

    /**
     * Sets the value of the ssppr1MEMID property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPPR1MEMID }
     *     
     */
    public void setSSPPR1MEMID(SSPPR1MEMID value) {
        this.ssppr1MEMID = value;
    }

    /**
     * Gets the value of the ssppr2MEMTYPE property.
     * 
     * @return
     *     possible object is
     *     {@link SSPPR2MEMTYPE }
     *     
     */
    public SSPPR2MEMTYPE getSSPPR2MEMTYPE() {
        return ssppr2MEMTYPE;
    }

    /**
     * Sets the value of the ssppr2MEMTYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPPR2MEMTYPE }
     *     
     */
    public void setSSPPR2MEMTYPE(SSPPR2MEMTYPE value) {
        this.ssppr2MEMTYPE = value;
    }

    /**
     * Gets the value of the ssppr2MEMID property.
     * 
     * @return
     *     possible object is
     *     {@link SSPPR2MEMID }
     *     
     */
    public SSPPR2MEMID getSSPPR2MEMID() {
        return ssppr2MEMID;
    }

    /**
     * Sets the value of the ssppr2MEMID property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPPR2MEMID }
     *     
     */
    public void setSSPPR2MEMID(SSPPR2MEMID value) {
        this.ssppr2MEMID = value;
    }

    /**
     * Gets the value of the sspdsgtxmemtype property.
     * 
     * @return
     *     possible object is
     *     {@link SSPDSGTXMEMTYPE }
     *     
     */
    public SSPDSGTXMEMTYPE getSSPDSGTXMEMTYPE() {
        return sspdsgtxmemtype;
    }

    /**
     * Sets the value of the sspdsgtxmemtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPDSGTXMEMTYPE }
     *     
     */
    public void setSSPDSGTXMEMTYPE(SSPDSGTXMEMTYPE value) {
        this.sspdsgtxmemtype = value;
    }

    /**
     * Gets the value of the sspdsgtxmemid property.
     * 
     * @return
     *     possible object is
     *     {@link SSPDSGTXMEMID }
     *     
     */
    public SSPDSGTXMEMID getSSPDSGTXMEMID() {
        return sspdsgtxmemid;
    }

    /**
     * Sets the value of the sspdsgtxmemid property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPDSGTXMEMID }
     *     
     */
    public void setSSPDSGTXMEMID(SSPDSGTXMEMID value) {
        this.sspdsgtxmemid = value;
    }

    /**
     * Gets the value of the sspscanlistalias property.
     * 
     * @return
     *     possible object is
     *     {@link SSPSCANLISTALIAS }
     *     
     */
    public SSPSCANLISTALIAS getSSPSCANLISTALIAS() {
        return sspscanlistalias;
    }

    /**
     * Sets the value of the sspscanlistalias property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPSCANLISTALIAS }
     *     
     */
    public void setSSPSCANLISTALIAS(SSPSCANLISTALIAS value) {
        this.sspscanlistalias = value;
    }

    /**
     * Gets the value of the ssptlkscnen property.
     * 
     * @return
     *     possible object is
     *     {@link SSPTLKSCNEN }
     *     
     */
    public SSPTLKSCNEN getSSPTLKSCNEN() {
        return ssptlkscnen;
    }

    /**
     * Sets the value of the ssptlkscnen property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPTLKSCNEN }
     *     
     */
    public void setSSPTLKSCNEN(SSPTLKSCNEN value) {
        this.ssptlkscnen = value;
    }

    /**
     * Gets the value of the ssppllockchmarken property.
     * 
     * @return
     *     possible object is
     *     {@link SSPPLLOCKCHMARKEN }
     *     
     */
    public SSPPLLOCKCHMARKEN getSSPPLLOCKCHMARKEN() {
        return ssppllockchmarken;
    }

    /**
     * Sets the value of the ssppllockchmarken property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPPLLOCKCHMARKEN }
     *     
     */
    public void setSSPPLLOCKCHMARKEN(SSPPLLOCKCHMARKEN value) {
        this.ssppllockchmarken = value;
    }

    /**
     * Gets the value of the ssplstdynmcdtmnhmch property.
     * 
     * @return
     *     possible object is
     *     {@link SSPLSTDYNMCDTMNHMCH }
     *     
     */
    public SSPLSTDYNMCDTMNHMCH getSSPLSTDYNMCDTMNHMCH() {
        return ssplstdynmcdtmnhmch;
    }

    /**
     * Sets the value of the ssplstdynmcdtmnhmch property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPLSTDYNMCDTMNHMCH }
     *     
     */
    public void setSSPLSTDYNMCDTMNHMCH(SSPLSTDYNMCDTMNHMCH value) {
        this.ssplstdynmcdtmnhmch = value;
    }

    /**
     * Gets the value of the ssprssithrforroam property.
     * 
     * @return
     *     possible object is
     *     {@link SSPRSSITHRFORROAM }
     *     
     */
    public SSPRSSITHRFORROAM getSSPRSSITHRFORROAM() {
        return ssprssithrforroam;
    }

    /**
     * Sets the value of the ssprssithrforroam property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPRSSITHRFORROAM }
     *     
     */
    public void setSSPRSSITHRFORROAM(SSPRSSITHRFORROAM value) {
        this.ssprssithrforroam = value;
    }

    /**
     * Gets the value of the sspreserved property.
     * 
     * @return
     *     possible object is
     *     {@link SSPRESERVED }
     *     
     */
    public SSPRESERVED getSSPRESERVED() {
        return sspreserved;
    }

    /**
     * Sets the value of the sspreserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSPRESERVED }
     *     
     */
    public void setSSPRESERVED(SSPRESERVED value) {
        this.sspreserved = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

}
