//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.05 at 02:22:03 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}SURC_DTMFTNLVL"/&gt;
 *         &lt;element ref="{}SURC_IWFACKTMRIPSC"/&gt;
 *         &lt;element ref="{}SURC_DYNAMICDISTORTIONCONTROLSTATE"/&gt;
 *         &lt;element ref="{}SURC_INTCALLHTIPSC"/&gt;
 *         &lt;element ref="{}SURC_TELRVTCHL7ACKWTTMR"/&gt;
 *         &lt;element ref="{}SURC_ARSINITDLY"/&gt;
 *         &lt;element ref="{}SURC_CALLALTTNDUR"/&gt;
 *         &lt;element ref="{}SURC_TRTRETRYCNT"/&gt;
 *         &lt;element ref="{}SURC_TRTRDRETRYMAXINTVAL"/&gt;
 *         &lt;element ref="{}SURC_TRTGRANTINTV"/&gt;
 *         &lt;element ref="{}SURC_DATACAPABILITY"/&gt;
 *         &lt;element ref="{}SURC_VOICEONLY"/&gt;
 *         &lt;element ref="{}SURC_DELETEALLJOBTICKETS"/&gt;
 *         &lt;element ref="{}SURC_DELETEALLTEXTMESSAGES"/&gt;
 *         &lt;element ref="{}SURC_TELRVTCHL2ACKWTTMR"/&gt;
 *         &lt;element ref="{}SURC_NCAT"/&gt;
 *         &lt;element ref="{}SURC_RESERVED"/&gt;
 *         &lt;element ref="{}SURC_IPSCTRTGRANTINTV"/&gt;
 *         &lt;element ref="{}SURC_ALLOWMANDOWNUSERCONTROL"/&gt;
 *         &lt;element ref="{}SURC_MANDOWNSTATUS"/&gt;
 *         &lt;element ref="{}SURC_HWLSPRSEN"/&gt;
 *         &lt;element ref="{}SURC_TXTMSGALTTNDUR"/&gt;
 *         &lt;element ref="{}SURC_625EDMBCNITV"/&gt;
 *         &lt;element ref="{}SURC_625EDMSAGINC"/&gt;
 *         &lt;element ref="{}SURC_625EDMDFSWD"/&gt;
 *         &lt;element ref="{}SURC_625EDMSAGTOT"/&gt;
 *         &lt;element ref="{}SURC_625EDMBCNDUR"/&gt;
 *         &lt;element ref="{}SURC_625ETTSPCLCD"/&gt;
 *         &lt;element ref="{}SURC_625EMINSPCLCD"/&gt;
 *         &lt;element ref="{}SURC_OACSUCSBKACKTIMER"/&gt;
 *         &lt;element ref="{}SURC_IMEFTEN"/&gt;
 *         &lt;element ref="{}SURC_IMEOPTWDPRDC"/&gt;
 *         &lt;element ref="{}SURC_IMEOPTSTWCPT"/&gt;
 *         &lt;element ref="{}SURC_IMEOPTMULTTP"/&gt;
 *         &lt;element ref="{}SURC_IMEOPTCURIPT"/&gt;
 *         &lt;element ref="{}SURC_IMEOPTNUMLCK"/&gt;
 *         &lt;element ref="{}SURC_IMEOPTKRNJN"/&gt;
 *         &lt;element ref="{}SURC_IMEOPTWDCRCT"/&gt;
 *         &lt;element ref="{}SURC_IMEOPTCPLK"/&gt;
 *         &lt;element ref="{}SURC_USERENVIRONMENTPROFILE"/&gt;
 *         &lt;element ref="{}SURC_ARTSADBIDCTP"/&gt;
 *         &lt;element ref="{}SURC_ARTSVSIDCTEN"/&gt;
 *         &lt;element ref="{}SURC_LCPRMATHMTRH"/&gt;
 *         &lt;element ref="{}SURC_ALTTNFXVLM"/&gt;
 *         &lt;element ref="{}SURC_IMEOPTNEDTTM"/&gt;
 *         &lt;element ref="{}SURC_TSTMDEN"/&gt;
 *         &lt;element ref="{}SURC_BTPERMANENTDISCOVERABLEENABLE"/&gt;
 *         &lt;element ref="{}SURC_DELETEALLUSERUCL"/&gt;
 *         &lt;element ref="{}SURC_DELETEALLCALLLOG"/&gt;
 *         &lt;element ref="{}SURC_LOGINCAPABILITY"/&gt;
 *         &lt;element ref="{}SURC_DELETEOPTIONBOARDUNIQUEIDENTIFIER"/&gt;
 *         &lt;element ref="{}SURC_CHANNELINDEXENABLE"/&gt;
 *         &lt;element ref="{}SURC_SECURESIGNINID"/&gt;
 *         &lt;element ref="{}SURC_PROHIBITTONEONINTERRUPT"/&gt;
 *         &lt;element ref="{}SURC_USERPREFERENCEPROFILE"/&gt;
 *         &lt;element ref="{}SURC_RMNATHMTHRH"/&gt;
 *         &lt;element ref="{}SURC_CCBIHBQKKY"/&gt;
 *         &lt;element ref="{}SURC_LCPRMBCINTVL"/&gt;
 *         &lt;element ref="{}SURC_625EDMGNRSUID"/&gt;
 *         &lt;element ref="{}SURC_BSMWAAEN"/&gt;
 *         &lt;element ref="{}SURC_PHTSATBRT"/&gt;
 *         &lt;element ref="{}SURC_VBALTTYPE"/&gt;
 *         &lt;element ref="{}SURC_BATTCHARGMODE"/&gt;
 *         &lt;element ref="{}SURC_ANALOGVOICESCRAMBLINGCODE"/&gt;
 *         &lt;element ref="{}SURC_NTBRTTHR"/&gt;
 *         &lt;element ref="{}SURC_DYBRTTHR"/&gt;
 *         &lt;element ref="{}SURC_3PDYBRTLOWTHR"/&gt;
 *         &lt;element ref="{}SURC_WPFLPATH"/&gt;
 *         &lt;element ref="{}SURC_WPFLNAME"/&gt;
 *         &lt;element ref="{}SURC_3PDYBRTHIGHTHR"/&gt;
 *         &lt;element ref="{}SURC_3PNTBRTLOWTHR"/&gt;
 *         &lt;element ref="{}SURC_3PNTBRTHIGHTHR"/&gt;
 *         &lt;element ref="{}SURC_EMERGENCYALARMTONEDURATION"/&gt;
 *         &lt;element ref="{}SURC_ATKPDLCKEN"/&gt;
 *         &lt;element ref="{}SURC_EMERGENCYMODELEDENABLE"/&gt;
 *         &lt;element ref="{}SURC_HWLSPRSSNSTV"/&gt;
 *         &lt;element ref="{}SURC_MINENTRYNUMFORCHSEARCH"/&gt;
 *         &lt;element ref="{}SURC_MINENTRYNUMFORNON-CHSEARCH"/&gt;
 *         &lt;element ref="{}SURC_LOG-INACKSESSION"/&gt;
 *         &lt;element ref="{}SURC_LOG-INID"/&gt;
 *         &lt;element ref="{}SURC_EMERGENCYSEARCHTONEVOLUME"/&gt;
 *         &lt;element ref="{}SURC_EMERGENCYSEARCHTONECONTROL"/&gt;
 *         &lt;element ref="{}SURC_EMERGENCYSEARCHTONESPEAKERSELECT"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "surcdtmftnlvl",
    "surciwfacktmripsc",
    "surcdynamicdistortioncontrolstate",
    "surcintcallhtipsc",
    "surctelrvtchl7ACKWTTMR",
    "surcarsinitdly",
    "surccallalttndur",
    "surctrtretrycnt",
    "surctrtrdretrymaxintval",
    "surctrtgrantintv",
    "surcdatacapability",
    "surcvoiceonly",
    "surcdeletealljobtickets",
    "surcdeletealltextmessages",
    "surctelrvtchl2ACKWTTMR",
    "surcncat",
    "surcreserved",
    "surcipsctrtgrantintv",
    "surcallowmandownusercontrol",
    "surcmandownstatus",
    "surchwlsprsen",
    "surctxtmsgalttndur",
    "surc625EDMBCNITV",
    "surc625EDMSAGINC",
    "surc625EDMDFSWD",
    "surc625EDMSAGTOT",
    "surc625EDMBCNDUR",
    "surc625ETTSPCLCD",
    "surc625EMINSPCLCD",
    "surcoacsucsbkacktimer",
    "surcimeften",
    "surcimeoptwdprdc",
    "surcimeoptstwcpt",
    "surcimeoptmulttp",
    "surcimeoptcuript",
    "surcimeoptnumlck",
    "surcimeoptkrnjn",
    "surcimeoptwdcrct",
    "surcimeoptcplk",
    "surcuserenvironmentprofile",
    "surcartsadbidctp",
    "surcartsvsidcten",
    "surclcprmathmtrh",
    "surcalttnfxvlm",
    "surcimeoptnedttm",
    "surctstmden",
    "surcbtpermanentdiscoverableenable",
    "surcdeletealluserucl",
    "surcdeleteallcalllog",
    "surclogincapability",
    "surcdeleteoptionboarduniqueidentifier",
    "surcchannelindexenable",
    "surcsecuresigninid",
    "surcprohibittoneoninterrupt",
    "surcuserpreferenceprofile",
    "surcrmnathmthrh",
    "surcccbihbqkky",
    "surclcprmbcintvl",
    "surc625EDMGNRSUID",
    "surcbsmwaaen",
    "surcphtsatbrt",
    "surcvbalttype",
    "surcbattchargmode",
    "surcanalogvoicescramblingcode",
    "surcntbrtthr",
    "surcdybrtthr",
    "surc3PDYBRTLOWTHR",
    "surcwpflpath",
    "surcwpflname",
    "surc3PDYBRTHIGHTHR",
    "surc3PNTBRTLOWTHR",
    "surc3PNTBRTHIGHTHR",
    "surcemergencyalarmtoneduration",
    "surcatkpdlcken",
    "surcemergencymodeledenable",
    "surchwlsprssnstv",
    "surcminentrynumforchsearch",
    "surcminentrynumfornonchsearch",
    "surcloginacksession",
    "surcloginid",
    "surcemergencysearchtonevolume",
    "surcemergencysearchtonecontrol",
    "surcemergencysearchtonespeakerselect"
})
@XmlRootElement(name = "SURC_CMP_TYPE")
public class SURCCMPTYPE {

    @XmlElement(name = "SURC_DTMFTNLVL", required = true)
    protected SURCDTMFTNLVL surcdtmftnlvl;
    @XmlElement(name = "SURC_IWFACKTMRIPSC", required = true)
    protected SURCIWFACKTMRIPSC surciwfacktmripsc;
    @XmlElement(name = "SURC_DYNAMICDISTORTIONCONTROLSTATE", required = true)
    protected SURCDYNAMICDISTORTIONCONTROLSTATE surcdynamicdistortioncontrolstate;
    @XmlElement(name = "SURC_INTCALLHTIPSC", required = true)
    protected SURCINTCALLHTIPSC surcintcallhtipsc;
    @XmlElement(name = "SURC_TELRVTCHL7ACKWTTMR", required = true)
    protected SURCTELRVTCHL7ACKWTTMR surctelrvtchl7ACKWTTMR;
    @XmlElement(name = "SURC_ARSINITDLY", required = true)
    protected SURCARSINITDLY surcarsinitdly;
    @XmlElement(name = "SURC_CALLALTTNDUR", required = true)
    protected SURCCALLALTTNDUR surccallalttndur;
    @XmlElement(name = "SURC_TRTRETRYCNT", required = true)
    protected SURCTRTRETRYCNT surctrtretrycnt;
    @XmlElement(name = "SURC_TRTRDRETRYMAXINTVAL", required = true)
    protected SURCTRTRDRETRYMAXINTVAL surctrtrdretrymaxintval;
    @XmlElement(name = "SURC_TRTGRANTINTV", required = true)
    protected SURCTRTGRANTINTV surctrtgrantintv;
    @XmlElement(name = "SURC_DATACAPABILITY", required = true)
    protected SURCDATACAPABILITY surcdatacapability;
    @XmlElement(name = "SURC_VOICEONLY", required = true)
    protected SURCVOICEONLY surcvoiceonly;
    @XmlElement(name = "SURC_DELETEALLJOBTICKETS", required = true)
    protected SURCDELETEALLJOBTICKETS surcdeletealljobtickets;
    @XmlElement(name = "SURC_DELETEALLTEXTMESSAGES", required = true)
    protected SURCDELETEALLTEXTMESSAGES surcdeletealltextmessages;
    @XmlElement(name = "SURC_TELRVTCHL2ACKWTTMR", required = true)
    protected SURCTELRVTCHL2ACKWTTMR surctelrvtchl2ACKWTTMR;
    @XmlElement(name = "SURC_NCAT", required = true)
    protected SURCNCAT surcncat;
    @XmlElement(name = "SURC_RESERVED", required = true)
    protected SURCRESERVED surcreserved;
    @XmlElement(name = "SURC_IPSCTRTGRANTINTV", required = true)
    protected SURCIPSCTRTGRANTINTV surcipsctrtgrantintv;
    @XmlElement(name = "SURC_ALLOWMANDOWNUSERCONTROL", required = true)
    protected SURCALLOWMANDOWNUSERCONTROL surcallowmandownusercontrol;
    @XmlElement(name = "SURC_MANDOWNSTATUS", required = true)
    protected SURCMANDOWNSTATUS surcmandownstatus;
    @XmlElement(name = "SURC_HWLSPRSEN", required = true)
    protected SURCHWLSPRSEN surchwlsprsen;
    @XmlElement(name = "SURC_TXTMSGALTTNDUR", required = true)
    protected SURCTXTMSGALTTNDUR surctxtmsgalttndur;
    @XmlElement(name = "SURC_625EDMBCNITV", required = true)
    protected SURC625EDMBCNITV surc625EDMBCNITV;
    @XmlElement(name = "SURC_625EDMSAGINC", required = true)
    protected SURC625EDMSAGINC surc625EDMSAGINC;
    @XmlElement(name = "SURC_625EDMDFSWD", required = true)
    protected SURC625EDMDFSWD surc625EDMDFSWD;
    @XmlElement(name = "SURC_625EDMSAGTOT", required = true)
    protected SURC625EDMSAGTOT surc625EDMSAGTOT;
    @XmlElement(name = "SURC_625EDMBCNDUR", required = true)
    protected SURC625EDMBCNDUR surc625EDMBCNDUR;
    @XmlElement(name = "SURC_625ETTSPCLCD", required = true)
    protected SURC625ETTSPCLCD surc625ETTSPCLCD;
    @XmlElement(name = "SURC_625EMINSPCLCD", required = true)
    protected SURC625EMINSPCLCD surc625EMINSPCLCD;
    @XmlElement(name = "SURC_OACSUCSBKACKTIMER", required = true)
    protected SURCOACSUCSBKACKTIMER surcoacsucsbkacktimer;
    @XmlElement(name = "SURC_IMEFTEN", required = true)
    protected SURCIMEFTEN surcimeften;
    @XmlElement(name = "SURC_IMEOPTWDPRDC", required = true)
    protected SURCIMEOPTWDPRDC surcimeoptwdprdc;
    @XmlElement(name = "SURC_IMEOPTSTWCPT", required = true)
    protected SURCIMEOPTSTWCPT surcimeoptstwcpt;
    @XmlElement(name = "SURC_IMEOPTMULTTP", required = true)
    protected SURCIMEOPTMULTTP surcimeoptmulttp;
    @XmlElement(name = "SURC_IMEOPTCURIPT", required = true)
    protected SURCIMEOPTCURIPT surcimeoptcuript;
    @XmlElement(name = "SURC_IMEOPTNUMLCK", required = true)
    protected SURCIMEOPTNUMLCK surcimeoptnumlck;
    @XmlElement(name = "SURC_IMEOPTKRNJN", required = true)
    protected SURCIMEOPTKRNJN surcimeoptkrnjn;
    @XmlElement(name = "SURC_IMEOPTWDCRCT", required = true)
    protected SURCIMEOPTWDCRCT surcimeoptwdcrct;
    @XmlElement(name = "SURC_IMEOPTCPLK", required = true)
    protected SURCIMEOPTCPLK surcimeoptcplk;
    @XmlElement(name = "SURC_USERENVIRONMENTPROFILE", required = true)
    protected SURCUSERENVIRONMENTPROFILE surcuserenvironmentprofile;
    @XmlElement(name = "SURC_ARTSADBIDCTP", required = true)
    protected SURCARTSADBIDCTP surcartsadbidctp;
    @XmlElement(name = "SURC_ARTSVSIDCTEN", required = true)
    protected SURCARTSVSIDCTEN surcartsvsidcten;
    @XmlElement(name = "SURC_LCPRMATHMTRH", required = true)
    protected SURCLCPRMATHMTRH surclcprmathmtrh;
    @XmlElement(name = "SURC_ALTTNFXVLM", required = true)
    protected SURCALTTNFXVLM surcalttnfxvlm;
    @XmlElement(name = "SURC_IMEOPTNEDTTM", required = true)
    protected SURCIMEOPTNEDTTM surcimeoptnedttm;
    @XmlElement(name = "SURC_TSTMDEN", required = true)
    protected SURCTSTMDEN surctstmden;
    @XmlElement(name = "SURC_BTPERMANENTDISCOVERABLEENABLE", required = true)
    protected SURCBTPERMANENTDISCOVERABLEENABLE surcbtpermanentdiscoverableenable;
    @XmlElement(name = "SURC_DELETEALLUSERUCL", required = true)
    protected SURCDELETEALLUSERUCL surcdeletealluserucl;
    @XmlElement(name = "SURC_DELETEALLCALLLOG", required = true)
    protected SURCDELETEALLCALLLOG surcdeleteallcalllog;
    @XmlElement(name = "SURC_LOGINCAPABILITY", required = true)
    protected SURCLOGINCAPABILITY surclogincapability;
    @XmlElement(name = "SURC_DELETEOPTIONBOARDUNIQUEIDENTIFIER", required = true)
    protected SURCDELETEOPTIONBOARDUNIQUEIDENTIFIER surcdeleteoptionboarduniqueidentifier;
    @XmlElement(name = "SURC_CHANNELINDEXENABLE", required = true)
    protected SURCCHANNELINDEXENABLE surcchannelindexenable;
    @XmlElement(name = "SURC_SECURESIGNINID", required = true)
    protected SURCSECURESIGNINID surcsecuresigninid;
    @XmlElement(name = "SURC_PROHIBITTONEONINTERRUPT", required = true)
    protected SURCPROHIBITTONEONINTERRUPT surcprohibittoneoninterrupt;
    @XmlElement(name = "SURC_USERPREFERENCEPROFILE", required = true)
    protected SURCUSERPREFERENCEPROFILE surcuserpreferenceprofile;
    @XmlElement(name = "SURC_RMNATHMTHRH", required = true)
    protected SURCRMNATHMTHRH surcrmnathmthrh;
    @XmlElement(name = "SURC_CCBIHBQKKY", required = true)
    protected SURCCCBIHBQKKY surcccbihbqkky;
    @XmlElement(name = "SURC_LCPRMBCINTVL", required = true)
    protected SURCLCPRMBCINTVL surclcprmbcintvl;
    @XmlElement(name = "SURC_625EDMGNRSUID", required = true)
    protected SURC625EDMGNRSUID surc625EDMGNRSUID;
    @XmlElement(name = "SURC_BSMWAAEN", required = true)
    protected SURCBSMWAAEN surcbsmwaaen;
    @XmlElement(name = "SURC_PHTSATBRT", required = true)
    protected SURCPHTSATBRT surcphtsatbrt;
    @XmlElement(name = "SURC_VBALTTYPE", required = true)
    protected SURCVBALTTYPE surcvbalttype;
    @XmlElement(name = "SURC_BATTCHARGMODE", required = true)
    protected SURCBATTCHARGMODE surcbattchargmode;
    @XmlElement(name = "SURC_ANALOGVOICESCRAMBLINGCODE", required = true)
    protected SURCANALOGVOICESCRAMBLINGCODE surcanalogvoicescramblingcode;
    @XmlElement(name = "SURC_NTBRTTHR", required = true)
    protected SURCNTBRTTHR surcntbrtthr;
    @XmlElement(name = "SURC_DYBRTTHR", required = true)
    protected SURCDYBRTTHR surcdybrtthr;
    @XmlElement(name = "SURC_3PDYBRTLOWTHR", required = true)
    protected SURC3PDYBRTLOWTHR surc3PDYBRTLOWTHR;
    @XmlElement(name = "SURC_WPFLPATH", required = true)
    protected SURCWPFLPATH surcwpflpath;
    @XmlElement(name = "SURC_WPFLNAME", required = true)
    protected SURCWPFLNAME surcwpflname;
    @XmlElement(name = "SURC_3PDYBRTHIGHTHR", required = true)
    protected SURC3PDYBRTHIGHTHR surc3PDYBRTHIGHTHR;
    @XmlElement(name = "SURC_3PNTBRTLOWTHR", required = true)
    protected SURC3PNTBRTLOWTHR surc3PNTBRTLOWTHR;
    @XmlElement(name = "SURC_3PNTBRTHIGHTHR", required = true)
    protected SURC3PNTBRTHIGHTHR surc3PNTBRTHIGHTHR;
    @XmlElement(name = "SURC_EMERGENCYALARMTONEDURATION", required = true)
    protected SURCEMERGENCYALARMTONEDURATION surcemergencyalarmtoneduration;
    @XmlElement(name = "SURC_ATKPDLCKEN", required = true)
    protected SURCATKPDLCKEN surcatkpdlcken;
    @XmlElement(name = "SURC_EMERGENCYMODELEDENABLE", required = true)
    protected SURCEMERGENCYMODELEDENABLE surcemergencymodeledenable;
    @XmlElement(name = "SURC_HWLSPRSSNSTV", required = true)
    protected SURCHWLSPRSSNSTV surchwlsprssnstv;
    @XmlElement(name = "SURC_MINENTRYNUMFORCHSEARCH", required = true)
    protected SURCMINENTRYNUMFORCHSEARCH surcminentrynumforchsearch;
    @XmlElement(name = "SURC_MINENTRYNUMFORNON-CHSEARCH", required = true)
    protected SURCMINENTRYNUMFORNONCHSEARCH surcminentrynumfornonchsearch;
    @XmlElement(name = "SURC_LOG-INACKSESSION", required = true)
    protected SURCLOGINACKSESSION surcloginacksession;
    @XmlElement(name = "SURC_LOG-INID", required = true)
    protected SURCLOGINID surcloginid;
    @XmlElement(name = "SURC_EMERGENCYSEARCHTONEVOLUME", required = true)
    protected SURCEMERGENCYSEARCHTONEVOLUME surcemergencysearchtonevolume;
    @XmlElement(name = "SURC_EMERGENCYSEARCHTONECONTROL", required = true)
    protected SURCEMERGENCYSEARCHTONECONTROL surcemergencysearchtonecontrol;
    @XmlElement(name = "SURC_EMERGENCYSEARCHTONESPEAKERSELECT", required = true)
    protected SURCEMERGENCYSEARCHTONESPEAKERSELECT surcemergencysearchtonespeakerselect;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;

    /**
     * Gets the value of the surcdtmftnlvl property.
     * 
     * @return
     *     possible object is
     *     {@link SURCDTMFTNLVL }
     *     
     */
    public SURCDTMFTNLVL getSURCDTMFTNLVL() {
        return surcdtmftnlvl;
    }

    /**
     * Sets the value of the surcdtmftnlvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCDTMFTNLVL }
     *     
     */
    public void setSURCDTMFTNLVL(SURCDTMFTNLVL value) {
        this.surcdtmftnlvl = value;
    }

    /**
     * Gets the value of the surciwfacktmripsc property.
     * 
     * @return
     *     possible object is
     *     {@link SURCIWFACKTMRIPSC }
     *     
     */
    public SURCIWFACKTMRIPSC getSURCIWFACKTMRIPSC() {
        return surciwfacktmripsc;
    }

    /**
     * Sets the value of the surciwfacktmripsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCIWFACKTMRIPSC }
     *     
     */
    public void setSURCIWFACKTMRIPSC(SURCIWFACKTMRIPSC value) {
        this.surciwfacktmripsc = value;
    }

    /**
     * Gets the value of the surcdynamicdistortioncontrolstate property.
     * 
     * @return
     *     possible object is
     *     {@link SURCDYNAMICDISTORTIONCONTROLSTATE }
     *     
     */
    public SURCDYNAMICDISTORTIONCONTROLSTATE getSURCDYNAMICDISTORTIONCONTROLSTATE() {
        return surcdynamicdistortioncontrolstate;
    }

    /**
     * Sets the value of the surcdynamicdistortioncontrolstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCDYNAMICDISTORTIONCONTROLSTATE }
     *     
     */
    public void setSURCDYNAMICDISTORTIONCONTROLSTATE(SURCDYNAMICDISTORTIONCONTROLSTATE value) {
        this.surcdynamicdistortioncontrolstate = value;
    }

    /**
     * Gets the value of the surcintcallhtipsc property.
     * 
     * @return
     *     possible object is
     *     {@link SURCINTCALLHTIPSC }
     *     
     */
    public SURCINTCALLHTIPSC getSURCINTCALLHTIPSC() {
        return surcintcallhtipsc;
    }

    /**
     * Sets the value of the surcintcallhtipsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCINTCALLHTIPSC }
     *     
     */
    public void setSURCINTCALLHTIPSC(SURCINTCALLHTIPSC value) {
        this.surcintcallhtipsc = value;
    }

    /**
     * Gets the value of the surctelrvtchl7ACKWTTMR property.
     * 
     * @return
     *     possible object is
     *     {@link SURCTELRVTCHL7ACKWTTMR }
     *     
     */
    public SURCTELRVTCHL7ACKWTTMR getSURCTELRVTCHL7ACKWTTMR() {
        return surctelrvtchl7ACKWTTMR;
    }

    /**
     * Sets the value of the surctelrvtchl7ACKWTTMR property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCTELRVTCHL7ACKWTTMR }
     *     
     */
    public void setSURCTELRVTCHL7ACKWTTMR(SURCTELRVTCHL7ACKWTTMR value) {
        this.surctelrvtchl7ACKWTTMR = value;
    }

    /**
     * Gets the value of the surcarsinitdly property.
     * 
     * @return
     *     possible object is
     *     {@link SURCARSINITDLY }
     *     
     */
    public SURCARSINITDLY getSURCARSINITDLY() {
        return surcarsinitdly;
    }

    /**
     * Sets the value of the surcarsinitdly property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCARSINITDLY }
     *     
     */
    public void setSURCARSINITDLY(SURCARSINITDLY value) {
        this.surcarsinitdly = value;
    }

    /**
     * Gets the value of the surccallalttndur property.
     * 
     * @return
     *     possible object is
     *     {@link SURCCALLALTTNDUR }
     *     
     */
    public SURCCALLALTTNDUR getSURCCALLALTTNDUR() {
        return surccallalttndur;
    }

    /**
     * Sets the value of the surccallalttndur property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCCALLALTTNDUR }
     *     
     */
    public void setSURCCALLALTTNDUR(SURCCALLALTTNDUR value) {
        this.surccallalttndur = value;
    }

    /**
     * Gets the value of the surctrtretrycnt property.
     * 
     * @return
     *     possible object is
     *     {@link SURCTRTRETRYCNT }
     *     
     */
    public SURCTRTRETRYCNT getSURCTRTRETRYCNT() {
        return surctrtretrycnt;
    }

    /**
     * Sets the value of the surctrtretrycnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCTRTRETRYCNT }
     *     
     */
    public void setSURCTRTRETRYCNT(SURCTRTRETRYCNT value) {
        this.surctrtretrycnt = value;
    }

    /**
     * Gets the value of the surctrtrdretrymaxintval property.
     * 
     * @return
     *     possible object is
     *     {@link SURCTRTRDRETRYMAXINTVAL }
     *     
     */
    public SURCTRTRDRETRYMAXINTVAL getSURCTRTRDRETRYMAXINTVAL() {
        return surctrtrdretrymaxintval;
    }

    /**
     * Sets the value of the surctrtrdretrymaxintval property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCTRTRDRETRYMAXINTVAL }
     *     
     */
    public void setSURCTRTRDRETRYMAXINTVAL(SURCTRTRDRETRYMAXINTVAL value) {
        this.surctrtrdretrymaxintval = value;
    }

    /**
     * Gets the value of the surctrtgrantintv property.
     * 
     * @return
     *     possible object is
     *     {@link SURCTRTGRANTINTV }
     *     
     */
    public SURCTRTGRANTINTV getSURCTRTGRANTINTV() {
        return surctrtgrantintv;
    }

    /**
     * Sets the value of the surctrtgrantintv property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCTRTGRANTINTV }
     *     
     */
    public void setSURCTRTGRANTINTV(SURCTRTGRANTINTV value) {
        this.surctrtgrantintv = value;
    }

    /**
     * Gets the value of the surcdatacapability property.
     * 
     * @return
     *     possible object is
     *     {@link SURCDATACAPABILITY }
     *     
     */
    public SURCDATACAPABILITY getSURCDATACAPABILITY() {
        return surcdatacapability;
    }

    /**
     * Sets the value of the surcdatacapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCDATACAPABILITY }
     *     
     */
    public void setSURCDATACAPABILITY(SURCDATACAPABILITY value) {
        this.surcdatacapability = value;
    }

    /**
     * Gets the value of the surcvoiceonly property.
     * 
     * @return
     *     possible object is
     *     {@link SURCVOICEONLY }
     *     
     */
    public SURCVOICEONLY getSURCVOICEONLY() {
        return surcvoiceonly;
    }

    /**
     * Sets the value of the surcvoiceonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCVOICEONLY }
     *     
     */
    public void setSURCVOICEONLY(SURCVOICEONLY value) {
        this.surcvoiceonly = value;
    }

    /**
     * Gets the value of the surcdeletealljobtickets property.
     * 
     * @return
     *     possible object is
     *     {@link SURCDELETEALLJOBTICKETS }
     *     
     */
    public SURCDELETEALLJOBTICKETS getSURCDELETEALLJOBTICKETS() {
        return surcdeletealljobtickets;
    }

    /**
     * Sets the value of the surcdeletealljobtickets property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCDELETEALLJOBTICKETS }
     *     
     */
    public void setSURCDELETEALLJOBTICKETS(SURCDELETEALLJOBTICKETS value) {
        this.surcdeletealljobtickets = value;
    }

    /**
     * Gets the value of the surcdeletealltextmessages property.
     * 
     * @return
     *     possible object is
     *     {@link SURCDELETEALLTEXTMESSAGES }
     *     
     */
    public SURCDELETEALLTEXTMESSAGES getSURCDELETEALLTEXTMESSAGES() {
        return surcdeletealltextmessages;
    }

    /**
     * Sets the value of the surcdeletealltextmessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCDELETEALLTEXTMESSAGES }
     *     
     */
    public void setSURCDELETEALLTEXTMESSAGES(SURCDELETEALLTEXTMESSAGES value) {
        this.surcdeletealltextmessages = value;
    }

    /**
     * Gets the value of the surctelrvtchl2ACKWTTMR property.
     * 
     * @return
     *     possible object is
     *     {@link SURCTELRVTCHL2ACKWTTMR }
     *     
     */
    public SURCTELRVTCHL2ACKWTTMR getSURCTELRVTCHL2ACKWTTMR() {
        return surctelrvtchl2ACKWTTMR;
    }

    /**
     * Sets the value of the surctelrvtchl2ACKWTTMR property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCTELRVTCHL2ACKWTTMR }
     *     
     */
    public void setSURCTELRVTCHL2ACKWTTMR(SURCTELRVTCHL2ACKWTTMR value) {
        this.surctelrvtchl2ACKWTTMR = value;
    }

    /**
     * Gets the value of the surcncat property.
     * 
     * @return
     *     possible object is
     *     {@link SURCNCAT }
     *     
     */
    public SURCNCAT getSURCNCAT() {
        return surcncat;
    }

    /**
     * Sets the value of the surcncat property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCNCAT }
     *     
     */
    public void setSURCNCAT(SURCNCAT value) {
        this.surcncat = value;
    }

    /**
     * Gets the value of the surcreserved property.
     * 
     * @return
     *     possible object is
     *     {@link SURCRESERVED }
     *     
     */
    public SURCRESERVED getSURCRESERVED() {
        return surcreserved;
    }

    /**
     * Sets the value of the surcreserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCRESERVED }
     *     
     */
    public void setSURCRESERVED(SURCRESERVED value) {
        this.surcreserved = value;
    }

    /**
     * Gets the value of the surcipsctrtgrantintv property.
     * 
     * @return
     *     possible object is
     *     {@link SURCIPSCTRTGRANTINTV }
     *     
     */
    public SURCIPSCTRTGRANTINTV getSURCIPSCTRTGRANTINTV() {
        return surcipsctrtgrantintv;
    }

    /**
     * Sets the value of the surcipsctrtgrantintv property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCIPSCTRTGRANTINTV }
     *     
     */
    public void setSURCIPSCTRTGRANTINTV(SURCIPSCTRTGRANTINTV value) {
        this.surcipsctrtgrantintv = value;
    }

    /**
     * Gets the value of the surcallowmandownusercontrol property.
     * 
     * @return
     *     possible object is
     *     {@link SURCALLOWMANDOWNUSERCONTROL }
     *     
     */
    public SURCALLOWMANDOWNUSERCONTROL getSURCALLOWMANDOWNUSERCONTROL() {
        return surcallowmandownusercontrol;
    }

    /**
     * Sets the value of the surcallowmandownusercontrol property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCALLOWMANDOWNUSERCONTROL }
     *     
     */
    public void setSURCALLOWMANDOWNUSERCONTROL(SURCALLOWMANDOWNUSERCONTROL value) {
        this.surcallowmandownusercontrol = value;
    }

    /**
     * Gets the value of the surcmandownstatus property.
     * 
     * @return
     *     possible object is
     *     {@link SURCMANDOWNSTATUS }
     *     
     */
    public SURCMANDOWNSTATUS getSURCMANDOWNSTATUS() {
        return surcmandownstatus;
    }

    /**
     * Sets the value of the surcmandownstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCMANDOWNSTATUS }
     *     
     */
    public void setSURCMANDOWNSTATUS(SURCMANDOWNSTATUS value) {
        this.surcmandownstatus = value;
    }

    /**
     * Gets the value of the surchwlsprsen property.
     * 
     * @return
     *     possible object is
     *     {@link SURCHWLSPRSEN }
     *     
     */
    public SURCHWLSPRSEN getSURCHWLSPRSEN() {
        return surchwlsprsen;
    }

    /**
     * Sets the value of the surchwlsprsen property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCHWLSPRSEN }
     *     
     */
    public void setSURCHWLSPRSEN(SURCHWLSPRSEN value) {
        this.surchwlsprsen = value;
    }

    /**
     * Gets the value of the surctxtmsgalttndur property.
     * 
     * @return
     *     possible object is
     *     {@link SURCTXTMSGALTTNDUR }
     *     
     */
    public SURCTXTMSGALTTNDUR getSURCTXTMSGALTTNDUR() {
        return surctxtmsgalttndur;
    }

    /**
     * Sets the value of the surctxtmsgalttndur property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCTXTMSGALTTNDUR }
     *     
     */
    public void setSURCTXTMSGALTTNDUR(SURCTXTMSGALTTNDUR value) {
        this.surctxtmsgalttndur = value;
    }

    /**
     * Gets the value of the surc625EDMBCNITV property.
     * 
     * @return
     *     possible object is
     *     {@link SURC625EDMBCNITV }
     *     
     */
    public SURC625EDMBCNITV getSURC625EDMBCNITV() {
        return surc625EDMBCNITV;
    }

    /**
     * Sets the value of the surc625EDMBCNITV property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURC625EDMBCNITV }
     *     
     */
    public void setSURC625EDMBCNITV(SURC625EDMBCNITV value) {
        this.surc625EDMBCNITV = value;
    }

    /**
     * Gets the value of the surc625EDMSAGINC property.
     * 
     * @return
     *     possible object is
     *     {@link SURC625EDMSAGINC }
     *     
     */
    public SURC625EDMSAGINC getSURC625EDMSAGINC() {
        return surc625EDMSAGINC;
    }

    /**
     * Sets the value of the surc625EDMSAGINC property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURC625EDMSAGINC }
     *     
     */
    public void setSURC625EDMSAGINC(SURC625EDMSAGINC value) {
        this.surc625EDMSAGINC = value;
    }

    /**
     * Gets the value of the surc625EDMDFSWD property.
     * 
     * @return
     *     possible object is
     *     {@link SURC625EDMDFSWD }
     *     
     */
    public SURC625EDMDFSWD getSURC625EDMDFSWD() {
        return surc625EDMDFSWD;
    }

    /**
     * Sets the value of the surc625EDMDFSWD property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURC625EDMDFSWD }
     *     
     */
    public void setSURC625EDMDFSWD(SURC625EDMDFSWD value) {
        this.surc625EDMDFSWD = value;
    }

    /**
     * Gets the value of the surc625EDMSAGTOT property.
     * 
     * @return
     *     possible object is
     *     {@link SURC625EDMSAGTOT }
     *     
     */
    public SURC625EDMSAGTOT getSURC625EDMSAGTOT() {
        return surc625EDMSAGTOT;
    }

    /**
     * Sets the value of the surc625EDMSAGTOT property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURC625EDMSAGTOT }
     *     
     */
    public void setSURC625EDMSAGTOT(SURC625EDMSAGTOT value) {
        this.surc625EDMSAGTOT = value;
    }

    /**
     * Gets the value of the surc625EDMBCNDUR property.
     * 
     * @return
     *     possible object is
     *     {@link SURC625EDMBCNDUR }
     *     
     */
    public SURC625EDMBCNDUR getSURC625EDMBCNDUR() {
        return surc625EDMBCNDUR;
    }

    /**
     * Sets the value of the surc625EDMBCNDUR property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURC625EDMBCNDUR }
     *     
     */
    public void setSURC625EDMBCNDUR(SURC625EDMBCNDUR value) {
        this.surc625EDMBCNDUR = value;
    }

    /**
     * Gets the value of the surc625ETTSPCLCD property.
     * 
     * @return
     *     possible object is
     *     {@link SURC625ETTSPCLCD }
     *     
     */
    public SURC625ETTSPCLCD getSURC625ETTSPCLCD() {
        return surc625ETTSPCLCD;
    }

    /**
     * Sets the value of the surc625ETTSPCLCD property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURC625ETTSPCLCD }
     *     
     */
    public void setSURC625ETTSPCLCD(SURC625ETTSPCLCD value) {
        this.surc625ETTSPCLCD = value;
    }

    /**
     * Gets the value of the surc625EMINSPCLCD property.
     * 
     * @return
     *     possible object is
     *     {@link SURC625EMINSPCLCD }
     *     
     */
    public SURC625EMINSPCLCD getSURC625EMINSPCLCD() {
        return surc625EMINSPCLCD;
    }

    /**
     * Sets the value of the surc625EMINSPCLCD property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURC625EMINSPCLCD }
     *     
     */
    public void setSURC625EMINSPCLCD(SURC625EMINSPCLCD value) {
        this.surc625EMINSPCLCD = value;
    }

    /**
     * Gets the value of the surcoacsucsbkacktimer property.
     * 
     * @return
     *     possible object is
     *     {@link SURCOACSUCSBKACKTIMER }
     *     
     */
    public SURCOACSUCSBKACKTIMER getSURCOACSUCSBKACKTIMER() {
        return surcoacsucsbkacktimer;
    }

    /**
     * Sets the value of the surcoacsucsbkacktimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCOACSUCSBKACKTIMER }
     *     
     */
    public void setSURCOACSUCSBKACKTIMER(SURCOACSUCSBKACKTIMER value) {
        this.surcoacsucsbkacktimer = value;
    }

    /**
     * Gets the value of the surcimeften property.
     * 
     * @return
     *     possible object is
     *     {@link SURCIMEFTEN }
     *     
     */
    public SURCIMEFTEN getSURCIMEFTEN() {
        return surcimeften;
    }

    /**
     * Sets the value of the surcimeften property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCIMEFTEN }
     *     
     */
    public void setSURCIMEFTEN(SURCIMEFTEN value) {
        this.surcimeften = value;
    }

    /**
     * Gets the value of the surcimeoptwdprdc property.
     * 
     * @return
     *     possible object is
     *     {@link SURCIMEOPTWDPRDC }
     *     
     */
    public SURCIMEOPTWDPRDC getSURCIMEOPTWDPRDC() {
        return surcimeoptwdprdc;
    }

    /**
     * Sets the value of the surcimeoptwdprdc property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCIMEOPTWDPRDC }
     *     
     */
    public void setSURCIMEOPTWDPRDC(SURCIMEOPTWDPRDC value) {
        this.surcimeoptwdprdc = value;
    }

    /**
     * Gets the value of the surcimeoptstwcpt property.
     * 
     * @return
     *     possible object is
     *     {@link SURCIMEOPTSTWCPT }
     *     
     */
    public SURCIMEOPTSTWCPT getSURCIMEOPTSTWCPT() {
        return surcimeoptstwcpt;
    }

    /**
     * Sets the value of the surcimeoptstwcpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCIMEOPTSTWCPT }
     *     
     */
    public void setSURCIMEOPTSTWCPT(SURCIMEOPTSTWCPT value) {
        this.surcimeoptstwcpt = value;
    }

    /**
     * Gets the value of the surcimeoptmulttp property.
     * 
     * @return
     *     possible object is
     *     {@link SURCIMEOPTMULTTP }
     *     
     */
    public SURCIMEOPTMULTTP getSURCIMEOPTMULTTP() {
        return surcimeoptmulttp;
    }

    /**
     * Sets the value of the surcimeoptmulttp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCIMEOPTMULTTP }
     *     
     */
    public void setSURCIMEOPTMULTTP(SURCIMEOPTMULTTP value) {
        this.surcimeoptmulttp = value;
    }

    /**
     * Gets the value of the surcimeoptcuript property.
     * 
     * @return
     *     possible object is
     *     {@link SURCIMEOPTCURIPT }
     *     
     */
    public SURCIMEOPTCURIPT getSURCIMEOPTCURIPT() {
        return surcimeoptcuript;
    }

    /**
     * Sets the value of the surcimeoptcuript property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCIMEOPTCURIPT }
     *     
     */
    public void setSURCIMEOPTCURIPT(SURCIMEOPTCURIPT value) {
        this.surcimeoptcuript = value;
    }

    /**
     * Gets the value of the surcimeoptnumlck property.
     * 
     * @return
     *     possible object is
     *     {@link SURCIMEOPTNUMLCK }
     *     
     */
    public SURCIMEOPTNUMLCK getSURCIMEOPTNUMLCK() {
        return surcimeoptnumlck;
    }

    /**
     * Sets the value of the surcimeoptnumlck property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCIMEOPTNUMLCK }
     *     
     */
    public void setSURCIMEOPTNUMLCK(SURCIMEOPTNUMLCK value) {
        this.surcimeoptnumlck = value;
    }

    /**
     * Gets the value of the surcimeoptkrnjn property.
     * 
     * @return
     *     possible object is
     *     {@link SURCIMEOPTKRNJN }
     *     
     */
    public SURCIMEOPTKRNJN getSURCIMEOPTKRNJN() {
        return surcimeoptkrnjn;
    }

    /**
     * Sets the value of the surcimeoptkrnjn property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCIMEOPTKRNJN }
     *     
     */
    public void setSURCIMEOPTKRNJN(SURCIMEOPTKRNJN value) {
        this.surcimeoptkrnjn = value;
    }

    /**
     * Gets the value of the surcimeoptwdcrct property.
     * 
     * @return
     *     possible object is
     *     {@link SURCIMEOPTWDCRCT }
     *     
     */
    public SURCIMEOPTWDCRCT getSURCIMEOPTWDCRCT() {
        return surcimeoptwdcrct;
    }

    /**
     * Sets the value of the surcimeoptwdcrct property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCIMEOPTWDCRCT }
     *     
     */
    public void setSURCIMEOPTWDCRCT(SURCIMEOPTWDCRCT value) {
        this.surcimeoptwdcrct = value;
    }

    /**
     * Gets the value of the surcimeoptcplk property.
     * 
     * @return
     *     possible object is
     *     {@link SURCIMEOPTCPLK }
     *     
     */
    public SURCIMEOPTCPLK getSURCIMEOPTCPLK() {
        return surcimeoptcplk;
    }

    /**
     * Sets the value of the surcimeoptcplk property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCIMEOPTCPLK }
     *     
     */
    public void setSURCIMEOPTCPLK(SURCIMEOPTCPLK value) {
        this.surcimeoptcplk = value;
    }

    /**
     * Gets the value of the surcuserenvironmentprofile property.
     * 
     * @return
     *     possible object is
     *     {@link SURCUSERENVIRONMENTPROFILE }
     *     
     */
    public SURCUSERENVIRONMENTPROFILE getSURCUSERENVIRONMENTPROFILE() {
        return surcuserenvironmentprofile;
    }

    /**
     * Sets the value of the surcuserenvironmentprofile property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCUSERENVIRONMENTPROFILE }
     *     
     */
    public void setSURCUSERENVIRONMENTPROFILE(SURCUSERENVIRONMENTPROFILE value) {
        this.surcuserenvironmentprofile = value;
    }

    /**
     * Gets the value of the surcartsadbidctp property.
     * 
     * @return
     *     possible object is
     *     {@link SURCARTSADBIDCTP }
     *     
     */
    public SURCARTSADBIDCTP getSURCARTSADBIDCTP() {
        return surcartsadbidctp;
    }

    /**
     * Sets the value of the surcartsadbidctp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCARTSADBIDCTP }
     *     
     */
    public void setSURCARTSADBIDCTP(SURCARTSADBIDCTP value) {
        this.surcartsadbidctp = value;
    }

    /**
     * Gets the value of the surcartsvsidcten property.
     * 
     * @return
     *     possible object is
     *     {@link SURCARTSVSIDCTEN }
     *     
     */
    public SURCARTSVSIDCTEN getSURCARTSVSIDCTEN() {
        return surcartsvsidcten;
    }

    /**
     * Sets the value of the surcartsvsidcten property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCARTSVSIDCTEN }
     *     
     */
    public void setSURCARTSVSIDCTEN(SURCARTSVSIDCTEN value) {
        this.surcartsvsidcten = value;
    }

    /**
     * Gets the value of the surclcprmathmtrh property.
     * 
     * @return
     *     possible object is
     *     {@link SURCLCPRMATHMTRH }
     *     
     */
    public SURCLCPRMATHMTRH getSURCLCPRMATHMTRH() {
        return surclcprmathmtrh;
    }

    /**
     * Sets the value of the surclcprmathmtrh property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCLCPRMATHMTRH }
     *     
     */
    public void setSURCLCPRMATHMTRH(SURCLCPRMATHMTRH value) {
        this.surclcprmathmtrh = value;
    }

    /**
     * Gets the value of the surcalttnfxvlm property.
     * 
     * @return
     *     possible object is
     *     {@link SURCALTTNFXVLM }
     *     
     */
    public SURCALTTNFXVLM getSURCALTTNFXVLM() {
        return surcalttnfxvlm;
    }

    /**
     * Sets the value of the surcalttnfxvlm property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCALTTNFXVLM }
     *     
     */
    public void setSURCALTTNFXVLM(SURCALTTNFXVLM value) {
        this.surcalttnfxvlm = value;
    }

    /**
     * Gets the value of the surcimeoptnedttm property.
     * 
     * @return
     *     possible object is
     *     {@link SURCIMEOPTNEDTTM }
     *     
     */
    public SURCIMEOPTNEDTTM getSURCIMEOPTNEDTTM() {
        return surcimeoptnedttm;
    }

    /**
     * Sets the value of the surcimeoptnedttm property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCIMEOPTNEDTTM }
     *     
     */
    public void setSURCIMEOPTNEDTTM(SURCIMEOPTNEDTTM value) {
        this.surcimeoptnedttm = value;
    }

    /**
     * Gets the value of the surctstmden property.
     * 
     * @return
     *     possible object is
     *     {@link SURCTSTMDEN }
     *     
     */
    public SURCTSTMDEN getSURCTSTMDEN() {
        return surctstmden;
    }

    /**
     * Sets the value of the surctstmden property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCTSTMDEN }
     *     
     */
    public void setSURCTSTMDEN(SURCTSTMDEN value) {
        this.surctstmden = value;
    }

    /**
     * Gets the value of the surcbtpermanentdiscoverableenable property.
     * 
     * @return
     *     possible object is
     *     {@link SURCBTPERMANENTDISCOVERABLEENABLE }
     *     
     */
    public SURCBTPERMANENTDISCOVERABLEENABLE getSURCBTPERMANENTDISCOVERABLEENABLE() {
        return surcbtpermanentdiscoverableenable;
    }

    /**
     * Sets the value of the surcbtpermanentdiscoverableenable property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCBTPERMANENTDISCOVERABLEENABLE }
     *     
     */
    public void setSURCBTPERMANENTDISCOVERABLEENABLE(SURCBTPERMANENTDISCOVERABLEENABLE value) {
        this.surcbtpermanentdiscoverableenable = value;
    }

    /**
     * Gets the value of the surcdeletealluserucl property.
     * 
     * @return
     *     possible object is
     *     {@link SURCDELETEALLUSERUCL }
     *     
     */
    public SURCDELETEALLUSERUCL getSURCDELETEALLUSERUCL() {
        return surcdeletealluserucl;
    }

    /**
     * Sets the value of the surcdeletealluserucl property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCDELETEALLUSERUCL }
     *     
     */
    public void setSURCDELETEALLUSERUCL(SURCDELETEALLUSERUCL value) {
        this.surcdeletealluserucl = value;
    }

    /**
     * Gets the value of the surcdeleteallcalllog property.
     * 
     * @return
     *     possible object is
     *     {@link SURCDELETEALLCALLLOG }
     *     
     */
    public SURCDELETEALLCALLLOG getSURCDELETEALLCALLLOG() {
        return surcdeleteallcalllog;
    }

    /**
     * Sets the value of the surcdeleteallcalllog property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCDELETEALLCALLLOG }
     *     
     */
    public void setSURCDELETEALLCALLLOG(SURCDELETEALLCALLLOG value) {
        this.surcdeleteallcalllog = value;
    }

    /**
     * Gets the value of the surclogincapability property.
     * 
     * @return
     *     possible object is
     *     {@link SURCLOGINCAPABILITY }
     *     
     */
    public SURCLOGINCAPABILITY getSURCLOGINCAPABILITY() {
        return surclogincapability;
    }

    /**
     * Sets the value of the surclogincapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCLOGINCAPABILITY }
     *     
     */
    public void setSURCLOGINCAPABILITY(SURCLOGINCAPABILITY value) {
        this.surclogincapability = value;
    }

    /**
     * Gets the value of the surcdeleteoptionboarduniqueidentifier property.
     * 
     * @return
     *     possible object is
     *     {@link SURCDELETEOPTIONBOARDUNIQUEIDENTIFIER }
     *     
     */
    public SURCDELETEOPTIONBOARDUNIQUEIDENTIFIER getSURCDELETEOPTIONBOARDUNIQUEIDENTIFIER() {
        return surcdeleteoptionboarduniqueidentifier;
    }

    /**
     * Sets the value of the surcdeleteoptionboarduniqueidentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCDELETEOPTIONBOARDUNIQUEIDENTIFIER }
     *     
     */
    public void setSURCDELETEOPTIONBOARDUNIQUEIDENTIFIER(SURCDELETEOPTIONBOARDUNIQUEIDENTIFIER value) {
        this.surcdeleteoptionboarduniqueidentifier = value;
    }

    /**
     * Gets the value of the surcchannelindexenable property.
     * 
     * @return
     *     possible object is
     *     {@link SURCCHANNELINDEXENABLE }
     *     
     */
    public SURCCHANNELINDEXENABLE getSURCCHANNELINDEXENABLE() {
        return surcchannelindexenable;
    }

    /**
     * Sets the value of the surcchannelindexenable property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCCHANNELINDEXENABLE }
     *     
     */
    public void setSURCCHANNELINDEXENABLE(SURCCHANNELINDEXENABLE value) {
        this.surcchannelindexenable = value;
    }

    /**
     * Gets the value of the surcsecuresigninid property.
     * 
     * @return
     *     possible object is
     *     {@link SURCSECURESIGNINID }
     *     
     */
    public SURCSECURESIGNINID getSURCSECURESIGNINID() {
        return surcsecuresigninid;
    }

    /**
     * Sets the value of the surcsecuresigninid property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCSECURESIGNINID }
     *     
     */
    public void setSURCSECURESIGNINID(SURCSECURESIGNINID value) {
        this.surcsecuresigninid = value;
    }

    /**
     * Gets the value of the surcprohibittoneoninterrupt property.
     * 
     * @return
     *     possible object is
     *     {@link SURCPROHIBITTONEONINTERRUPT }
     *     
     */
    public SURCPROHIBITTONEONINTERRUPT getSURCPROHIBITTONEONINTERRUPT() {
        return surcprohibittoneoninterrupt;
    }

    /**
     * Sets the value of the surcprohibittoneoninterrupt property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCPROHIBITTONEONINTERRUPT }
     *     
     */
    public void setSURCPROHIBITTONEONINTERRUPT(SURCPROHIBITTONEONINTERRUPT value) {
        this.surcprohibittoneoninterrupt = value;
    }

    /**
     * Gets the value of the surcuserpreferenceprofile property.
     * 
     * @return
     *     possible object is
     *     {@link SURCUSERPREFERENCEPROFILE }
     *     
     */
    public SURCUSERPREFERENCEPROFILE getSURCUSERPREFERENCEPROFILE() {
        return surcuserpreferenceprofile;
    }

    /**
     * Sets the value of the surcuserpreferenceprofile property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCUSERPREFERENCEPROFILE }
     *     
     */
    public void setSURCUSERPREFERENCEPROFILE(SURCUSERPREFERENCEPROFILE value) {
        this.surcuserpreferenceprofile = value;
    }

    /**
     * Gets the value of the surcrmnathmthrh property.
     * 
     * @return
     *     possible object is
     *     {@link SURCRMNATHMTHRH }
     *     
     */
    public SURCRMNATHMTHRH getSURCRMNATHMTHRH() {
        return surcrmnathmthrh;
    }

    /**
     * Sets the value of the surcrmnathmthrh property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCRMNATHMTHRH }
     *     
     */
    public void setSURCRMNATHMTHRH(SURCRMNATHMTHRH value) {
        this.surcrmnathmthrh = value;
    }

    /**
     * Gets the value of the surcccbihbqkky property.
     * 
     * @return
     *     possible object is
     *     {@link SURCCCBIHBQKKY }
     *     
     */
    public SURCCCBIHBQKKY getSURCCCBIHBQKKY() {
        return surcccbihbqkky;
    }

    /**
     * Sets the value of the surcccbihbqkky property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCCCBIHBQKKY }
     *     
     */
    public void setSURCCCBIHBQKKY(SURCCCBIHBQKKY value) {
        this.surcccbihbqkky = value;
    }

    /**
     * Gets the value of the surclcprmbcintvl property.
     * 
     * @return
     *     possible object is
     *     {@link SURCLCPRMBCINTVL }
     *     
     */
    public SURCLCPRMBCINTVL getSURCLCPRMBCINTVL() {
        return surclcprmbcintvl;
    }

    /**
     * Sets the value of the surclcprmbcintvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCLCPRMBCINTVL }
     *     
     */
    public void setSURCLCPRMBCINTVL(SURCLCPRMBCINTVL value) {
        this.surclcprmbcintvl = value;
    }

    /**
     * Gets the value of the surc625EDMGNRSUID property.
     * 
     * @return
     *     possible object is
     *     {@link SURC625EDMGNRSUID }
     *     
     */
    public SURC625EDMGNRSUID getSURC625EDMGNRSUID() {
        return surc625EDMGNRSUID;
    }

    /**
     * Sets the value of the surc625EDMGNRSUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURC625EDMGNRSUID }
     *     
     */
    public void setSURC625EDMGNRSUID(SURC625EDMGNRSUID value) {
        this.surc625EDMGNRSUID = value;
    }

    /**
     * Gets the value of the surcbsmwaaen property.
     * 
     * @return
     *     possible object is
     *     {@link SURCBSMWAAEN }
     *     
     */
    public SURCBSMWAAEN getSURCBSMWAAEN() {
        return surcbsmwaaen;
    }

    /**
     * Sets the value of the surcbsmwaaen property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCBSMWAAEN }
     *     
     */
    public void setSURCBSMWAAEN(SURCBSMWAAEN value) {
        this.surcbsmwaaen = value;
    }

    /**
     * Gets the value of the surcphtsatbrt property.
     * 
     * @return
     *     possible object is
     *     {@link SURCPHTSATBRT }
     *     
     */
    public SURCPHTSATBRT getSURCPHTSATBRT() {
        return surcphtsatbrt;
    }

    /**
     * Sets the value of the surcphtsatbrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCPHTSATBRT }
     *     
     */
    public void setSURCPHTSATBRT(SURCPHTSATBRT value) {
        this.surcphtsatbrt = value;
    }

    /**
     * Gets the value of the surcvbalttype property.
     * 
     * @return
     *     possible object is
     *     {@link SURCVBALTTYPE }
     *     
     */
    public SURCVBALTTYPE getSURCVBALTTYPE() {
        return surcvbalttype;
    }

    /**
     * Sets the value of the surcvbalttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCVBALTTYPE }
     *     
     */
    public void setSURCVBALTTYPE(SURCVBALTTYPE value) {
        this.surcvbalttype = value;
    }

    /**
     * Gets the value of the surcbattchargmode property.
     * 
     * @return
     *     possible object is
     *     {@link SURCBATTCHARGMODE }
     *     
     */
    public SURCBATTCHARGMODE getSURCBATTCHARGMODE() {
        return surcbattchargmode;
    }

    /**
     * Sets the value of the surcbattchargmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCBATTCHARGMODE }
     *     
     */
    public void setSURCBATTCHARGMODE(SURCBATTCHARGMODE value) {
        this.surcbattchargmode = value;
    }

    /**
     * Gets the value of the surcanalogvoicescramblingcode property.
     * 
     * @return
     *     possible object is
     *     {@link SURCANALOGVOICESCRAMBLINGCODE }
     *     
     */
    public SURCANALOGVOICESCRAMBLINGCODE getSURCANALOGVOICESCRAMBLINGCODE() {
        return surcanalogvoicescramblingcode;
    }

    /**
     * Sets the value of the surcanalogvoicescramblingcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCANALOGVOICESCRAMBLINGCODE }
     *     
     */
    public void setSURCANALOGVOICESCRAMBLINGCODE(SURCANALOGVOICESCRAMBLINGCODE value) {
        this.surcanalogvoicescramblingcode = value;
    }

    /**
     * Gets the value of the surcntbrtthr property.
     * 
     * @return
     *     possible object is
     *     {@link SURCNTBRTTHR }
     *     
     */
    public SURCNTBRTTHR getSURCNTBRTTHR() {
        return surcntbrtthr;
    }

    /**
     * Sets the value of the surcntbrtthr property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCNTBRTTHR }
     *     
     */
    public void setSURCNTBRTTHR(SURCNTBRTTHR value) {
        this.surcntbrtthr = value;
    }

    /**
     * Gets the value of the surcdybrtthr property.
     * 
     * @return
     *     possible object is
     *     {@link SURCDYBRTTHR }
     *     
     */
    public SURCDYBRTTHR getSURCDYBRTTHR() {
        return surcdybrtthr;
    }

    /**
     * Sets the value of the surcdybrtthr property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCDYBRTTHR }
     *     
     */
    public void setSURCDYBRTTHR(SURCDYBRTTHR value) {
        this.surcdybrtthr = value;
    }

    /**
     * Gets the value of the surc3PDYBRTLOWTHR property.
     * 
     * @return
     *     possible object is
     *     {@link SURC3PDYBRTLOWTHR }
     *     
     */
    public SURC3PDYBRTLOWTHR getSURC3PDYBRTLOWTHR() {
        return surc3PDYBRTLOWTHR;
    }

    /**
     * Sets the value of the surc3PDYBRTLOWTHR property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURC3PDYBRTLOWTHR }
     *     
     */
    public void setSURC3PDYBRTLOWTHR(SURC3PDYBRTLOWTHR value) {
        this.surc3PDYBRTLOWTHR = value;
    }

    /**
     * Gets the value of the surcwpflpath property.
     * 
     * @return
     *     possible object is
     *     {@link SURCWPFLPATH }
     *     
     */
    public SURCWPFLPATH getSURCWPFLPATH() {
        return surcwpflpath;
    }

    /**
     * Sets the value of the surcwpflpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCWPFLPATH }
     *     
     */
    public void setSURCWPFLPATH(SURCWPFLPATH value) {
        this.surcwpflpath = value;
    }

    /**
     * Gets the value of the surcwpflname property.
     * 
     * @return
     *     possible object is
     *     {@link SURCWPFLNAME }
     *     
     */
    public SURCWPFLNAME getSURCWPFLNAME() {
        return surcwpflname;
    }

    /**
     * Sets the value of the surcwpflname property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCWPFLNAME }
     *     
     */
    public void setSURCWPFLNAME(SURCWPFLNAME value) {
        this.surcwpflname = value;
    }

    /**
     * Gets the value of the surc3PDYBRTHIGHTHR property.
     * 
     * @return
     *     possible object is
     *     {@link SURC3PDYBRTHIGHTHR }
     *     
     */
    public SURC3PDYBRTHIGHTHR getSURC3PDYBRTHIGHTHR() {
        return surc3PDYBRTHIGHTHR;
    }

    /**
     * Sets the value of the surc3PDYBRTHIGHTHR property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURC3PDYBRTHIGHTHR }
     *     
     */
    public void setSURC3PDYBRTHIGHTHR(SURC3PDYBRTHIGHTHR value) {
        this.surc3PDYBRTHIGHTHR = value;
    }

    /**
     * Gets the value of the surc3PNTBRTLOWTHR property.
     * 
     * @return
     *     possible object is
     *     {@link SURC3PNTBRTLOWTHR }
     *     
     */
    public SURC3PNTBRTLOWTHR getSURC3PNTBRTLOWTHR() {
        return surc3PNTBRTLOWTHR;
    }

    /**
     * Sets the value of the surc3PNTBRTLOWTHR property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURC3PNTBRTLOWTHR }
     *     
     */
    public void setSURC3PNTBRTLOWTHR(SURC3PNTBRTLOWTHR value) {
        this.surc3PNTBRTLOWTHR = value;
    }

    /**
     * Gets the value of the surc3PNTBRTHIGHTHR property.
     * 
     * @return
     *     possible object is
     *     {@link SURC3PNTBRTHIGHTHR }
     *     
     */
    public SURC3PNTBRTHIGHTHR getSURC3PNTBRTHIGHTHR() {
        return surc3PNTBRTHIGHTHR;
    }

    /**
     * Sets the value of the surc3PNTBRTHIGHTHR property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURC3PNTBRTHIGHTHR }
     *     
     */
    public void setSURC3PNTBRTHIGHTHR(SURC3PNTBRTHIGHTHR value) {
        this.surc3PNTBRTHIGHTHR = value;
    }

    /**
     * Gets the value of the surcemergencyalarmtoneduration property.
     * 
     * @return
     *     possible object is
     *     {@link SURCEMERGENCYALARMTONEDURATION }
     *     
     */
    public SURCEMERGENCYALARMTONEDURATION getSURCEMERGENCYALARMTONEDURATION() {
        return surcemergencyalarmtoneduration;
    }

    /**
     * Sets the value of the surcemergencyalarmtoneduration property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCEMERGENCYALARMTONEDURATION }
     *     
     */
    public void setSURCEMERGENCYALARMTONEDURATION(SURCEMERGENCYALARMTONEDURATION value) {
        this.surcemergencyalarmtoneduration = value;
    }

    /**
     * Gets the value of the surcatkpdlcken property.
     * 
     * @return
     *     possible object is
     *     {@link SURCATKPDLCKEN }
     *     
     */
    public SURCATKPDLCKEN getSURCATKPDLCKEN() {
        return surcatkpdlcken;
    }

    /**
     * Sets the value of the surcatkpdlcken property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCATKPDLCKEN }
     *     
     */
    public void setSURCATKPDLCKEN(SURCATKPDLCKEN value) {
        this.surcatkpdlcken = value;
    }

    /**
     * Gets the value of the surcemergencymodeledenable property.
     * 
     * @return
     *     possible object is
     *     {@link SURCEMERGENCYMODELEDENABLE }
     *     
     */
    public SURCEMERGENCYMODELEDENABLE getSURCEMERGENCYMODELEDENABLE() {
        return surcemergencymodeledenable;
    }

    /**
     * Sets the value of the surcemergencymodeledenable property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCEMERGENCYMODELEDENABLE }
     *     
     */
    public void setSURCEMERGENCYMODELEDENABLE(SURCEMERGENCYMODELEDENABLE value) {
        this.surcemergencymodeledenable = value;
    }

    /**
     * Gets the value of the surchwlsprssnstv property.
     * 
     * @return
     *     possible object is
     *     {@link SURCHWLSPRSSNSTV }
     *     
     */
    public SURCHWLSPRSSNSTV getSURCHWLSPRSSNSTV() {
        return surchwlsprssnstv;
    }

    /**
     * Sets the value of the surchwlsprssnstv property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCHWLSPRSSNSTV }
     *     
     */
    public void setSURCHWLSPRSSNSTV(SURCHWLSPRSSNSTV value) {
        this.surchwlsprssnstv = value;
    }

    /**
     * Gets the value of the surcminentrynumforchsearch property.
     * 
     * @return
     *     possible object is
     *     {@link SURCMINENTRYNUMFORCHSEARCH }
     *     
     */
    public SURCMINENTRYNUMFORCHSEARCH getSURCMINENTRYNUMFORCHSEARCH() {
        return surcminentrynumforchsearch;
    }

    /**
     * Sets the value of the surcminentrynumforchsearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCMINENTRYNUMFORCHSEARCH }
     *     
     */
    public void setSURCMINENTRYNUMFORCHSEARCH(SURCMINENTRYNUMFORCHSEARCH value) {
        this.surcminentrynumforchsearch = value;
    }

    /**
     * Gets the value of the surcminentrynumfornonchsearch property.
     * 
     * @return
     *     possible object is
     *     {@link SURCMINENTRYNUMFORNONCHSEARCH }
     *     
     */
    public SURCMINENTRYNUMFORNONCHSEARCH getSURCMINENTRYNUMFORNONCHSEARCH() {
        return surcminentrynumfornonchsearch;
    }

    /**
     * Sets the value of the surcminentrynumfornonchsearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCMINENTRYNUMFORNONCHSEARCH }
     *     
     */
    public void setSURCMINENTRYNUMFORNONCHSEARCH(SURCMINENTRYNUMFORNONCHSEARCH value) {
        this.surcminentrynumfornonchsearch = value;
    }

    /**
     * Gets the value of the surcloginacksession property.
     * 
     * @return
     *     possible object is
     *     {@link SURCLOGINACKSESSION }
     *     
     */
    public SURCLOGINACKSESSION getSURCLOGINACKSESSION() {
        return surcloginacksession;
    }

    /**
     * Sets the value of the surcloginacksession property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCLOGINACKSESSION }
     *     
     */
    public void setSURCLOGINACKSESSION(SURCLOGINACKSESSION value) {
        this.surcloginacksession = value;
    }

    /**
     * Gets the value of the surcloginid property.
     * 
     * @return
     *     possible object is
     *     {@link SURCLOGINID }
     *     
     */
    public SURCLOGINID getSURCLOGINID() {
        return surcloginid;
    }

    /**
     * Sets the value of the surcloginid property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCLOGINID }
     *     
     */
    public void setSURCLOGINID(SURCLOGINID value) {
        this.surcloginid = value;
    }

    /**
     * Gets the value of the surcemergencysearchtonevolume property.
     * 
     * @return
     *     possible object is
     *     {@link SURCEMERGENCYSEARCHTONEVOLUME }
     *     
     */
    public SURCEMERGENCYSEARCHTONEVOLUME getSURCEMERGENCYSEARCHTONEVOLUME() {
        return surcemergencysearchtonevolume;
    }

    /**
     * Sets the value of the surcemergencysearchtonevolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCEMERGENCYSEARCHTONEVOLUME }
     *     
     */
    public void setSURCEMERGENCYSEARCHTONEVOLUME(SURCEMERGENCYSEARCHTONEVOLUME value) {
        this.surcemergencysearchtonevolume = value;
    }

    /**
     * Gets the value of the surcemergencysearchtonecontrol property.
     * 
     * @return
     *     possible object is
     *     {@link SURCEMERGENCYSEARCHTONECONTROL }
     *     
     */
    public SURCEMERGENCYSEARCHTONECONTROL getSURCEMERGENCYSEARCHTONECONTROL() {
        return surcemergencysearchtonecontrol;
    }

    /**
     * Sets the value of the surcemergencysearchtonecontrol property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCEMERGENCYSEARCHTONECONTROL }
     *     
     */
    public void setSURCEMERGENCYSEARCHTONECONTROL(SURCEMERGENCYSEARCHTONECONTROL value) {
        this.surcemergencysearchtonecontrol = value;
    }

    /**
     * Gets the value of the surcemergencysearchtonespeakerselect property.
     * 
     * @return
     *     possible object is
     *     {@link SURCEMERGENCYSEARCHTONESPEAKERSELECT }
     *     
     */
    public SURCEMERGENCYSEARCHTONESPEAKERSELECT getSURCEMERGENCYSEARCHTONESPEAKERSELECT() {
        return surcemergencysearchtonespeakerselect;
    }

    /**
     * Sets the value of the surcemergencysearchtonespeakerselect property.
     * 
     * @param value
     *     allowed object is
     *     {@link SURCEMERGENCYSEARCHTONESPEAKERSELECT }
     *     
     */
    public void setSURCEMERGENCYSEARCHTONESPEAKERSELECT(SURCEMERGENCYSEARCHTONESPEAKERSELECT value) {
        this.surcemergencysearchtonespeakerselect = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

}
