//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.02.07 at 05:56:42 PM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ZN_PER_ASGN_DLT_TYPE" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "znperasgndlttype"
})
@XmlRootElement(name = "ZN_PER_ASGN_DLH_TYPE_GRP")
public class ZNPERASGNDLHTYPEGRP {

    @XmlElement(name = "ZN_PER_ASGN_DLT_TYPE", required = true)
    protected List<ZNPERASGNDLTTYPE> znperasgndlttype;

    /**
     * Gets the value of the znperasgndlttype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the znperasgndlttype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZNPERASGNDLTTYPE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ZNPERASGNDLTTYPE }
     * 
     * 
     */
    public List<ZNPERASGNDLTTYPE> getZNPERASGNDLTTYPE() {
        if (znperasgndlttype == null) {
            znperasgndlttype = new ArrayList<ZNPERASGNDLTTYPE>();
        }
        return this.znperasgndlttype;
    }

}
