//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:46:48 AM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}GPS_PERUPDINTERVAL"/>
 *         &lt;element ref="{}GPS_GPSEN"/>
 *         &lt;element ref="{}GPS_GPSBITCHK"/>
 *         &lt;element ref="{}GPS_LOCUPDDEST3"/>
 *         &lt;element ref="{}GPS_LOCUPDDEST2"/>
 *         &lt;element ref="{}GPS_LOCUPDDEST1"/>
 *         &lt;element ref="{}GPS_LOCUPDDEST0"/>
 *         &lt;element ref="{}GPS_LOCUPDDEST"/>
 *         &lt;element ref="{}GPS_WAITFORACKTMR"/>
 *         &lt;element ref="{}GPS_RDTHOT"/>
 *         &lt;element ref="{}GPSMSG_RHOT"/>
 *         &lt;element ref="{}GPS_GPSSTATE"/>
 *         &lt;element ref="{}GPS_LOCATIONSERVICECHIPSET"/>
 *         &lt;element ref="{}GPS_LOCATIONREPEATERLATITUDE"/>
 *         &lt;element ref="{}GPS_LOCATIONREPEATERLONGITUDE"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gpsperupdinterval",
    "gpsgpsen",
    "gpsgpsbitchk",
    "gpslocupddest3",
    "gpslocupddest2",
    "gpslocupddest1",
    "gpslocupddest0",
    "gpslocupddest",
    "gpswaitforacktmr",
    "gpsrdthot",
    "gpsmsgrhot",
    "gpsgpsstate",
    "gpslocationservicechipset",
    "gpslocationrepeaterlatitude",
    "gpslocationrepeaterlongitude"
})
@XmlRootElement(name = "GPS_CONFIG_CMP_TYPE")
public class GPSCONFIGCMPTYPE {

    @XmlElement(name = "GPS_PERUPDINTERVAL", required = true)
    protected GPSPERUPDINTERVAL gpsperupdinterval;
    @XmlElement(name = "GPS_GPSEN", required = true)
    protected GPSGPSEN gpsgpsen;
    @XmlElement(name = "GPS_GPSBITCHK", required = true)
    protected GPSGPSBITCHK gpsgpsbitchk;
    @XmlElement(name = "GPS_LOCUPDDEST3", required = true)
    protected GPSLOCUPDDEST3 gpslocupddest3;
    @XmlElement(name = "GPS_LOCUPDDEST2", required = true)
    protected GPSLOCUPDDEST2 gpslocupddest2;
    @XmlElement(name = "GPS_LOCUPDDEST1", required = true)
    protected GPSLOCUPDDEST1 gpslocupddest1;
    @XmlElement(name = "GPS_LOCUPDDEST0", required = true)
    protected GPSLOCUPDDEST0 gpslocupddest0;
    @XmlElement(name = "GPS_LOCUPDDEST", required = true)
    protected GPSLOCUPDDEST gpslocupddest;
    @XmlElement(name = "GPS_WAITFORACKTMR", required = true)
    protected GPSWAITFORACKTMR gpswaitforacktmr;
    @XmlElement(name = "GPS_RDTHOT", required = true)
    protected GPSRDTHOT gpsrdthot;
    @XmlElement(name = "GPSMSG_RHOT", required = true)
    protected GPSMSGRHOT gpsmsgrhot;
    @XmlElement(name = "GPS_GPSSTATE", required = true)
    protected GPSGPSSTATE gpsgpsstate;
    @XmlElement(name = "GPS_LOCATIONSERVICECHIPSET", required = true)
    protected GPSLOCATIONSERVICECHIPSET gpslocationservicechipset;
    @XmlElement(name = "GPS_LOCATIONREPEATERLATITUDE", required = true)
    protected GPSLOCATIONREPEATERLATITUDE gpslocationrepeaterlatitude;
    @XmlElement(name = "GPS_LOCATIONREPEATERLONGITUDE", required = true)
    protected GPSLOCATIONREPEATERLONGITUDE gpslocationrepeaterlongitude;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;

    /**
     * Gets the value of the gpsperupdinterval property.
     * 
     * @return
     *     possible object is
     *     {@link GPSPERUPDINTERVAL }
     *     
     */
    public GPSPERUPDINTERVAL getGPSPERUPDINTERVAL() {
        return gpsperupdinterval;
    }

    /**
     * Sets the value of the gpsperupdinterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSPERUPDINTERVAL }
     *     
     */
    public void setGPSPERUPDINTERVAL(GPSPERUPDINTERVAL value) {
        this.gpsperupdinterval = value;
    }

    /**
     * Gets the value of the gpsgpsen property.
     * 
     * @return
     *     possible object is
     *     {@link GPSGPSEN }
     *     
     */
    public GPSGPSEN getGPSGPSEN() {
        return gpsgpsen;
    }

    /**
     * Sets the value of the gpsgpsen property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSGPSEN }
     *     
     */
    public void setGPSGPSEN(GPSGPSEN value) {
        this.gpsgpsen = value;
    }

    /**
     * Gets the value of the gpsgpsbitchk property.
     * 
     * @return
     *     possible object is
     *     {@link GPSGPSBITCHK }
     *     
     */
    public GPSGPSBITCHK getGPSGPSBITCHK() {
        return gpsgpsbitchk;
    }

    /**
     * Sets the value of the gpsgpsbitchk property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSGPSBITCHK }
     *     
     */
    public void setGPSGPSBITCHK(GPSGPSBITCHK value) {
        this.gpsgpsbitchk = value;
    }

    /**
     * Gets the value of the gpslocupddest3 property.
     * 
     * @return
     *     possible object is
     *     {@link GPSLOCUPDDEST3 }
     *     
     */
    public GPSLOCUPDDEST3 getGPSLOCUPDDEST3() {
        return gpslocupddest3;
    }

    /**
     * Sets the value of the gpslocupddest3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSLOCUPDDEST3 }
     *     
     */
    public void setGPSLOCUPDDEST3(GPSLOCUPDDEST3 value) {
        this.gpslocupddest3 = value;
    }

    /**
     * Gets the value of the gpslocupddest2 property.
     * 
     * @return
     *     possible object is
     *     {@link GPSLOCUPDDEST2 }
     *     
     */
    public GPSLOCUPDDEST2 getGPSLOCUPDDEST2() {
        return gpslocupddest2;
    }

    /**
     * Sets the value of the gpslocupddest2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSLOCUPDDEST2 }
     *     
     */
    public void setGPSLOCUPDDEST2(GPSLOCUPDDEST2 value) {
        this.gpslocupddest2 = value;
    }

    /**
     * Gets the value of the gpslocupddest1 property.
     * 
     * @return
     *     possible object is
     *     {@link GPSLOCUPDDEST1 }
     *     
     */
    public GPSLOCUPDDEST1 getGPSLOCUPDDEST1() {
        return gpslocupddest1;
    }

    /**
     * Sets the value of the gpslocupddest1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSLOCUPDDEST1 }
     *     
     */
    public void setGPSLOCUPDDEST1(GPSLOCUPDDEST1 value) {
        this.gpslocupddest1 = value;
    }

    /**
     * Gets the value of the gpslocupddest0 property.
     * 
     * @return
     *     possible object is
     *     {@link GPSLOCUPDDEST0 }
     *     
     */
    public GPSLOCUPDDEST0 getGPSLOCUPDDEST0() {
        return gpslocupddest0;
    }

    /**
     * Sets the value of the gpslocupddest0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSLOCUPDDEST0 }
     *     
     */
    public void setGPSLOCUPDDEST0(GPSLOCUPDDEST0 value) {
        this.gpslocupddest0 = value;
    }

    /**
     * Gets the value of the gpslocupddest property.
     * 
     * @return
     *     possible object is
     *     {@link GPSLOCUPDDEST }
     *     
     */
    public GPSLOCUPDDEST getGPSLOCUPDDEST() {
        return gpslocupddest;
    }

    /**
     * Sets the value of the gpslocupddest property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSLOCUPDDEST }
     *     
     */
    public void setGPSLOCUPDDEST(GPSLOCUPDDEST value) {
        this.gpslocupddest = value;
    }

    /**
     * Gets the value of the gpswaitforacktmr property.
     * 
     * @return
     *     possible object is
     *     {@link GPSWAITFORACKTMR }
     *     
     */
    public GPSWAITFORACKTMR getGPSWAITFORACKTMR() {
        return gpswaitforacktmr;
    }

    /**
     * Sets the value of the gpswaitforacktmr property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSWAITFORACKTMR }
     *     
     */
    public void setGPSWAITFORACKTMR(GPSWAITFORACKTMR value) {
        this.gpswaitforacktmr = value;
    }

    /**
     * Gets the value of the gpsrdthot property.
     * 
     * @return
     *     possible object is
     *     {@link GPSRDTHOT }
     *     
     */
    public GPSRDTHOT getGPSRDTHOT() {
        return gpsrdthot;
    }

    /**
     * Sets the value of the gpsrdthot property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSRDTHOT }
     *     
     */
    public void setGPSRDTHOT(GPSRDTHOT value) {
        this.gpsrdthot = value;
    }

    /**
     * Gets the value of the gpsmsgrhot property.
     * 
     * @return
     *     possible object is
     *     {@link GPSMSGRHOT }
     *     
     */
    public GPSMSGRHOT getGPSMSGRHOT() {
        return gpsmsgrhot;
    }

    /**
     * Sets the value of the gpsmsgrhot property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSMSGRHOT }
     *     
     */
    public void setGPSMSGRHOT(GPSMSGRHOT value) {
        this.gpsmsgrhot = value;
    }

    /**
     * Gets the value of the gpsgpsstate property.
     * 
     * @return
     *     possible object is
     *     {@link GPSGPSSTATE }
     *     
     */
    public GPSGPSSTATE getGPSGPSSTATE() {
        return gpsgpsstate;
    }

    /**
     * Sets the value of the gpsgpsstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSGPSSTATE }
     *     
     */
    public void setGPSGPSSTATE(GPSGPSSTATE value) {
        this.gpsgpsstate = value;
    }

    /**
     * Gets the value of the gpslocationservicechipset property.
     * 
     * @return
     *     possible object is
     *     {@link GPSLOCATIONSERVICECHIPSET }
     *     
     */
    public GPSLOCATIONSERVICECHIPSET getGPSLOCATIONSERVICECHIPSET() {
        return gpslocationservicechipset;
    }

    /**
     * Sets the value of the gpslocationservicechipset property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSLOCATIONSERVICECHIPSET }
     *     
     */
    public void setGPSLOCATIONSERVICECHIPSET(GPSLOCATIONSERVICECHIPSET value) {
        this.gpslocationservicechipset = value;
    }

    /**
     * Gets the value of the gpslocationrepeaterlatitude property.
     * 
     * @return
     *     possible object is
     *     {@link GPSLOCATIONREPEATERLATITUDE }
     *     
     */
    public GPSLOCATIONREPEATERLATITUDE getGPSLOCATIONREPEATERLATITUDE() {
        return gpslocationrepeaterlatitude;
    }

    /**
     * Sets the value of the gpslocationrepeaterlatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSLOCATIONREPEATERLATITUDE }
     *     
     */
    public void setGPSLOCATIONREPEATERLATITUDE(GPSLOCATIONREPEATERLATITUDE value) {
        this.gpslocationrepeaterlatitude = value;
    }

    /**
     * Gets the value of the gpslocationrepeaterlongitude property.
     * 
     * @return
     *     possible object is
     *     {@link GPSLOCATIONREPEATERLONGITUDE }
     *     
     */
    public GPSLOCATIONREPEATERLONGITUDE getGPSLOCATIONREPEATERLONGITUDE() {
        return gpslocationrepeaterlongitude;
    }

    /**
     * Sets the value of the gpslocationrepeaterlongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link GPSLOCATIONREPEATERLONGITUDE }
     *     
     */
    public void setGPSLOCATIONREPEATERLONGITUDE(GPSLOCATIONREPEATERLONGITUDE value) {
        this.gpslocationrepeaterlongitude = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

}
