//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.30 at 11:46:48 AM GMT 
//


package cafe.deadbeef._2e1hnk.mototools.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}S5DECSTSLDLH_LC"/>
 *         &lt;element ref="{}S5DECSTSLDLH_LEDSZ"/>
 *         &lt;element ref="{}SLT_5_DECODER_STATUS_DLH_LEQMAX"/>
 *         &lt;element ref="{}S5DECSTSLDLH_LLEQMAX"/>
 *         &lt;element ref="{}SLT_5_DECODER_STATUS_DLH_TYPE_FTLLISHTYPE"/>
 *         &lt;element ref="{}SLT_5_DECODER_STATUS_DLH_TYPE_FTLLISHID"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Applicable" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="ListID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "s5DECSTSLDLHLC",
    "s5DECSTSLDLHLEDSZ",
    "slt5DECODERSTATUSDLHLEQMAX",
    "s5DECSTSLDLHLLEQMAX",
    "slt5DECODERSTATUSDLHTYPEFTLLISHTYPE",
    "slt5DECODERSTATUSDLHTYPEFTLLISHID"
})
@XmlRootElement(name = "SLT_5_DECODER_STATUS_DLH_TYPE")
public class SLT5DECODERSTATUSDLHTYPE {

    @XmlElement(name = "S5DECSTSLDLH_LC", required = true)
    protected S5DECSTSLDLHLC s5DECSTSLDLHLC;
    @XmlElement(name = "S5DECSTSLDLH_LEDSZ", required = true)
    protected S5DECSTSLDLHLEDSZ s5DECSTSLDLHLEDSZ;
    @XmlElement(name = "SLT_5_DECODER_STATUS_DLH_LEQMAX", required = true)
    protected SLT5DECODERSTATUSDLHLEQMAX slt5DECODERSTATUSDLHLEQMAX;
    @XmlElement(name = "S5DECSTSLDLH_LLEQMAX", required = true)
    protected S5DECSTSLDLHLLEQMAX s5DECSTSLDLHLLEQMAX;
    @XmlElement(name = "SLT_5_DECODER_STATUS_DLH_TYPE_FTLLISHTYPE", required = true)
    protected SLT5DECODERSTATUSDLHTYPEFTLLISHTYPE slt5DECODERSTATUSDLHTYPEFTLLISHTYPE;
    @XmlElement(name = "SLT_5_DECODER_STATUS_DLH_TYPE_FTLLISHID", required = true)
    protected SLT5DECODERSTATUSDLHTYPEFTLLISHID slt5DECODERSTATUSDLHTYPEFTLLISHID;
    @XmlAttribute(name = "Applicable", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String applicable;
    @XmlAttribute(name = "ListID", required = true)
    protected BigInteger listID;

    /**
     * Gets the value of the s5DECSTSLDLHLC property.
     * 
     * @return
     *     possible object is
     *     {@link S5DECSTSLDLHLC }
     *     
     */
    public S5DECSTSLDLHLC getS5DECSTSLDLHLC() {
        return s5DECSTSLDLHLC;
    }

    /**
     * Sets the value of the s5DECSTSLDLHLC property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5DECSTSLDLHLC }
     *     
     */
    public void setS5DECSTSLDLHLC(S5DECSTSLDLHLC value) {
        this.s5DECSTSLDLHLC = value;
    }

    /**
     * Gets the value of the s5DECSTSLDLHLEDSZ property.
     * 
     * @return
     *     possible object is
     *     {@link S5DECSTSLDLHLEDSZ }
     *     
     */
    public S5DECSTSLDLHLEDSZ getS5DECSTSLDLHLEDSZ() {
        return s5DECSTSLDLHLEDSZ;
    }

    /**
     * Sets the value of the s5DECSTSLDLHLEDSZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5DECSTSLDLHLEDSZ }
     *     
     */
    public void setS5DECSTSLDLHLEDSZ(S5DECSTSLDLHLEDSZ value) {
        this.s5DECSTSLDLHLEDSZ = value;
    }

    /**
     * Gets the value of the slt5DECODERSTATUSDLHLEQMAX property.
     * 
     * @return
     *     possible object is
     *     {@link SLT5DECODERSTATUSDLHLEQMAX }
     *     
     */
    public SLT5DECODERSTATUSDLHLEQMAX getSLT5DECODERSTATUSDLHLEQMAX() {
        return slt5DECODERSTATUSDLHLEQMAX;
    }

    /**
     * Sets the value of the slt5DECODERSTATUSDLHLEQMAX property.
     * 
     * @param value
     *     allowed object is
     *     {@link SLT5DECODERSTATUSDLHLEQMAX }
     *     
     */
    public void setSLT5DECODERSTATUSDLHLEQMAX(SLT5DECODERSTATUSDLHLEQMAX value) {
        this.slt5DECODERSTATUSDLHLEQMAX = value;
    }

    /**
     * Gets the value of the s5DECSTSLDLHLLEQMAX property.
     * 
     * @return
     *     possible object is
     *     {@link S5DECSTSLDLHLLEQMAX }
     *     
     */
    public S5DECSTSLDLHLLEQMAX getS5DECSTSLDLHLLEQMAX() {
        return s5DECSTSLDLHLLEQMAX;
    }

    /**
     * Sets the value of the s5DECSTSLDLHLLEQMAX property.
     * 
     * @param value
     *     allowed object is
     *     {@link S5DECSTSLDLHLLEQMAX }
     *     
     */
    public void setS5DECSTSLDLHLLEQMAX(S5DECSTSLDLHLLEQMAX value) {
        this.s5DECSTSLDLHLLEQMAX = value;
    }

    /**
     * Gets the value of the slt5DECODERSTATUSDLHTYPEFTLLISHTYPE property.
     * 
     * @return
     *     possible object is
     *     {@link SLT5DECODERSTATUSDLHTYPEFTLLISHTYPE }
     *     
     */
    public SLT5DECODERSTATUSDLHTYPEFTLLISHTYPE getSLT5DECODERSTATUSDLHTYPEFTLLISHTYPE() {
        return slt5DECODERSTATUSDLHTYPEFTLLISHTYPE;
    }

    /**
     * Sets the value of the slt5DECODERSTATUSDLHTYPEFTLLISHTYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link SLT5DECODERSTATUSDLHTYPEFTLLISHTYPE }
     *     
     */
    public void setSLT5DECODERSTATUSDLHTYPEFTLLISHTYPE(SLT5DECODERSTATUSDLHTYPEFTLLISHTYPE value) {
        this.slt5DECODERSTATUSDLHTYPEFTLLISHTYPE = value;
    }

    /**
     * Gets the value of the slt5DECODERSTATUSDLHTYPEFTLLISHID property.
     * 
     * @return
     *     possible object is
     *     {@link SLT5DECODERSTATUSDLHTYPEFTLLISHID }
     *     
     */
    public SLT5DECODERSTATUSDLHTYPEFTLLISHID getSLT5DECODERSTATUSDLHTYPEFTLLISHID() {
        return slt5DECODERSTATUSDLHTYPEFTLLISHID;
    }

    /**
     * Sets the value of the slt5DECODERSTATUSDLHTYPEFTLLISHID property.
     * 
     * @param value
     *     allowed object is
     *     {@link SLT5DECODERSTATUSDLHTYPEFTLLISHID }
     *     
     */
    public void setSLT5DECODERSTATUSDLHTYPEFTLLISHID(SLT5DECODERSTATUSDLHTYPEFTLLISHID value) {
        this.slt5DECODERSTATUSDLHTYPEFTLLISHID = value;
    }

    /**
     * Gets the value of the applicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicable() {
        return applicable;
    }

    /**
     * Sets the value of the applicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicable(String value) {
        this.applicable = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setListID(BigInteger value) {
        this.listID = value;
    }

}
